global:
  scrape_interval: 15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: "prometheus-stack-monitor"

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  # - job_name: "prometheus"
  #   scrape_interval: 10s
  #   scrape_timeout: 5s
  #   metrics_path: "/metrics"
  #   static_configs:
  #     - targets: ["localhost:9090"]

  # - job_name: "pushgateway"
  #   scrape_interval: 10s
  #   honor_labels: true
  #   static_configs:
  #     - targets: ["pushgateway:9091"]

  - job_name: "webx"
    scrape_interval: 5s
    metrics_path: "/metrics"
    static_configs:
      - targets: ["www.coscms.com"]
