// @generated Do not edit this file, which is automatically generated by the generator.

package dbschema

import (
	"fmt"

	"github.com/webx-top/com"
	"github.com/webx-top/db"
	"github.com/webx-top/db/lib/factory"
	"github.com/webx-top/db/lib/factory/pagination"
	"github.com/webx-top/echo"
	"github.com/webx-top/echo/param"
)

type Slice_OfficialCommonTags = factory.Slicex[*OfficialCommonTags]

func NewOfficialCommonTags(ctx echo.Context) *OfficialCommonTags {
	m := &OfficialCommonTags{}
	m.SetContext(ctx)
	return m
}

// OfficialCommonTags 标签库
type OfficialCommonTags struct {
	base    factory.Base
	objects []*OfficialCommonTags

	Id      uint64 `db:"id,omitempty,pk" bson:"id,omitempty" comment:"ID" json:"id" xml:"id"`
	Name    string `db:"name" bson:"name" comment:"标签名" json:"name" xml:"name"`
	Num     uint64 `db:"num" bson:"num" comment:"数量" json:"num" xml:"num"`
	Group   string `db:"group" bson:"group" comment:"分组标识" json:"group" xml:"group"`
	Display string `db:"display" bson:"display" comment:"是否显示" json:"display" xml:"display"`
}

// - base function

func (a *OfficialCommonTags) Trans() factory.Transactioner {
	return a.base.Trans()
}

func (a *OfficialCommonTags) Use(trans factory.Transactioner) factory.Model {
	a.base.Use(trans)
	return a
}

func (a *OfficialCommonTags) SetContext(ctx echo.Context) factory.Model {
	a.base.SetContext(ctx)
	return a
}

func (a *OfficialCommonTags) EventON(on ...bool) factory.Model {
	a.base.EventON(on...)
	return a
}

func (a *OfficialCommonTags) EventOFF(off ...bool) factory.Model {
	a.base.EventOFF(off...)
	return a
}

func (a *OfficialCommonTags) Context() echo.Context {
	return a.base.Context()
}

func (a *OfficialCommonTags) SetConnID(connID int) factory.Model {
	a.base.SetConnID(connID)
	return a
}

func (a *OfficialCommonTags) ConnID() int {
	return a.base.ConnID()
}

func (a *OfficialCommonTags) SetNamer(namer func(factory.Model) string) factory.Model {
	a.base.SetNamer(namer)
	return a
}

func (a *OfficialCommonTags) Namer() func(factory.Model) string {
	return a.base.Namer()
}

func (a *OfficialCommonTags) SetParam(param *factory.Param) factory.Model {
	a.base.SetParam(param)
	return a
}

func (a *OfficialCommonTags) Param(mw func(db.Result) db.Result, args ...interface{}) *factory.Param {
	if a.base.Param() == nil {
		return a.NewParam().SetMiddleware(mw).SetArgs(args...)
	}
	return a.base.Param().SetMiddleware(mw).SetArgs(args...)
}

func (a *OfficialCommonTags) New(structName string, connID ...int) factory.Model {
	return a.base.New(structName, connID...)
}

func (a *OfficialCommonTags) Base_() factory.Baser {
	return &a.base
}

// - current function

func (a *OfficialCommonTags) Objects() []*OfficialCommonTags {
	if a.objects == nil {
		return nil
	}
	return a.objects[:]
}

func (a *OfficialCommonTags) XObjects() Slice_OfficialCommonTags {
	return Slice_OfficialCommonTags(a.Objects())
}

func (a *OfficialCommonTags) NewObjects() factory.Ranger {
	return &Slice_OfficialCommonTags{}
}

func (a *OfficialCommonTags) InitObjects() *[]*OfficialCommonTags {
	a.objects = []*OfficialCommonTags{}
	return &a.objects
}

func (a *OfficialCommonTags) NewParam() *factory.Param {
	return factory.NewParam(factory.DefaultFactory).SetIndex(a.base.ConnID()).SetTrans(a.base.Trans()).SetCollection(a.Name_()).SetModel(a)
}

func (a *OfficialCommonTags) Short_() string {
	return "official_common_tags"
}

func (a *OfficialCommonTags) Struct_() string {
	return "OfficialCommonTags"
}

func (a *OfficialCommonTags) Name_() string {
	b := a
	if b == nil {
		b = &OfficialCommonTags{}
	}
	if b.base.Namer() != nil {
		return WithPrefix(b.base.Namer()(b))
	}
	return WithPrefix(factory.TableNamerGet(b.Short_())(b))
}

// CPAFrom Deprecated: Use CtxFrom instead.
func (a *OfficialCommonTags) CPAFrom(source factory.Model) factory.Model {
	return a.CtxFrom(source)
}

func (a *OfficialCommonTags) CtxFrom(source factory.Model) factory.Model {
	a.base.CtxFrom(source)
	return a
}

func (a *OfficialCommonTags) Get(mw func(db.Result) db.Result, args ...interface{}) (err error) {
	base := a.base
	if !a.base.Eventable() {
		err = a.Param(mw, args...).SetRecv(a).One()
		a.base = base
		return
	}
	queryParam := a.Param(mw, args...).SetRecv(a)
	if err = a.base.FireReading(a, queryParam); err != nil {
		return
	}
	err = queryParam.One()
	a.base = base
	if err == nil {
		err = a.base.FireReaded(a, queryParam)
	}
	return
}

func (a *OfficialCommonTags) List(recv interface{}, mw func(db.Result) db.Result, page, size int, args ...interface{}) (func() int64, error) {
	if recv == nil {
		recv = a.InitObjects()
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetPage(page).SetSize(size).SetRecv(recv).List()
	}
	queryParam := a.Param(mw, args...).SetPage(page).SetSize(size).SetRecv(recv)
	if err := a.base.FireReading(a, queryParam); err != nil {
		return nil, err
	}
	cnt, err := queryParam.List()
	if err == nil {
		switch v := recv.(type) {
		case *[]*OfficialCommonTags:
			err = a.base.FireReaded(a, queryParam, Slice_OfficialCommonTags(*v))
		case []*OfficialCommonTags:
			err = a.base.FireReaded(a, queryParam, Slice_OfficialCommonTags(v))
		case factory.Ranger:
			err = a.base.FireReaded(a, queryParam, v)
		}
	}
	return cnt, err
}

func (a *OfficialCommonTags) GroupBy(keyField string, inputRows ...[]*OfficialCommonTags) map[string][]*OfficialCommonTags {
	var rows Slice_OfficialCommonTags
	if len(inputRows) > 0 {
		rows = Slice_OfficialCommonTags(inputRows[0])
	} else {
		rows = Slice_OfficialCommonTags(a.Objects())
	}
	return rows.GroupBy(keyField)
}

func (a *OfficialCommonTags) KeyBy(keyField string, inputRows ...[]*OfficialCommonTags) map[string]*OfficialCommonTags {
	var rows Slice_OfficialCommonTags
	if len(inputRows) > 0 {
		rows = Slice_OfficialCommonTags(inputRows[0])
	} else {
		rows = Slice_OfficialCommonTags(a.Objects())
	}
	return rows.KeyBy(keyField)
}

func (a *OfficialCommonTags) AsKV(keyField string, valueField string, inputRows ...[]*OfficialCommonTags) param.Store {
	var rows Slice_OfficialCommonTags
	if len(inputRows) > 0 {
		rows = Slice_OfficialCommonTags(inputRows[0])
	} else {
		rows = Slice_OfficialCommonTags(a.Objects())
	}
	return rows.AsKV(keyField, valueField)
}

func (a *OfficialCommonTags) ListByOffset(recv interface{}, mw func(db.Result) db.Result, offset, size int, args ...interface{}) (func() int64, error) {
	if recv == nil {
		recv = a.InitObjects()
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetOffset(offset).SetSize(size).SetRecv(recv).List()
	}
	queryParam := a.Param(mw, args...).SetOffset(offset).SetSize(size).SetRecv(recv)
	if err := a.base.FireReading(a, queryParam); err != nil {
		return nil, err
	}
	cnt, err := queryParam.List()
	if err == nil {
		switch v := recv.(type) {
		case *[]*OfficialCommonTags:
			err = a.base.FireReaded(a, queryParam, Slice_OfficialCommonTags(*v))
		case []*OfficialCommonTags:
			err = a.base.FireReaded(a, queryParam, Slice_OfficialCommonTags(v))
		case factory.Ranger:
			err = a.base.FireReaded(a, queryParam, v)
		}
	}
	return cnt, err
}

func (a *OfficialCommonTags) Insert() (pk interface{}, err error) {
	a.Id = 0
	if len(a.Display) == 0 {
		a.Display = "Y"
	}
	if a.base.Eventable() {
		err = a.base.Fire(factory.EventCreating, a, nil)
		if err != nil {
			return
		}
	}
	pk, err = a.Param(nil).SetSend(a).Insert()
	if err == nil && pk != nil {
		if v, y := pk.(uint64); y {
			a.Id = v
		} else if v, y := pk.(int64); y {
			a.Id = uint64(v)
		}
	}
	if err == nil && a.base.Eventable() {
		err = a.base.Fire(factory.EventCreated, a, nil)
	}
	return
}

func (a *OfficialCommonTags) Update(mw func(db.Result) db.Result, args ...interface{}) (err error) {

	if len(a.Display) == 0 {
		a.Display = "Y"
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(a).Update()
	}
	if err = a.base.Fire(factory.EventUpdating, a, mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).SetSend(a).Update(); err != nil {
		return
	}
	return a.base.Fire(factory.EventUpdated, a, mw, args...)
}

func (a *OfficialCommonTags) Updatex(mw func(db.Result) db.Result, args ...interface{}) (affected int64, err error) {

	if len(a.Display) == 0 {
		a.Display = "Y"
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(a).Updatex()
	}
	if err = a.base.Fire(factory.EventUpdating, a, mw, args...); err != nil {
		return
	}
	if affected, err = a.Param(mw, args...).SetSend(a).Updatex(); err != nil {
		return
	}
	err = a.base.Fire(factory.EventUpdated, a, mw, args...)
	return
}

func (a *OfficialCommonTags) UpdateByFields(mw func(db.Result) db.Result, fields []string, args ...interface{}) (err error) {

	if len(a.Display) == 0 {
		a.Display = "Y"
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).UpdateByStruct(a, fields...)
	}
	editColumns := make([]string, len(fields))
	for index, field := range fields {
		editColumns[index] = com.SnakeCase(field)
	}
	if err = a.base.FireUpdate(factory.EventUpdating, a, editColumns, mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).UpdateByStruct(a, fields...); err != nil {
		return
	}
	err = a.base.FireUpdate(factory.EventUpdated, a, editColumns, mw, args...)
	return
}

func (a *OfficialCommonTags) UpdatexByFields(mw func(db.Result) db.Result, fields []string, args ...interface{}) (affected int64, err error) {

	if len(a.Display) == 0 {
		a.Display = "Y"
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).UpdatexByStruct(a, fields...)
	}
	editColumns := make([]string, len(fields))
	for index, field := range fields {
		editColumns[index] = com.SnakeCase(field)
	}
	if err = a.base.FireUpdate(factory.EventUpdating, a, editColumns, mw, args...); err != nil {
		return
	}
	if affected, err = a.Param(mw, args...).UpdatexByStruct(a, fields...); err != nil {
		return
	}
	err = a.base.FireUpdate(factory.EventUpdated, a, editColumns, mw, args...)
	return
}

func (a *OfficialCommonTags) UpdateField(mw func(db.Result) db.Result, field string, value interface{}, args ...interface{}) (err error) {
	return a.UpdateFields(mw, map[string]interface{}{
		field: value,
	}, args...)
}

func (a *OfficialCommonTags) UpdatexField(mw func(db.Result) db.Result, field string, value interface{}, args ...interface{}) (affected int64, err error) {
	return a.UpdatexFields(mw, map[string]interface{}{
		field: value,
	}, args...)
}

func (a *OfficialCommonTags) UpdateFields(mw func(db.Result) db.Result, kvset map[string]interface{}, args ...interface{}) (err error) {

	if val, ok := kvset["display"]; ok && val != nil {
		if v, ok := val.(string); ok && len(v) == 0 {
			kvset["display"] = "Y"
		}
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(kvset).Update()
	}
	m := *a
	m.FromRow(kvset)
	editColumns := make([]string, 0, len(kvset))
	for column := range kvset {
		editColumns = append(editColumns, column)
	}
	if err = a.base.FireUpdate(factory.EventUpdating, &m, editColumns, mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).SetSend(kvset).Update(); err != nil {
		return
	}
	return a.base.FireUpdate(factory.EventUpdated, &m, editColumns, mw, args...)
}

func (a *OfficialCommonTags) UpdatexFields(mw func(db.Result) db.Result, kvset map[string]interface{}, args ...interface{}) (affected int64, err error) {

	if val, ok := kvset["display"]; ok && val != nil {
		if v, ok := val.(string); ok && len(v) == 0 {
			kvset["display"] = "Y"
		}
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(kvset).Updatex()
	}
	m := *a
	m.FromRow(kvset)
	editColumns := make([]string, 0, len(kvset))
	for column := range kvset {
		editColumns = append(editColumns, column)
	}
	if err = a.base.FireUpdate(factory.EventUpdating, &m, editColumns, mw, args...); err != nil {
		return
	}
	if affected, err = a.Param(mw, args...).SetSend(kvset).Updatex(); err != nil {
		return
	}
	err = a.base.FireUpdate(factory.EventUpdated, &m, editColumns, mw, args...)
	return
}

func (a *OfficialCommonTags) UpdateValues(mw func(db.Result) db.Result, keysValues *db.KeysValues, args ...interface{}) (err error) {
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(keysValues).Update()
	}
	m := *a
	m.FromRow(keysValues.Map())
	if err = a.base.FireUpdate(factory.EventUpdating, &m, keysValues.Keys(), mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).SetSend(keysValues).Update(); err != nil {
		return
	}
	return a.base.FireUpdate(factory.EventUpdated, &m, keysValues.Keys(), mw, args...)
}

func (a *OfficialCommonTags) Upsert(mw func(db.Result) db.Result, args ...interface{}) (pk interface{}, err error) {
	pk, err = a.Param(mw, args...).SetSend(a).Upsert(func() error {
		if len(a.Display) == 0 {
			a.Display = "Y"
		}
		if !a.base.Eventable() {
			return nil
		}
		return a.base.Fire(factory.EventUpdating, a, mw, args...)
	}, func() error {
		a.Id = 0
		if len(a.Display) == 0 {
			a.Display = "Y"
		}
		if !a.base.Eventable() {
			return nil
		}
		return a.base.Fire(factory.EventCreating, a, nil)
	})
	if err == nil && pk != nil {
		if v, y := pk.(uint64); y {
			a.Id = v
		} else if v, y := pk.(int64); y {
			a.Id = uint64(v)
		}
	}
	if err == nil && a.base.Eventable() {
		if pk == nil {
			err = a.base.Fire(factory.EventUpdated, a, mw, args...)
		} else {
			err = a.base.Fire(factory.EventCreated, a, nil)
		}
	}
	return
}

func (a *OfficialCommonTags) Delete(mw func(db.Result) db.Result, args ...interface{}) (err error) {

	if !a.base.Eventable() {
		return a.Param(mw, args...).Delete()
	}
	if err = a.base.Fire(factory.EventDeleting, a, mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).Delete(); err != nil {
		return
	}
	return a.base.Fire(factory.EventDeleted, a, mw, args...)
}

func (a *OfficialCommonTags) Deletex(mw func(db.Result) db.Result, args ...interface{}) (affected int64, err error) {

	if !a.base.Eventable() {
		return a.Param(mw, args...).Deletex()
	}
	if err = a.base.Fire(factory.EventDeleting, a, mw, args...); err != nil {
		return
	}
	if affected, err = a.Param(mw, args...).Deletex(); err != nil {
		return
	}
	err = a.base.Fire(factory.EventDeleted, a, mw, args...)
	return
}

func (a *OfficialCommonTags) Count(mw func(db.Result) db.Result, args ...interface{}) (int64, error) {
	return a.Param(mw, args...).Count()
}

func (a *OfficialCommonTags) Exists(mw func(db.Result) db.Result, args ...interface{}) (bool, error) {
	return a.Param(mw, args...).Exists()
}

func (a *OfficialCommonTags) Reset() *OfficialCommonTags {
	a.Id = 0
	a.Name = ``
	a.Num = 0
	a.Group = ``
	a.Display = ``
	return a
}

func (a *OfficialCommonTags) AsMap(onlyFields ...string) param.Store {
	r := param.Store{}
	if len(onlyFields) == 0 {
		r["Id"] = a.Id
		r["Name"] = a.Name
		r["Num"] = a.Num
		r["Group"] = a.Group
		r["Display"] = a.Display
		return r
	}
	for _, field := range onlyFields {
		switch field {
		case "Id":
			r["Id"] = a.Id
		case "Name":
			r["Name"] = a.Name
		case "Num":
			r["Num"] = a.Num
		case "Group":
			r["Group"] = a.Group
		case "Display":
			r["Display"] = a.Display
		}
	}
	return r
}

func (a *OfficialCommonTags) Clone() *OfficialCommonTags {
	cloned := OfficialCommonTags{Id: a.Id, Name: a.Name, Num: a.Num, Group: a.Group, Display: a.Display}
	cloned.CtxFrom(a)
	return &cloned
}

func (a *OfficialCommonTags) FromRow(row map[string]interface{}) {
	for key, value := range row {
		if _, ok := value.(db.RawValue); ok {
			continue
		}
		switch key {
		case "id":
			a.Id = param.AsUint64(value)
		case "name":
			a.Name = param.AsString(value)
		case "num":
			a.Num = param.AsUint64(value)
		case "group":
			a.Group = param.AsString(value)
		case "display":
			a.Display = param.AsString(value)
		}
	}
}

func (a *OfficialCommonTags) GetField(field string) interface{} {
	switch field {
	case "Id":
		return a.Id
	case "Name":
		return a.Name
	case "Num":
		return a.Num
	case "Group":
		return a.Group
	case "Display":
		return a.Display
	default:
		return nil
	}
}

func (a *OfficialCommonTags) GetAllFieldNames() []string {
	return []string{
		"Id",
		"Name",
		"Num",
		"Group",
		"Display",
	}
}

func (a *OfficialCommonTags) HasField(field string) bool {
	switch field {
	case "Id":
		return true
	case "Name":
		return true
	case "Num":
		return true
	case "Group":
		return true
	case "Display":
		return true
	default:
		return false
	}
}

func (a *OfficialCommonTags) Set(key interface{}, value ...interface{}) {
	switch k := key.(type) {
	case map[string]interface{}:
		for kk, vv := range k {
			a.Set(kk, vv)
		}
	default:
		var (
			kk string
			vv interface{}
		)
		if k, y := key.(string); y {
			kk = k
		} else {
			kk = fmt.Sprint(key)
		}
		if len(value) > 0 {
			vv = value[0]
		}
		switch kk {
		case "Id":
			a.Id = param.AsUint64(vv)
		case "Name":
			a.Name = param.AsString(vv)
		case "Num":
			a.Num = param.AsUint64(vv)
		case "Group":
			a.Group = param.AsString(vv)
		case "Display":
			a.Display = param.AsString(vv)
		}
	}
}

func (a *OfficialCommonTags) AsRow(onlyFields ...string) param.Store {
	r := param.Store{}
	if len(onlyFields) == 0 {
		r["id"] = a.Id
		r["name"] = a.Name
		r["num"] = a.Num
		r["group"] = a.Group
		r["display"] = a.Display
		return r
	}
	for _, field := range onlyFields {
		switch field {
		case "id":
			r["id"] = a.Id
		case "name":
			r["name"] = a.Name
		case "num":
			r["num"] = a.Num
		case "group":
			r["group"] = a.Group
		case "display":
			r["display"] = a.Display
		}
	}
	return r
}

func (a *OfficialCommonTags) ListPage(cond *db.Compounds, sorts ...interface{}) error {
	return pagination.ListPage(a, cond, sorts...)
}

func (a *OfficialCommonTags) ListPageAs(recv interface{}, cond *db.Compounds, sorts ...interface{}) error {
	return pagination.ListPageAs(a, recv, cond, sorts...)
}

func (a *OfficialCommonTags) ListPageByOffset(cond *db.Compounds, sorts ...interface{}) error {
	return pagination.ListPageByOffset(a, cond, sorts...)
}

func (a *OfficialCommonTags) ListPageByOffsetAs(recv interface{}, cond *db.Compounds, sorts ...interface{}) error {
	return pagination.ListPageByOffsetAs(a, recv, cond, sorts...)
}

func (a *OfficialCommonTags) BatchValidate(kvset map[string]interface{}) error {
	return a.base.BatchValidate(a, kvset)
}

func (a *OfficialCommonTags) Validate(column string, value interface{}) error {
	return a.base.Validate(a, column, value)
}

func (a *OfficialCommonTags) TrimOverflowText(column string, value string) string {
	return a.base.TrimOverflowText(a, column, value)
}
