// @generated Do not edit this file, which is automatically generated by the generator.

package dbschema

import (
	"fmt"

	"time"

	"github.com/webx-top/com"
	"github.com/webx-top/db"
	"github.com/webx-top/db/lib/factory"
	"github.com/webx-top/db/lib/factory/pagination"
	"github.com/webx-top/echo"
	"github.com/webx-top/echo/param"
)

type Slice_OfficialCommonCategory []*OfficialCommonCategory

func (s Slice_OfficialCommonCategory) Range(fn func(m factory.Model) error) error {
	for _, v := range s {
		if err := fn(v); err != nil {
			return err
		}
	}
	return nil
}

func (s Slice_OfficialCommonCategory) RangeRaw(fn func(m *OfficialCommonCategory) error) error {
	for _, v := range s {
		if err := fn(v); err != nil {
			return err
		}
	}
	return nil
}

func (s Slice_OfficialCommonCategory) GroupBy(keyField string) map[string][]*OfficialCommonCategory {
	r := map[string][]*OfficialCommonCategory{}
	for _, row := range s {
		dmap := row.AsMap()
		vkey := fmt.Sprint(dmap[keyField])
		if _, y := r[vkey]; !y {
			r[vkey] = []*OfficialCommonCategory{}
		}
		r[vkey] = append(r[vkey], row)
	}
	return r
}

func (s Slice_OfficialCommonCategory) KeyBy(keyField string) map[string]*OfficialCommonCategory {
	r := map[string]*OfficialCommonCategory{}
	for _, row := range s {
		dmap := row.AsMap()
		vkey := fmt.Sprint(dmap[keyField])
		r[vkey] = row
	}
	return r
}

func (s Slice_OfficialCommonCategory) AsKV(keyField string, valueField string) param.Store {
	r := param.Store{}
	for _, row := range s {
		dmap := row.AsMap()
		vkey := fmt.Sprint(dmap[keyField])
		r[vkey] = dmap[valueField]
	}
	return r
}

func (s Slice_OfficialCommonCategory) Transform(transfers map[string]param.Transfer) []param.Store {
	r := make([]param.Store, len(s))
	for idx, row := range s {
		r[idx] = row.AsMap().Transform(transfers)
	}
	return r
}

func (s Slice_OfficialCommonCategory) FromList(data interface{}) Slice_OfficialCommonCategory {
	values, ok := data.([]*OfficialCommonCategory)
	if !ok {
		for _, value := range data.([]interface{}) {
			row := &OfficialCommonCategory{}
			row.FromRow(value.(map[string]interface{}))
			s = append(s, row)
		}
		return s
	}
	s = append(s, values...)

	return s
}

func NewOfficialCommonCategory(ctx echo.Context) *OfficialCommonCategory {
	m := &OfficialCommonCategory{}
	m.SetContext(ctx)
	return m
}

// OfficialCommonCategory 分类
type OfficialCommonCategory struct {
	base    factory.Base
	objects []*OfficialCommonCategory

	Id          uint   `db:"id,omitempty,pk" bson:"id,omitempty" comment:"ID" json:"id" xml:"id"`
	ParentId    uint   `db:"parent_id" bson:"parent_id" comment:"上级分类ID" json:"parent_id" xml:"parent_id"`
	HasChild    string `db:"has_child" bson:"has_child" comment:"是否有子分类" json:"has_child" xml:"has_child"`
	Level       uint   `db:"level" bson:"level" comment:"层级" json:"level" xml:"level"`
	Name        string `db:"name" bson:"name" comment:"分类名称" json:"name" xml:"name"`
	Keywords    string `db:"keywords" bson:"keywords" comment:"分类页面关键词" json:"keywords" xml:"keywords"`
	Description string `db:"description" bson:"description" comment:"分类说明" json:"description" xml:"description"`
	Cover       string `db:"cover" bson:"cover" comment:"分类封面图" json:"cover" xml:"cover"`
	Type        string `db:"type" bson:"type" comment:"类型" json:"type" xml:"type"`
	Sort        int    `db:"sort" bson:"sort" comment:"排序编号(从小到大)" json:"sort" xml:"sort"`
	Template    string `db:"template" bson:"template" comment:"分类列表页模版" json:"template" xml:"template"`
	Disabled    string `db:"disabled" bson:"disabled" comment:"是否(Y/N)禁用" json:"disabled" xml:"disabled"`
	ShowOnMenu  string `db:"show_on_menu" bson:"show_on_menu" comment:"是否(Y/N)显示在导航菜单上" json:"show_on_menu" xml:"show_on_menu"`
	Created     uint   `db:"created" bson:"created" comment:"创建时间" json:"created" xml:"created"`
	Updated     uint   `db:"updated" bson:"updated" comment:"更新时间" json:"updated" xml:"updated"`
	Slugify     string `db:"slugify" bson:"slugify" comment:"SEO-friendly URLs with Slugify" json:"slugify" xml:"slugify"`
}

// - base function

func (a *OfficialCommonCategory) Trans() factory.Transactioner {
	return a.base.Trans()
}

func (a *OfficialCommonCategory) Use(trans factory.Transactioner) factory.Model {
	a.base.Use(trans)
	return a
}

func (a *OfficialCommonCategory) SetContext(ctx echo.Context) factory.Model {
	a.base.SetContext(ctx)
	return a
}

func (a *OfficialCommonCategory) EventON(on ...bool) factory.Model {
	a.base.EventON(on...)
	return a
}

func (a *OfficialCommonCategory) EventOFF(off ...bool) factory.Model {
	a.base.EventOFF(off...)
	return a
}

func (a *OfficialCommonCategory) Context() echo.Context {
	return a.base.Context()
}

func (a *OfficialCommonCategory) SetConnID(connID int) factory.Model {
	a.base.SetConnID(connID)
	return a
}

func (a *OfficialCommonCategory) ConnID() int {
	return a.base.ConnID()
}

func (a *OfficialCommonCategory) SetNamer(namer func(factory.Model) string) factory.Model {
	a.base.SetNamer(namer)
	return a
}

func (a *OfficialCommonCategory) Namer() func(factory.Model) string {
	return a.base.Namer()
}

func (a *OfficialCommonCategory) SetParam(param *factory.Param) factory.Model {
	a.base.SetParam(param)
	return a
}

func (a *OfficialCommonCategory) Param(mw func(db.Result) db.Result, args ...interface{}) *factory.Param {
	if a.base.Param() == nil {
		return a.NewParam().SetMiddleware(mw).SetArgs(args...)
	}
	return a.base.Param().SetMiddleware(mw).SetArgs(args...)
}

func (a *OfficialCommonCategory) New(structName string, connID ...int) factory.Model {
	return a.base.New(structName, connID...)
}

func (a *OfficialCommonCategory) Base_() factory.Baser {
	return &a.base
}

// - current function

func (a *OfficialCommonCategory) Objects() []*OfficialCommonCategory {
	if a.objects == nil {
		return nil
	}
	return a.objects[:]
}

func (a *OfficialCommonCategory) XObjects() Slice_OfficialCommonCategory {
	return Slice_OfficialCommonCategory(a.Objects())
}

func (a *OfficialCommonCategory) NewObjects() factory.Ranger {
	return &Slice_OfficialCommonCategory{}
}

func (a *OfficialCommonCategory) InitObjects() *[]*OfficialCommonCategory {
	a.objects = []*OfficialCommonCategory{}
	return &a.objects
}

func (a *OfficialCommonCategory) NewParam() *factory.Param {
	return factory.NewParam(factory.DefaultFactory).SetIndex(a.base.ConnID()).SetTrans(a.base.Trans()).SetCollection(a.Name_()).SetModel(a)
}

func (a *OfficialCommonCategory) Short_() string {
	return "official_common_category"
}

func (a *OfficialCommonCategory) Struct_() string {
	return "OfficialCommonCategory"
}

func (a *OfficialCommonCategory) Name_() string {
	b := a
	if b == nil {
		b = &OfficialCommonCategory{}
	}
	if b.base.Namer() != nil {
		return WithPrefix(b.base.Namer()(b))
	}
	return WithPrefix(factory.TableNamerGet(b.Short_())(b))
}

func (a *OfficialCommonCategory) CPAFrom(source factory.Model) factory.Model {
	a.SetContext(source.Context())
	a.SetConnID(source.ConnID())
	a.SetNamer(source.Namer())
	return a
}

func (a *OfficialCommonCategory) Get(mw func(db.Result) db.Result, args ...interface{}) (err error) {
	base := a.base
	if !a.base.Eventable() {
		err = a.Param(mw, args...).SetRecv(a).One()
		a.base = base
		return
	}
	queryParam := a.Param(mw, args...).SetRecv(a)
	if err = DBI.FireReading(a, queryParam); err != nil {
		return
	}
	err = queryParam.One()
	a.base = base
	if err == nil {
		err = DBI.FireReaded(a, queryParam)
	}
	return
}

func (a *OfficialCommonCategory) List(recv interface{}, mw func(db.Result) db.Result, page, size int, args ...interface{}) (func() int64, error) {
	if recv == nil {
		recv = a.InitObjects()
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetPage(page).SetSize(size).SetRecv(recv).List()
	}
	queryParam := a.Param(mw, args...).SetPage(page).SetSize(size).SetRecv(recv)
	if err := DBI.FireReading(a, queryParam); err != nil {
		return nil, err
	}
	cnt, err := queryParam.List()
	if err == nil {
		switch v := recv.(type) {
		case *[]*OfficialCommonCategory:
			err = DBI.FireReaded(a, queryParam, Slice_OfficialCommonCategory(*v))
		case []*OfficialCommonCategory:
			err = DBI.FireReaded(a, queryParam, Slice_OfficialCommonCategory(v))
		case factory.Ranger:
			err = DBI.FireReaded(a, queryParam, v)
		}
	}
	return cnt, err
}

func (a *OfficialCommonCategory) GroupBy(keyField string, inputRows ...[]*OfficialCommonCategory) map[string][]*OfficialCommonCategory {
	var rows Slice_OfficialCommonCategory
	if len(inputRows) > 0 {
		rows = Slice_OfficialCommonCategory(inputRows[0])
	} else {
		rows = Slice_OfficialCommonCategory(a.Objects())
	}
	return rows.GroupBy(keyField)
}

func (a *OfficialCommonCategory) KeyBy(keyField string, inputRows ...[]*OfficialCommonCategory) map[string]*OfficialCommonCategory {
	var rows Slice_OfficialCommonCategory
	if len(inputRows) > 0 {
		rows = Slice_OfficialCommonCategory(inputRows[0])
	} else {
		rows = Slice_OfficialCommonCategory(a.Objects())
	}
	return rows.KeyBy(keyField)
}

func (a *OfficialCommonCategory) AsKV(keyField string, valueField string, inputRows ...[]*OfficialCommonCategory) param.Store {
	var rows Slice_OfficialCommonCategory
	if len(inputRows) > 0 {
		rows = Slice_OfficialCommonCategory(inputRows[0])
	} else {
		rows = Slice_OfficialCommonCategory(a.Objects())
	}
	return rows.AsKV(keyField, valueField)
}

func (a *OfficialCommonCategory) ListByOffset(recv interface{}, mw func(db.Result) db.Result, offset, size int, args ...interface{}) (func() int64, error) {
	if recv == nil {
		recv = a.InitObjects()
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetOffset(offset).SetSize(size).SetRecv(recv).List()
	}
	queryParam := a.Param(mw, args...).SetOffset(offset).SetSize(size).SetRecv(recv)
	if err := DBI.FireReading(a, queryParam); err != nil {
		return nil, err
	}
	cnt, err := queryParam.List()
	if err == nil {
		switch v := recv.(type) {
		case *[]*OfficialCommonCategory:
			err = DBI.FireReaded(a, queryParam, Slice_OfficialCommonCategory(*v))
		case []*OfficialCommonCategory:
			err = DBI.FireReaded(a, queryParam, Slice_OfficialCommonCategory(v))
		case factory.Ranger:
			err = DBI.FireReaded(a, queryParam, v)
		}
	}
	return cnt, err
}

func (a *OfficialCommonCategory) Insert() (pk interface{}, err error) {
	a.Created = uint(time.Now().Unix())
	a.Id = 0
	if len(a.HasChild) == 0 {
		a.HasChild = "N"
	}
	if len(a.Type) == 0 {
		a.Type = "article"
	}
	if len(a.Disabled) == 0 {
		a.Disabled = "N"
	}
	if len(a.ShowOnMenu) == 0 {
		a.ShowOnMenu = "Y"
	}
	if a.base.Eventable() {
		err = DBI.Fire("creating", a, nil)
		if err != nil {
			return
		}
	}
	pk, err = a.Param(nil).SetSend(a).Insert()
	if err == nil && pk != nil {
		if v, y := pk.(uint); y {
			a.Id = v
		} else if v, y := pk.(int64); y {
			a.Id = uint(v)
		}
	}
	if err == nil && a.base.Eventable() {
		err = DBI.Fire("created", a, nil)
	}
	return
}

func (a *OfficialCommonCategory) Update(mw func(db.Result) db.Result, args ...interface{}) (err error) {
	a.Updated = uint(time.Now().Unix())
	if len(a.HasChild) == 0 {
		a.HasChild = "N"
	}
	if len(a.Type) == 0 {
		a.Type = "article"
	}
	if len(a.Disabled) == 0 {
		a.Disabled = "N"
	}
	if len(a.ShowOnMenu) == 0 {
		a.ShowOnMenu = "Y"
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(a).Update()
	}
	if err = DBI.Fire("updating", a, mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).SetSend(a).Update(); err != nil {
		return
	}
	return DBI.Fire("updated", a, mw, args...)
}

func (a *OfficialCommonCategory) Updatex(mw func(db.Result) db.Result, args ...interface{}) (affected int64, err error) {
	a.Updated = uint(time.Now().Unix())
	if len(a.HasChild) == 0 {
		a.HasChild = "N"
	}
	if len(a.Type) == 0 {
		a.Type = "article"
	}
	if len(a.Disabled) == 0 {
		a.Disabled = "N"
	}
	if len(a.ShowOnMenu) == 0 {
		a.ShowOnMenu = "Y"
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(a).Updatex()
	}
	if err = DBI.Fire("updating", a, mw, args...); err != nil {
		return
	}
	if affected, err = a.Param(mw, args...).SetSend(a).Updatex(); err != nil {
		return
	}
	err = DBI.Fire("updated", a, mw, args...)
	return
}

func (a *OfficialCommonCategory) UpdateByFields(mw func(db.Result) db.Result, fields []string, args ...interface{}) (err error) {
	a.Updated = uint(time.Now().Unix())
	if len(a.HasChild) == 0 {
		a.HasChild = "N"
	}
	if len(a.Type) == 0 {
		a.Type = "article"
	}
	if len(a.Disabled) == 0 {
		a.Disabled = "N"
	}
	if len(a.ShowOnMenu) == 0 {
		a.ShowOnMenu = "Y"
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).UpdateByStruct(a, fields...)
	}
	editColumns := make([]string, len(fields))
	for index, field := range fields {
		editColumns[index] = com.SnakeCase(field)
	}
	if err = DBI.FireUpdate("updating", a, editColumns, mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).UpdateByStruct(a, fields...); err != nil {
		return
	}
	err = DBI.FireUpdate("updated", a, editColumns, mw, args...)
	return
}

func (a *OfficialCommonCategory) UpdatexByFields(mw func(db.Result) db.Result, fields []string, args ...interface{}) (affected int64, err error) {
	a.Updated = uint(time.Now().Unix())
	if len(a.HasChild) == 0 {
		a.HasChild = "N"
	}
	if len(a.Type) == 0 {
		a.Type = "article"
	}
	if len(a.Disabled) == 0 {
		a.Disabled = "N"
	}
	if len(a.ShowOnMenu) == 0 {
		a.ShowOnMenu = "Y"
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).UpdatexByStruct(a, fields...)
	}
	editColumns := make([]string, len(fields))
	for index, field := range fields {
		editColumns[index] = com.SnakeCase(field)
	}
	if err = DBI.FireUpdate("updating", a, editColumns, mw, args...); err != nil {
		return
	}
	if affected, err = a.Param(mw, args...).UpdatexByStruct(a, fields...); err != nil {
		return
	}
	err = DBI.FireUpdate("updated", a, editColumns, mw, args...)
	return
}

func (a *OfficialCommonCategory) UpdateField(mw func(db.Result) db.Result, field string, value interface{}, args ...interface{}) (err error) {
	return a.UpdateFields(mw, map[string]interface{}{
		field: value,
	}, args...)
}

func (a *OfficialCommonCategory) UpdatexField(mw func(db.Result) db.Result, field string, value interface{}, args ...interface{}) (affected int64, err error) {
	return a.UpdatexFields(mw, map[string]interface{}{
		field: value,
	}, args...)
}

func (a *OfficialCommonCategory) UpdateFields(mw func(db.Result) db.Result, kvset map[string]interface{}, args ...interface{}) (err error) {

	if val, ok := kvset["has_child"]; ok && val != nil {
		if v, ok := val.(string); ok && len(v) == 0 {
			kvset["has_child"] = "N"
		}
	}
	if val, ok := kvset["type"]; ok && val != nil {
		if v, ok := val.(string); ok && len(v) == 0 {
			kvset["type"] = "article"
		}
	}
	if val, ok := kvset["disabled"]; ok && val != nil {
		if v, ok := val.(string); ok && len(v) == 0 {
			kvset["disabled"] = "N"
		}
	}
	if val, ok := kvset["show_on_menu"]; ok && val != nil {
		if v, ok := val.(string); ok && len(v) == 0 {
			kvset["show_on_menu"] = "Y"
		}
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(kvset).Update()
	}
	m := *a
	m.FromRow(kvset)
	var editColumns []string
	for column := range kvset {
		editColumns = append(editColumns, column)
	}
	if err = DBI.FireUpdate("updating", &m, editColumns, mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).SetSend(kvset).Update(); err != nil {
		return
	}
	return DBI.FireUpdate("updated", &m, editColumns, mw, args...)
}

func (a *OfficialCommonCategory) UpdatexFields(mw func(db.Result) db.Result, kvset map[string]interface{}, args ...interface{}) (affected int64, err error) {

	if val, ok := kvset["has_child"]; ok && val != nil {
		if v, ok := val.(string); ok && len(v) == 0 {
			kvset["has_child"] = "N"
		}
	}
	if val, ok := kvset["type"]; ok && val != nil {
		if v, ok := val.(string); ok && len(v) == 0 {
			kvset["type"] = "article"
		}
	}
	if val, ok := kvset["disabled"]; ok && val != nil {
		if v, ok := val.(string); ok && len(v) == 0 {
			kvset["disabled"] = "N"
		}
	}
	if val, ok := kvset["show_on_menu"]; ok && val != nil {
		if v, ok := val.(string); ok && len(v) == 0 {
			kvset["show_on_menu"] = "Y"
		}
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(kvset).Updatex()
	}
	m := *a
	m.FromRow(kvset)
	var editColumns []string
	for column := range kvset {
		editColumns = append(editColumns, column)
	}
	if err = DBI.FireUpdate("updating", &m, editColumns, mw, args...); err != nil {
		return
	}
	if affected, err = a.Param(mw, args...).SetSend(kvset).Updatex(); err != nil {
		return
	}
	err = DBI.FireUpdate("updated", &m, editColumns, mw, args...)
	return
}

func (a *OfficialCommonCategory) UpdateValues(mw func(db.Result) db.Result, keysValues *db.KeysValues, args ...interface{}) (err error) {
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(keysValues).Update()
	}
	m := *a
	m.FromRow(keysValues.Map())
	if err = DBI.FireUpdate("updating", &m, keysValues.Keys(), mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).SetSend(keysValues).Update(); err != nil {
		return
	}
	return DBI.FireUpdate("updated", &m, keysValues.Keys(), mw, args...)
}

func (a *OfficialCommonCategory) Upsert(mw func(db.Result) db.Result, args ...interface{}) (pk interface{}, err error) {
	pk, err = a.Param(mw, args...).SetSend(a).Upsert(func() error {
		a.Updated = uint(time.Now().Unix())
		if len(a.HasChild) == 0 {
			a.HasChild = "N"
		}
		if len(a.Type) == 0 {
			a.Type = "article"
		}
		if len(a.Disabled) == 0 {
			a.Disabled = "N"
		}
		if len(a.ShowOnMenu) == 0 {
			a.ShowOnMenu = "Y"
		}
		if !a.base.Eventable() {
			return nil
		}
		return DBI.Fire("updating", a, mw, args...)
	}, func() error {
		a.Created = uint(time.Now().Unix())
		a.Id = 0
		if len(a.HasChild) == 0 {
			a.HasChild = "N"
		}
		if len(a.Type) == 0 {
			a.Type = "article"
		}
		if len(a.Disabled) == 0 {
			a.Disabled = "N"
		}
		if len(a.ShowOnMenu) == 0 {
			a.ShowOnMenu = "Y"
		}
		if !a.base.Eventable() {
			return nil
		}
		return DBI.Fire("creating", a, nil)
	})
	if err == nil && pk != nil {
		if v, y := pk.(uint); y {
			a.Id = v
		} else if v, y := pk.(int64); y {
			a.Id = uint(v)
		}
	}
	if err == nil && a.base.Eventable() {
		if pk == nil {
			err = DBI.Fire("updated", a, mw, args...)
		} else {
			err = DBI.Fire("created", a, nil)
		}
	}
	return
}

func (a *OfficialCommonCategory) Delete(mw func(db.Result) db.Result, args ...interface{}) (err error) {

	if !a.base.Eventable() {
		return a.Param(mw, args...).Delete()
	}
	if err = DBI.Fire("deleting", a, mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).Delete(); err != nil {
		return
	}
	return DBI.Fire("deleted", a, mw, args...)
}

func (a *OfficialCommonCategory) Deletex(mw func(db.Result) db.Result, args ...interface{}) (affected int64, err error) {

	if !a.base.Eventable() {
		return a.Param(mw, args...).Deletex()
	}
	if err = DBI.Fire("deleting", a, mw, args...); err != nil {
		return
	}
	if affected, err = a.Param(mw, args...).Deletex(); err != nil {
		return
	}
	err = DBI.Fire("deleted", a, mw, args...)
	return
}

func (a *OfficialCommonCategory) Count(mw func(db.Result) db.Result, args ...interface{}) (int64, error) {
	return a.Param(mw, args...).Count()
}

func (a *OfficialCommonCategory) Exists(mw func(db.Result) db.Result, args ...interface{}) (bool, error) {
	return a.Param(mw, args...).Exists()
}

func (a *OfficialCommonCategory) Reset() *OfficialCommonCategory {
	a.Id = 0
	a.ParentId = 0
	a.HasChild = ``
	a.Level = 0
	a.Name = ``
	a.Keywords = ``
	a.Description = ``
	a.Cover = ``
	a.Type = ``
	a.Sort = 0
	a.Template = ``
	a.Disabled = ``
	a.ShowOnMenu = ``
	a.Created = 0
	a.Updated = 0
	a.Slugify = ``
	return a
}

func (a *OfficialCommonCategory) AsMap(onlyFields ...string) param.Store {
	r := param.Store{}
	if len(onlyFields) == 0 {
		r["Id"] = a.Id
		r["ParentId"] = a.ParentId
		r["HasChild"] = a.HasChild
		r["Level"] = a.Level
		r["Name"] = a.Name
		r["Keywords"] = a.Keywords
		r["Description"] = a.Description
		r["Cover"] = a.Cover
		r["Type"] = a.Type
		r["Sort"] = a.Sort
		r["Template"] = a.Template
		r["Disabled"] = a.Disabled
		r["ShowOnMenu"] = a.ShowOnMenu
		r["Created"] = a.Created
		r["Updated"] = a.Updated
		r["Slugify"] = a.Slugify
		return r
	}
	for _, field := range onlyFields {
		switch field {
		case "Id":
			r["Id"] = a.Id
		case "ParentId":
			r["ParentId"] = a.ParentId
		case "HasChild":
			r["HasChild"] = a.HasChild
		case "Level":
			r["Level"] = a.Level
		case "Name":
			r["Name"] = a.Name
		case "Keywords":
			r["Keywords"] = a.Keywords
		case "Description":
			r["Description"] = a.Description
		case "Cover":
			r["Cover"] = a.Cover
		case "Type":
			r["Type"] = a.Type
		case "Sort":
			r["Sort"] = a.Sort
		case "Template":
			r["Template"] = a.Template
		case "Disabled":
			r["Disabled"] = a.Disabled
		case "ShowOnMenu":
			r["ShowOnMenu"] = a.ShowOnMenu
		case "Created":
			r["Created"] = a.Created
		case "Updated":
			r["Updated"] = a.Updated
		case "Slugify":
			r["Slugify"] = a.Slugify
		}
	}
	return r
}

func (a *OfficialCommonCategory) FromRow(row map[string]interface{}) {
	for key, value := range row {
		switch key {
		case "id":
			a.Id = param.AsUint(value)
		case "parent_id":
			a.ParentId = param.AsUint(value)
		case "has_child":
			a.HasChild = param.AsString(value)
		case "level":
			a.Level = param.AsUint(value)
		case "name":
			a.Name = param.AsString(value)
		case "keywords":
			a.Keywords = param.AsString(value)
		case "description":
			a.Description = param.AsString(value)
		case "cover":
			a.Cover = param.AsString(value)
		case "type":
			a.Type = param.AsString(value)
		case "sort":
			a.Sort = param.AsInt(value)
		case "template":
			a.Template = param.AsString(value)
		case "disabled":
			a.Disabled = param.AsString(value)
		case "show_on_menu":
			a.ShowOnMenu = param.AsString(value)
		case "created":
			a.Created = param.AsUint(value)
		case "updated":
			a.Updated = param.AsUint(value)
		case "slugify":
			a.Slugify = param.AsString(value)
		}
	}
}

func (a *OfficialCommonCategory) Set(key interface{}, value ...interface{}) {
	switch k := key.(type) {
	case map[string]interface{}:
		for kk, vv := range k {
			a.Set(kk, vv)
		}
	default:
		var (
			kk string
			vv interface{}
		)
		if k, y := key.(string); y {
			kk = k
		} else {
			kk = fmt.Sprint(key)
		}
		if len(value) > 0 {
			vv = value[0]
		}
		switch kk {
		case "Id":
			a.Id = param.AsUint(vv)
		case "ParentId":
			a.ParentId = param.AsUint(vv)
		case "HasChild":
			a.HasChild = param.AsString(vv)
		case "Level":
			a.Level = param.AsUint(vv)
		case "Name":
			a.Name = param.AsString(vv)
		case "Keywords":
			a.Keywords = param.AsString(vv)
		case "Description":
			a.Description = param.AsString(vv)
		case "Cover":
			a.Cover = param.AsString(vv)
		case "Type":
			a.Type = param.AsString(vv)
		case "Sort":
			a.Sort = param.AsInt(vv)
		case "Template":
			a.Template = param.AsString(vv)
		case "Disabled":
			a.Disabled = param.AsString(vv)
		case "ShowOnMenu":
			a.ShowOnMenu = param.AsString(vv)
		case "Created":
			a.Created = param.AsUint(vv)
		case "Updated":
			a.Updated = param.AsUint(vv)
		case "Slugify":
			a.Slugify = param.AsString(vv)
		}
	}
}

func (a *OfficialCommonCategory) AsRow(onlyFields ...string) param.Store {
	r := param.Store{}
	if len(onlyFields) == 0 {
		r["id"] = a.Id
		r["parent_id"] = a.ParentId
		r["has_child"] = a.HasChild
		r["level"] = a.Level
		r["name"] = a.Name
		r["keywords"] = a.Keywords
		r["description"] = a.Description
		r["cover"] = a.Cover
		r["type"] = a.Type
		r["sort"] = a.Sort
		r["template"] = a.Template
		r["disabled"] = a.Disabled
		r["show_on_menu"] = a.ShowOnMenu
		r["created"] = a.Created
		r["updated"] = a.Updated
		r["slugify"] = a.Slugify
		return r
	}
	for _, field := range onlyFields {
		switch field {
		case "id":
			r["id"] = a.Id
		case "parent_id":
			r["parent_id"] = a.ParentId
		case "has_child":
			r["has_child"] = a.HasChild
		case "level":
			r["level"] = a.Level
		case "name":
			r["name"] = a.Name
		case "keywords":
			r["keywords"] = a.Keywords
		case "description":
			r["description"] = a.Description
		case "cover":
			r["cover"] = a.Cover
		case "type":
			r["type"] = a.Type
		case "sort":
			r["sort"] = a.Sort
		case "template":
			r["template"] = a.Template
		case "disabled":
			r["disabled"] = a.Disabled
		case "show_on_menu":
			r["show_on_menu"] = a.ShowOnMenu
		case "created":
			r["created"] = a.Created
		case "updated":
			r["updated"] = a.Updated
		case "slugify":
			r["slugify"] = a.Slugify
		}
	}
	return r
}

func (a *OfficialCommonCategory) ListPage(cond *db.Compounds, sorts ...interface{}) error {
	_, err := pagination.NewLister(a, nil, func(r db.Result) db.Result {
		return r.OrderBy(sorts...)
	}, cond.And()).Paging(a.Context())
	return err
}

func (a *OfficialCommonCategory) ListPageAs(recv interface{}, cond *db.Compounds, sorts ...interface{}) error {
	_, err := pagination.NewLister(a, recv, func(r db.Result) db.Result {
		return r.OrderBy(sorts...)
	}, cond.And()).Paging(a.Context())
	return err
}

func (a *OfficialCommonCategory) BatchValidate(kvset map[string]interface{}) error {
	if kvset == nil {
		kvset = a.AsRow()
	}
	return DBI.Fields.BatchValidate(a.Short_(), kvset)
}

func (a *OfficialCommonCategory) Validate(field string, value interface{}) error {
	return DBI.Fields.Validate(a.Short_(), field, value)
}
