// @generated Do not edit this file, which is automatically generated by the generator.

package dbschema

import (
	"fmt"

	"time"

	"github.com/webx-top/com"
	"github.com/webx-top/db"
	"github.com/webx-top/db/lib/factory"
	"github.com/webx-top/db/lib/factory/pagination"
	"github.com/webx-top/echo"
	"github.com/webx-top/echo/param"
)

type Slice_OfficialAdPosition = factory.Slicex[*OfficialAdPosition]

func NewOfficialAdPosition(ctx echo.Context) *OfficialAdPosition {
	m := &OfficialAdPosition{}
	m.SetContext(ctx)
	return m
}

// OfficialAdPosition 广告位置
type OfficialAdPosition struct {
	base    factory.Base
	objects []*OfficialAdPosition

	Id       uint64 `db:"id,omitempty,pk" bson:"id,omitempty" comment:"ID" json:"id" xml:"id"`
	Ident    string `db:"ident" bson:"ident" comment:"唯一标识" json:"ident" xml:"ident"`
	Name     string `db:"name" bson:"name" comment:"位置名称" json:"name" xml:"name"`
	Width    uint   `db:"width" bson:"width" comment:"宽度" json:"width" xml:"width"`
	Height   uint   `db:"height" bson:"height" comment:"高度" json:"height" xml:"height"`
	Content  string `db:"content" bson:"content" comment:"默认内容" json:"content" xml:"content"`
	Contype  string `db:"contype" bson:"contype" comment:"内容类型" json:"contype" xml:"contype"`
	Url      string `db:"url" bson:"url" comment:"广告链接" json:"url" xml:"url"`
	Disabled string `db:"disabled" bson:"disabled" comment:"是否(Y/N)禁用" json:"disabled" xml:"disabled"`
	Created  uint   `db:"created" bson:"created" comment:"创建时间" json:"created" xml:"created" form_decoder:"time2unix" form_encoder:"unix2time"`
	Updated  uint   `db:"updated" bson:"updated" comment:"修改时间" json:"updated" xml:"updated" form_decoder:"time2unix" form_encoder:"unix2time"`
}

// - base function

func (a *OfficialAdPosition) Trans() factory.Transactioner {
	return a.base.Trans()
}

func (a *OfficialAdPosition) Use(trans factory.Transactioner) factory.Model {
	a.base.Use(trans)
	return a
}

func (a *OfficialAdPosition) SetContext(ctx echo.Context) factory.Model {
	a.base.SetContext(ctx)
	return a
}

func (a *OfficialAdPosition) EventON(on ...bool) factory.Model {
	a.base.EventON(on...)
	return a
}

func (a *OfficialAdPosition) EventOFF(off ...bool) factory.Model {
	a.base.EventOFF(off...)
	return a
}

func (a *OfficialAdPosition) Context() echo.Context {
	return a.base.Context()
}

func (a *OfficialAdPosition) SetConnID(connID int) factory.Model {
	a.base.SetConnID(connID)
	return a
}

func (a *OfficialAdPosition) ConnID() int {
	return a.base.ConnID()
}

func (a *OfficialAdPosition) SetNamer(namer func(factory.Model) string) factory.Model {
	a.base.SetNamer(namer)
	return a
}

func (a *OfficialAdPosition) Namer() func(factory.Model) string {
	return a.base.Namer()
}

func (a *OfficialAdPosition) SetParam(param *factory.Param) factory.Model {
	a.base.SetParam(param)
	return a
}

func (a *OfficialAdPosition) Param(mw func(db.Result) db.Result, args ...interface{}) *factory.Param {
	if a.base.Param() == nil {
		return a.NewParam().SetMiddleware(mw).SetArgs(args...)
	}
	return a.base.Param().SetMiddleware(mw).SetArgs(args...)
}

func (a *OfficialAdPosition) New(structName string, connID ...int) factory.Model {
	return a.base.New(structName, connID...)
}

func (a *OfficialAdPosition) Base_() factory.Baser {
	return &a.base
}

// - current function

func (a *OfficialAdPosition) Objects() []*OfficialAdPosition {
	if a.objects == nil {
		return nil
	}
	return a.objects[:]
}

func (a *OfficialAdPosition) XObjects() Slice_OfficialAdPosition {
	return Slice_OfficialAdPosition(a.Objects())
}

func (a *OfficialAdPosition) NewObjects() factory.Ranger {
	return &Slice_OfficialAdPosition{}
}

func (a *OfficialAdPosition) InitObjects() *[]*OfficialAdPosition {
	a.objects = []*OfficialAdPosition{}
	return &a.objects
}

func (a *OfficialAdPosition) NewParam() *factory.Param {
	return factory.NewParam(factory.DefaultFactory).SetIndex(a.base.ConnID()).SetTrans(a.base.Trans()).SetCollection(a.Name_()).SetModel(a)
}

func (a *OfficialAdPosition) Short_() string {
	return "official_ad_position"
}

func (a *OfficialAdPosition) Struct_() string {
	return "OfficialAdPosition"
}

func (a *OfficialAdPosition) Name_() string {
	b := a
	if b == nil {
		b = &OfficialAdPosition{}
	}
	if b.base.Namer() != nil {
		return WithPrefix(b.base.Namer()(b))
	}
	return WithPrefix(factory.TableNamerGet(b.Short_())(b))
}

// CPAFrom Deprecated: Use CtxFrom instead.
func (a *OfficialAdPosition) CPAFrom(source factory.Model) factory.Model {
	return a.CtxFrom(source)
}

func (a *OfficialAdPosition) CtxFrom(source factory.Model) factory.Model {
	a.base.CtxFrom(source)
	return a
}

func (a *OfficialAdPosition) Get(mw func(db.Result) db.Result, args ...interface{}) (err error) {
	base := a.base
	if !a.base.Eventable() {
		err = a.Param(mw, args...).SetRecv(a).One()
		a.base = base
		return
	}
	queryParam := a.Param(mw, args...).SetRecv(a)
	if err = a.base.FireReading(a, queryParam); err != nil {
		return
	}
	err = queryParam.One()
	a.base = base
	if err == nil {
		err = a.base.FireReaded(a, queryParam)
	}
	return
}

func (a *OfficialAdPosition) List(recv interface{}, mw func(db.Result) db.Result, page, size int, args ...interface{}) (func() int64, error) {
	if recv == nil {
		recv = a.InitObjects()
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetPage(page).SetSize(size).SetRecv(recv).List()
	}
	queryParam := a.Param(mw, args...).SetPage(page).SetSize(size).SetRecv(recv)
	if err := a.base.FireReading(a, queryParam); err != nil {
		return nil, err
	}
	cnt, err := queryParam.List()
	if err == nil {
		switch v := recv.(type) {
		case *[]*OfficialAdPosition:
			err = a.base.FireReaded(a, queryParam, Slice_OfficialAdPosition(*v))
		case []*OfficialAdPosition:
			err = a.base.FireReaded(a, queryParam, Slice_OfficialAdPosition(v))
		case factory.Ranger:
			err = a.base.FireReaded(a, queryParam, v)
		}
	}
	return cnt, err
}

func (a *OfficialAdPosition) GroupBy(keyField string, inputRows ...[]*OfficialAdPosition) map[string][]*OfficialAdPosition {
	var rows Slice_OfficialAdPosition
	if len(inputRows) > 0 {
		rows = Slice_OfficialAdPosition(inputRows[0])
	} else {
		rows = Slice_OfficialAdPosition(a.Objects())
	}
	return rows.GroupBy(keyField)
}

func (a *OfficialAdPosition) KeyBy(keyField string, inputRows ...[]*OfficialAdPosition) map[string]*OfficialAdPosition {
	var rows Slice_OfficialAdPosition
	if len(inputRows) > 0 {
		rows = Slice_OfficialAdPosition(inputRows[0])
	} else {
		rows = Slice_OfficialAdPosition(a.Objects())
	}
	return rows.KeyBy(keyField)
}

func (a *OfficialAdPosition) AsKV(keyField string, valueField string, inputRows ...[]*OfficialAdPosition) param.Store {
	var rows Slice_OfficialAdPosition
	if len(inputRows) > 0 {
		rows = Slice_OfficialAdPosition(inputRows[0])
	} else {
		rows = Slice_OfficialAdPosition(a.Objects())
	}
	return rows.AsKV(keyField, valueField)
}

func (a *OfficialAdPosition) ListByOffset(recv interface{}, mw func(db.Result) db.Result, offset, size int, args ...interface{}) (func() int64, error) {
	if recv == nil {
		recv = a.InitObjects()
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetOffset(offset).SetSize(size).SetRecv(recv).List()
	}
	queryParam := a.Param(mw, args...).SetOffset(offset).SetSize(size).SetRecv(recv)
	if err := a.base.FireReading(a, queryParam); err != nil {
		return nil, err
	}
	cnt, err := queryParam.List()
	if err == nil {
		switch v := recv.(type) {
		case *[]*OfficialAdPosition:
			err = a.base.FireReaded(a, queryParam, Slice_OfficialAdPosition(*v))
		case []*OfficialAdPosition:
			err = a.base.FireReaded(a, queryParam, Slice_OfficialAdPosition(v))
		case factory.Ranger:
			err = a.base.FireReaded(a, queryParam, v)
		}
	}
	return cnt, err
}

func (a *OfficialAdPosition) Insert() (pk interface{}, err error) {
	a.Created = uint(time.Now().Unix())
	a.Id = 0
	if len(a.Contype) == 0 {
		a.Contype = "image"
	}
	if len(a.Disabled) == 0 {
		a.Disabled = "N"
	}
	if a.base.Eventable() {
		err = a.base.Fire(factory.EventCreating, a, nil)
		if err != nil {
			return
		}
	}
	pk, err = a.Param(nil).SetSend(a).Insert()
	if err == nil && pk != nil {
		if v, y := pk.(uint64); y {
			a.Id = v
		} else if v, y := pk.(int64); y {
			a.Id = uint64(v)
		}
	}
	if err == nil && a.base.Eventable() {
		err = a.base.Fire(factory.EventCreated, a, nil)
	}
	return
}

func (a *OfficialAdPosition) Update(mw func(db.Result) db.Result, args ...interface{}) (err error) {
	a.Updated = uint(time.Now().Unix())
	if len(a.Contype) == 0 {
		a.Contype = "image"
	}
	if len(a.Disabled) == 0 {
		a.Disabled = "N"
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(a).Update()
	}
	if err = a.base.Fire(factory.EventUpdating, a, mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).SetSend(a).Update(); err != nil {
		return
	}
	return a.base.Fire(factory.EventUpdated, a, mw, args...)
}

func (a *OfficialAdPosition) Updatex(mw func(db.Result) db.Result, args ...interface{}) (affected int64, err error) {
	a.Updated = uint(time.Now().Unix())
	if len(a.Contype) == 0 {
		a.Contype = "image"
	}
	if len(a.Disabled) == 0 {
		a.Disabled = "N"
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(a).Updatex()
	}
	if err = a.base.Fire(factory.EventUpdating, a, mw, args...); err != nil {
		return
	}
	if affected, err = a.Param(mw, args...).SetSend(a).Updatex(); err != nil {
		return
	}
	err = a.base.Fire(factory.EventUpdated, a, mw, args...)
	return
}

func (a *OfficialAdPosition) UpdateByFields(mw func(db.Result) db.Result, fields []string, args ...interface{}) (err error) {
	a.Updated = uint(time.Now().Unix())
	if len(a.Contype) == 0 {
		a.Contype = "image"
	}
	if len(a.Disabled) == 0 {
		a.Disabled = "N"
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).UpdateByStruct(a, fields...)
	}
	editColumns := make([]string, len(fields))
	for index, field := range fields {
		editColumns[index] = com.SnakeCase(field)
	}
	if err = a.base.FireUpdate(factory.EventUpdating, a, editColumns, mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).UpdateByStruct(a, fields...); err != nil {
		return
	}
	err = a.base.FireUpdate(factory.EventUpdated, a, editColumns, mw, args...)
	return
}

func (a *OfficialAdPosition) UpdatexByFields(mw func(db.Result) db.Result, fields []string, args ...interface{}) (affected int64, err error) {
	a.Updated = uint(time.Now().Unix())
	if len(a.Contype) == 0 {
		a.Contype = "image"
	}
	if len(a.Disabled) == 0 {
		a.Disabled = "N"
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).UpdatexByStruct(a, fields...)
	}
	editColumns := make([]string, len(fields))
	for index, field := range fields {
		editColumns[index] = com.SnakeCase(field)
	}
	if err = a.base.FireUpdate(factory.EventUpdating, a, editColumns, mw, args...); err != nil {
		return
	}
	if affected, err = a.Param(mw, args...).UpdatexByStruct(a, fields...); err != nil {
		return
	}
	err = a.base.FireUpdate(factory.EventUpdated, a, editColumns, mw, args...)
	return
}

func (a *OfficialAdPosition) UpdateField(mw func(db.Result) db.Result, field string, value interface{}, args ...interface{}) (err error) {
	return a.UpdateFields(mw, map[string]interface{}{
		field: value,
	}, args...)
}

func (a *OfficialAdPosition) UpdatexField(mw func(db.Result) db.Result, field string, value interface{}, args ...interface{}) (affected int64, err error) {
	return a.UpdatexFields(mw, map[string]interface{}{
		field: value,
	}, args...)
}

func (a *OfficialAdPosition) UpdateFields(mw func(db.Result) db.Result, kvset map[string]interface{}, args ...interface{}) (err error) {

	if val, ok := kvset["contype"]; ok && val != nil {
		if v, ok := val.(string); ok && len(v) == 0 {
			kvset["contype"] = "image"
		}
	}
	if val, ok := kvset["disabled"]; ok && val != nil {
		if v, ok := val.(string); ok && len(v) == 0 {
			kvset["disabled"] = "N"
		}
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(kvset).Update()
	}
	m := *a
	m.FromRow(kvset)
	editColumns := make([]string, 0, len(kvset))
	for column := range kvset {
		editColumns = append(editColumns, column)
	}
	if err = a.base.FireUpdate(factory.EventUpdating, &m, editColumns, mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).SetSend(kvset).Update(); err != nil {
		return
	}
	return a.base.FireUpdate(factory.EventUpdated, &m, editColumns, mw, args...)
}

func (a *OfficialAdPosition) UpdatexFields(mw func(db.Result) db.Result, kvset map[string]interface{}, args ...interface{}) (affected int64, err error) {

	if val, ok := kvset["contype"]; ok && val != nil {
		if v, ok := val.(string); ok && len(v) == 0 {
			kvset["contype"] = "image"
		}
	}
	if val, ok := kvset["disabled"]; ok && val != nil {
		if v, ok := val.(string); ok && len(v) == 0 {
			kvset["disabled"] = "N"
		}
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(kvset).Updatex()
	}
	m := *a
	m.FromRow(kvset)
	editColumns := make([]string, 0, len(kvset))
	for column := range kvset {
		editColumns = append(editColumns, column)
	}
	if err = a.base.FireUpdate(factory.EventUpdating, &m, editColumns, mw, args...); err != nil {
		return
	}
	if affected, err = a.Param(mw, args...).SetSend(kvset).Updatex(); err != nil {
		return
	}
	err = a.base.FireUpdate(factory.EventUpdated, &m, editColumns, mw, args...)
	return
}

func (a *OfficialAdPosition) UpdateValues(mw func(db.Result) db.Result, keysValues *db.KeysValues, args ...interface{}) (err error) {
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(keysValues).Update()
	}
	m := *a
	m.FromRow(keysValues.Map())
	if err = a.base.FireUpdate(factory.EventUpdating, &m, keysValues.Keys(), mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).SetSend(keysValues).Update(); err != nil {
		return
	}
	return a.base.FireUpdate(factory.EventUpdated, &m, keysValues.Keys(), mw, args...)
}

func (a *OfficialAdPosition) Upsert(mw func(db.Result) db.Result, args ...interface{}) (pk interface{}, err error) {
	pk, err = a.Param(mw, args...).SetSend(a).Upsert(func() error {
		a.Updated = uint(time.Now().Unix())
		if len(a.Contype) == 0 {
			a.Contype = "image"
		}
		if len(a.Disabled) == 0 {
			a.Disabled = "N"
		}
		if !a.base.Eventable() {
			return nil
		}
		return a.base.Fire(factory.EventUpdating, a, mw, args...)
	}, func() error {
		a.Created = uint(time.Now().Unix())
		a.Id = 0
		if len(a.Contype) == 0 {
			a.Contype = "image"
		}
		if len(a.Disabled) == 0 {
			a.Disabled = "N"
		}
		if !a.base.Eventable() {
			return nil
		}
		return a.base.Fire(factory.EventCreating, a, nil)
	})
	if err == nil && pk != nil {
		if v, y := pk.(uint64); y {
			a.Id = v
		} else if v, y := pk.(int64); y {
			a.Id = uint64(v)
		}
	}
	if err == nil && a.base.Eventable() {
		if pk == nil {
			err = a.base.Fire(factory.EventUpdated, a, mw, args...)
		} else {
			err = a.base.Fire(factory.EventCreated, a, nil)
		}
	}
	return
}

func (a *OfficialAdPosition) Delete(mw func(db.Result) db.Result, args ...interface{}) (err error) {

	if !a.base.Eventable() {
		return a.Param(mw, args...).Delete()
	}
	if err = a.base.Fire(factory.EventDeleting, a, mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).Delete(); err != nil {
		return
	}
	return a.base.Fire(factory.EventDeleted, a, mw, args...)
}

func (a *OfficialAdPosition) Deletex(mw func(db.Result) db.Result, args ...interface{}) (affected int64, err error) {

	if !a.base.Eventable() {
		return a.Param(mw, args...).Deletex()
	}
	if err = a.base.Fire(factory.EventDeleting, a, mw, args...); err != nil {
		return
	}
	if affected, err = a.Param(mw, args...).Deletex(); err != nil {
		return
	}
	err = a.base.Fire(factory.EventDeleted, a, mw, args...)
	return
}

func (a *OfficialAdPosition) Count(mw func(db.Result) db.Result, args ...interface{}) (int64, error) {
	return a.Param(mw, args...).Count()
}

func (a *OfficialAdPosition) Exists(mw func(db.Result) db.Result, args ...interface{}) (bool, error) {
	return a.Param(mw, args...).Exists()
}

func (a *OfficialAdPosition) Reset() *OfficialAdPosition {
	a.Id = 0
	a.Ident = ``
	a.Name = ``
	a.Width = 0
	a.Height = 0
	a.Content = ``
	a.Contype = ``
	a.Url = ``
	a.Disabled = ``
	a.Created = 0
	a.Updated = 0
	return a
}

func (a *OfficialAdPosition) AsMap(onlyFields ...string) param.Store {
	r := param.Store{}
	if len(onlyFields) == 0 {
		r["Id"] = a.Id
		r["Ident"] = a.Ident
		r["Name"] = a.Name
		r["Width"] = a.Width
		r["Height"] = a.Height
		r["Content"] = a.Content
		r["Contype"] = a.Contype
		r["Url"] = a.Url
		r["Disabled"] = a.Disabled
		r["Created"] = a.Created
		r["Updated"] = a.Updated
		return r
	}
	for _, field := range onlyFields {
		switch field {
		case "Id":
			r["Id"] = a.Id
		case "Ident":
			r["Ident"] = a.Ident
		case "Name":
			r["Name"] = a.Name
		case "Width":
			r["Width"] = a.Width
		case "Height":
			r["Height"] = a.Height
		case "Content":
			r["Content"] = a.Content
		case "Contype":
			r["Contype"] = a.Contype
		case "Url":
			r["Url"] = a.Url
		case "Disabled":
			r["Disabled"] = a.Disabled
		case "Created":
			r["Created"] = a.Created
		case "Updated":
			r["Updated"] = a.Updated
		}
	}
	return r
}

func (a *OfficialAdPosition) Clone() *OfficialAdPosition {
	cloned := OfficialAdPosition{Id: a.Id, Ident: a.Ident, Name: a.Name, Width: a.Width, Height: a.Height, Content: a.Content, Contype: a.Contype, Url: a.Url, Disabled: a.Disabled, Created: a.Created, Updated: a.Updated}
	cloned.CtxFrom(a)
	return &cloned
}

func (a *OfficialAdPosition) FromRow(row map[string]interface{}) {
	for key, value := range row {
		if _, ok := value.(db.RawValue); ok {
			continue
		}
		switch key {
		case "id":
			a.Id = param.AsUint64(value)
		case "ident":
			a.Ident = param.AsString(value)
		case "name":
			a.Name = param.AsString(value)
		case "width":
			a.Width = param.AsUint(value)
		case "height":
			a.Height = param.AsUint(value)
		case "content":
			a.Content = param.AsString(value)
		case "contype":
			a.Contype = param.AsString(value)
		case "url":
			a.Url = param.AsString(value)
		case "disabled":
			a.Disabled = param.AsString(value)
		case "created":
			a.Created = param.AsUint(value)
		case "updated":
			a.Updated = param.AsUint(value)
		}
	}
}

func (a *OfficialAdPosition) GetField(field string) interface{} {
	switch field {
	case "Id":
		return a.Id
	case "Ident":
		return a.Ident
	case "Name":
		return a.Name
	case "Width":
		return a.Width
	case "Height":
		return a.Height
	case "Content":
		return a.Content
	case "Contype":
		return a.Contype
	case "Url":
		return a.Url
	case "Disabled":
		return a.Disabled
	case "Created":
		return a.Created
	case "Updated":
		return a.Updated
	default:
		return nil
	}
}

func (a *OfficialAdPosition) GetAllFieldNames() []string {
	return []string{
		"Id",
		"Ident",
		"Name",
		"Width",
		"Height",
		"Content",
		"Contype",
		"Url",
		"Disabled",
		"Created",
		"Updated",
	}
}

func (a *OfficialAdPosition) HasField(field string) bool {
	switch field {
	case "Id":
		return true
	case "Ident":
		return true
	case "Name":
		return true
	case "Width":
		return true
	case "Height":
		return true
	case "Content":
		return true
	case "Contype":
		return true
	case "Url":
		return true
	case "Disabled":
		return true
	case "Created":
		return true
	case "Updated":
		return true
	default:
		return false
	}
}

func (a *OfficialAdPosition) Set(key interface{}, value ...interface{}) {
	switch k := key.(type) {
	case map[string]interface{}:
		for kk, vv := range k {
			a.Set(kk, vv)
		}
	default:
		var (
			kk string
			vv interface{}
		)
		if k, y := key.(string); y {
			kk = k
		} else {
			kk = fmt.Sprint(key)
		}
		if len(value) > 0 {
			vv = value[0]
		}
		switch kk {
		case "Id":
			a.Id = param.AsUint64(vv)
		case "Ident":
			a.Ident = param.AsString(vv)
		case "Name":
			a.Name = param.AsString(vv)
		case "Width":
			a.Width = param.AsUint(vv)
		case "Height":
			a.Height = param.AsUint(vv)
		case "Content":
			a.Content = param.AsString(vv)
		case "Contype":
			a.Contype = param.AsString(vv)
		case "Url":
			a.Url = param.AsString(vv)
		case "Disabled":
			a.Disabled = param.AsString(vv)
		case "Created":
			a.Created = param.AsUint(vv)
		case "Updated":
			a.Updated = param.AsUint(vv)
		}
	}
}

func (a *OfficialAdPosition) AsRow(onlyFields ...string) param.Store {
	r := param.Store{}
	if len(onlyFields) == 0 {
		r["id"] = a.Id
		r["ident"] = a.Ident
		r["name"] = a.Name
		r["width"] = a.Width
		r["height"] = a.Height
		r["content"] = a.Content
		r["contype"] = a.Contype
		r["url"] = a.Url
		r["disabled"] = a.Disabled
		r["created"] = a.Created
		r["updated"] = a.Updated
		return r
	}
	for _, field := range onlyFields {
		switch field {
		case "id":
			r["id"] = a.Id
		case "ident":
			r["ident"] = a.Ident
		case "name":
			r["name"] = a.Name
		case "width":
			r["width"] = a.Width
		case "height":
			r["height"] = a.Height
		case "content":
			r["content"] = a.Content
		case "contype":
			r["contype"] = a.Contype
		case "url":
			r["url"] = a.Url
		case "disabled":
			r["disabled"] = a.Disabled
		case "created":
			r["created"] = a.Created
		case "updated":
			r["updated"] = a.Updated
		}
	}
	return r
}

func (a *OfficialAdPosition) ListPage(cond *db.Compounds, sorts ...interface{}) error {
	return pagination.ListPage(a, cond, sorts...)
}

func (a *OfficialAdPosition) ListPageAs(recv interface{}, cond *db.Compounds, sorts ...interface{}) error {
	return pagination.ListPageAs(a, recv, cond, sorts...)
}

func (a *OfficialAdPosition) ListPageByOffset(cond *db.Compounds, sorts ...interface{}) error {
	return pagination.ListPageByOffset(a, cond, sorts...)
}

func (a *OfficialAdPosition) ListPageByOffsetAs(recv interface{}, cond *db.Compounds, sorts ...interface{}) error {
	return pagination.ListPageByOffsetAs(a, recv, cond, sorts...)
}

func (a *OfficialAdPosition) BatchValidate(kvset map[string]interface{}) error {
	return a.base.BatchValidate(a, kvset)
}

func (a *OfficialAdPosition) Validate(column string, value interface{}) error {
	return a.base.Validate(a, column, value)
}

func (a *OfficialAdPosition) TrimOverflowText(column string, value string) string {
	return a.base.TrimOverflowText(a, column, value)
}
