// @generated Do not edit this file, which is automatically generated by the generator.

package dbschema

import (
	"fmt"

	"time"

	"github.com/webx-top/com"
	"github.com/webx-top/db"
	"github.com/webx-top/db/lib/factory"
	"github.com/webx-top/db/lib/factory/pagination"
	"github.com/webx-top/echo"
	"github.com/webx-top/echo/param"
)

type Slice_OfficialCustomerDevice []*OfficialCustomerDevice

func (s Slice_OfficialCustomerDevice) Range(fn func(m factory.Model) error) error {
	for _, v := range s {
		if err := fn(v); err != nil {
			return err
		}
	}
	return nil
}

func (s Slice_OfficialCustomerDevice) RangeRaw(fn func(m *OfficialCustomerDevice) error) error {
	for _, v := range s {
		if err := fn(v); err != nil {
			return err
		}
	}
	return nil
}

func (s Slice_OfficialCustomerDevice) GroupBy(keyField string) map[string][]*OfficialCustomerDevice {
	r := map[string][]*OfficialCustomerDevice{}
	for _, row := range s {
		dmap := row.AsMap()
		vkey := fmt.Sprint(dmap[keyField])
		if _, y := r[vkey]; !y {
			r[vkey] = []*OfficialCustomerDevice{}
		}
		r[vkey] = append(r[vkey], row)
	}
	return r
}

func (s Slice_OfficialCustomerDevice) KeyBy(keyField string) map[string]*OfficialCustomerDevice {
	r := map[string]*OfficialCustomerDevice{}
	for _, row := range s {
		dmap := row.AsMap()
		vkey := fmt.Sprint(dmap[keyField])
		r[vkey] = row
	}
	return r
}

func (s Slice_OfficialCustomerDevice) AsKV(keyField string, valueField string) param.Store {
	r := param.Store{}
	for _, row := range s {
		dmap := row.AsMap()
		vkey := fmt.Sprint(dmap[keyField])
		r[vkey] = dmap[valueField]
	}
	return r
}

func (s Slice_OfficialCustomerDevice) Transform(transfers map[string]param.Transfer) []param.Store {
	r := make([]param.Store, len(s))
	for idx, row := range s {
		r[idx] = row.AsMap().Transform(transfers)
	}
	return r
}

func (s Slice_OfficialCustomerDevice) FromList(data interface{}) Slice_OfficialCustomerDevice {
	values, ok := data.([]*OfficialCustomerDevice)
	if !ok {
		for _, value := range data.([]interface{}) {
			row := &OfficialCustomerDevice{}
			row.FromRow(value.(map[string]interface{}))
			s = append(s, row)
		}
		return s
	}
	s = append(s, values...)

	return s
}

func NewOfficialCustomerDevice(ctx echo.Context) *OfficialCustomerDevice {
	m := &OfficialCustomerDevice{}
	m.SetContext(ctx)
	return m
}

// OfficialCustomerDevice 客户登录设备
type OfficialCustomerDevice struct {
	base    factory.Base
	objects []*OfficialCustomerDevice

	Id         uint64 `db:"id,omitempty,pk" bson:"id,omitempty" comment:"ID" json:"id" xml:"id"`
	CustomerId uint64 `db:"customer_id" bson:"customer_id" comment:"客户ID" json:"customer_id" xml:"customer_id"`
	SessionId  string `db:"session_id" bson:"session_id" comment:"session id" json:"session_id" xml:"session_id"`
	Scense     string `db:"scense" bson:"scense" comment:"场景标识" json:"scense" xml:"scense"`
	Platform   string `db:"platform" bson:"platform" comment:"系统平台" json:"platform" xml:"platform"`
	DeviceNo   string `db:"device_no" bson:"device_no" comment:"设备编号" json:"device_no" xml:"device_no"`
	Created    uint   `db:"created" bson:"created" comment:"登录时间" json:"created" xml:"created"`
	Updated    uint   `db:"updated" bson:"updated" comment:"更新时间" json:"updated" xml:"updated"`
	Expired    uint   `db:"expired" bson:"expired" comment:"过期时间" json:"expired" xml:"expired"`
}

// - base function

func (a *OfficialCustomerDevice) Trans() factory.Transactioner {
	return a.base.Trans()
}

func (a *OfficialCustomerDevice) Use(trans factory.Transactioner) factory.Model {
	a.base.Use(trans)
	return a
}

func (a *OfficialCustomerDevice) SetContext(ctx echo.Context) factory.Model {
	a.base.SetContext(ctx)
	return a
}

func (a *OfficialCustomerDevice) EventON(on ...bool) factory.Model {
	a.base.EventON(on...)
	return a
}

func (a *OfficialCustomerDevice) EventOFF(off ...bool) factory.Model {
	a.base.EventOFF(off...)
	return a
}

func (a *OfficialCustomerDevice) Context() echo.Context {
	return a.base.Context()
}

func (a *OfficialCustomerDevice) SetConnID(connID int) factory.Model {
	a.base.SetConnID(connID)
	return a
}

func (a *OfficialCustomerDevice) ConnID() int {
	return a.base.ConnID()
}

func (a *OfficialCustomerDevice) SetNamer(namer func(factory.Model) string) factory.Model {
	a.base.SetNamer(namer)
	return a
}

func (a *OfficialCustomerDevice) Namer() func(factory.Model) string {
	return a.base.Namer()
}

func (a *OfficialCustomerDevice) SetParam(param *factory.Param) factory.Model {
	a.base.SetParam(param)
	return a
}

func (a *OfficialCustomerDevice) Param(mw func(db.Result) db.Result, args ...interface{}) *factory.Param {
	if a.base.Param() == nil {
		return a.NewParam().SetMiddleware(mw).SetArgs(args...)
	}
	return a.base.Param().SetMiddleware(mw).SetArgs(args...)
}

func (a *OfficialCustomerDevice) New(structName string, connID ...int) factory.Model {
	return a.base.New(structName, connID...)
}

func (a *OfficialCustomerDevice) Base_() factory.Baser {
	return &a.base
}

// - current function

func (a *OfficialCustomerDevice) Objects() []*OfficialCustomerDevice {
	if a.objects == nil {
		return nil
	}
	return a.objects[:]
}

func (a *OfficialCustomerDevice) XObjects() Slice_OfficialCustomerDevice {
	return Slice_OfficialCustomerDevice(a.Objects())
}

func (a *OfficialCustomerDevice) NewObjects() factory.Ranger {
	return &Slice_OfficialCustomerDevice{}
}

func (a *OfficialCustomerDevice) InitObjects() *[]*OfficialCustomerDevice {
	a.objects = []*OfficialCustomerDevice{}
	return &a.objects
}

func (a *OfficialCustomerDevice) NewParam() *factory.Param {
	return factory.NewParam(factory.DefaultFactory).SetIndex(a.base.ConnID()).SetTrans(a.base.Trans()).SetCollection(a.Name_()).SetModel(a)
}

func (a *OfficialCustomerDevice) Short_() string {
	return "official_customer_device"
}

func (a *OfficialCustomerDevice) Struct_() string {
	return "OfficialCustomerDevice"
}

func (a *OfficialCustomerDevice) Name_() string {
	b := a
	if b == nil {
		b = &OfficialCustomerDevice{}
	}
	if b.base.Namer() != nil {
		return WithPrefix(b.base.Namer()(b))
	}
	return WithPrefix(factory.TableNamerGet(b.Short_())(b))
}

func (a *OfficialCustomerDevice) CPAFrom(source factory.Model) factory.Model {
	a.SetContext(source.Context())
	a.SetConnID(source.ConnID())
	a.SetNamer(source.Namer())
	return a
}

func (a *OfficialCustomerDevice) Get(mw func(db.Result) db.Result, args ...interface{}) (err error) {
	base := a.base
	if !a.base.Eventable() {
		err = a.Param(mw, args...).SetRecv(a).One()
		a.base = base
		return
	}
	queryParam := a.Param(mw, args...).SetRecv(a)
	if err = DBI.FireReading(a, queryParam); err != nil {
		return
	}
	err = queryParam.One()
	a.base = base
	if err == nil {
		err = DBI.FireReaded(a, queryParam)
	}
	return
}

func (a *OfficialCustomerDevice) List(recv interface{}, mw func(db.Result) db.Result, page, size int, args ...interface{}) (func() int64, error) {
	if recv == nil {
		recv = a.InitObjects()
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetPage(page).SetSize(size).SetRecv(recv).List()
	}
	queryParam := a.Param(mw, args...).SetPage(page).SetSize(size).SetRecv(recv)
	if err := DBI.FireReading(a, queryParam); err != nil {
		return nil, err
	}
	cnt, err := queryParam.List()
	if err == nil {
		switch v := recv.(type) {
		case *[]*OfficialCustomerDevice:
			err = DBI.FireReaded(a, queryParam, Slice_OfficialCustomerDevice(*v))
		case []*OfficialCustomerDevice:
			err = DBI.FireReaded(a, queryParam, Slice_OfficialCustomerDevice(v))
		case factory.Ranger:
			err = DBI.FireReaded(a, queryParam, v)
		}
	}
	return cnt, err
}

func (a *OfficialCustomerDevice) GroupBy(keyField string, inputRows ...[]*OfficialCustomerDevice) map[string][]*OfficialCustomerDevice {
	var rows Slice_OfficialCustomerDevice
	if len(inputRows) > 0 {
		rows = Slice_OfficialCustomerDevice(inputRows[0])
	} else {
		rows = Slice_OfficialCustomerDevice(a.Objects())
	}
	return rows.GroupBy(keyField)
}

func (a *OfficialCustomerDevice) KeyBy(keyField string, inputRows ...[]*OfficialCustomerDevice) map[string]*OfficialCustomerDevice {
	var rows Slice_OfficialCustomerDevice
	if len(inputRows) > 0 {
		rows = Slice_OfficialCustomerDevice(inputRows[0])
	} else {
		rows = Slice_OfficialCustomerDevice(a.Objects())
	}
	return rows.KeyBy(keyField)
}

func (a *OfficialCustomerDevice) AsKV(keyField string, valueField string, inputRows ...[]*OfficialCustomerDevice) param.Store {
	var rows Slice_OfficialCustomerDevice
	if len(inputRows) > 0 {
		rows = Slice_OfficialCustomerDevice(inputRows[0])
	} else {
		rows = Slice_OfficialCustomerDevice(a.Objects())
	}
	return rows.AsKV(keyField, valueField)
}

func (a *OfficialCustomerDevice) ListByOffset(recv interface{}, mw func(db.Result) db.Result, offset, size int, args ...interface{}) (func() int64, error) {
	if recv == nil {
		recv = a.InitObjects()
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetOffset(offset).SetSize(size).SetRecv(recv).List()
	}
	queryParam := a.Param(mw, args...).SetOffset(offset).SetSize(size).SetRecv(recv)
	if err := DBI.FireReading(a, queryParam); err != nil {
		return nil, err
	}
	cnt, err := queryParam.List()
	if err == nil {
		switch v := recv.(type) {
		case *[]*OfficialCustomerDevice:
			err = DBI.FireReaded(a, queryParam, Slice_OfficialCustomerDevice(*v))
		case []*OfficialCustomerDevice:
			err = DBI.FireReaded(a, queryParam, Slice_OfficialCustomerDevice(v))
		case factory.Ranger:
			err = DBI.FireReaded(a, queryParam, v)
		}
	}
	return cnt, err
}

func (a *OfficialCustomerDevice) Insert() (pk interface{}, err error) {
	a.Created = uint(time.Now().Unix())
	a.Id = 0
	if a.base.Eventable() {
		err = DBI.Fire("creating", a, nil)
		if err != nil {
			return
		}
	}
	pk, err = a.Param(nil).SetSend(a).Insert()
	if err == nil && pk != nil {
		if v, y := pk.(uint64); y {
			a.Id = v
		} else if v, y := pk.(int64); y {
			a.Id = uint64(v)
		}
	}
	if err == nil && a.base.Eventable() {
		err = DBI.Fire("created", a, nil)
	}
	return
}

func (a *OfficialCustomerDevice) Update(mw func(db.Result) db.Result, args ...interface{}) (err error) {
	a.Updated = uint(time.Now().Unix())
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(a).Update()
	}
	if err = DBI.Fire("updating", a, mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).SetSend(a).Update(); err != nil {
		return
	}
	return DBI.Fire("updated", a, mw, args...)
}

func (a *OfficialCustomerDevice) Updatex(mw func(db.Result) db.Result, args ...interface{}) (affected int64, err error) {
	a.Updated = uint(time.Now().Unix())
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(a).Updatex()
	}
	if err = DBI.Fire("updating", a, mw, args...); err != nil {
		return
	}
	if affected, err = a.Param(mw, args...).SetSend(a).Updatex(); err != nil {
		return
	}
	err = DBI.Fire("updated", a, mw, args...)
	return
}

func (a *OfficialCustomerDevice) UpdateByFields(mw func(db.Result) db.Result, fields []string, args ...interface{}) (err error) {
	a.Updated = uint(time.Now().Unix())
	if !a.base.Eventable() {
		return a.Param(mw, args...).UpdateByStruct(a, fields...)
	}
	editColumns := make([]string, len(fields))
	for index, field := range fields {
		editColumns[index] = com.SnakeCase(field)
	}
	if err = DBI.FireUpdate("updating", a, editColumns, mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).UpdateByStruct(a, fields...); err != nil {
		return
	}
	err = DBI.FireUpdate("updated", a, editColumns, mw, args...)
	return
}

func (a *OfficialCustomerDevice) UpdatexByFields(mw func(db.Result) db.Result, fields []string, args ...interface{}) (affected int64, err error) {
	a.Updated = uint(time.Now().Unix())
	if !a.base.Eventable() {
		return a.Param(mw, args...).UpdatexByStruct(a, fields...)
	}
	editColumns := make([]string, len(fields))
	for index, field := range fields {
		editColumns[index] = com.SnakeCase(field)
	}
	if err = DBI.FireUpdate("updating", a, editColumns, mw, args...); err != nil {
		return
	}
	if affected, err = a.Param(mw, args...).UpdatexByStruct(a, fields...); err != nil {
		return
	}
	err = DBI.FireUpdate("updated", a, editColumns, mw, args...)
	return
}

func (a *OfficialCustomerDevice) UpdateField(mw func(db.Result) db.Result, field string, value interface{}, args ...interface{}) (err error) {
	return a.UpdateFields(mw, map[string]interface{}{
		field: value,
	}, args...)
}

func (a *OfficialCustomerDevice) UpdatexField(mw func(db.Result) db.Result, field string, value interface{}, args ...interface{}) (affected int64, err error) {
	return a.UpdatexFields(mw, map[string]interface{}{
		field: value,
	}, args...)
}

func (a *OfficialCustomerDevice) UpdateFields(mw func(db.Result) db.Result, kvset map[string]interface{}, args ...interface{}) (err error) {
	kvset["updated"] = uint(time.Now().Unix())
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(kvset).Update()
	}
	m := *a
	m.FromRow(kvset)
	var editColumns []string
	for column := range kvset {
		editColumns = append(editColumns, column)
	}
	if err = DBI.FireUpdate("updating", &m, editColumns, mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).SetSend(kvset).Update(); err != nil {
		return
	}
	return DBI.FireUpdate("updated", &m, editColumns, mw, args...)
}

func (a *OfficialCustomerDevice) UpdatexFields(mw func(db.Result) db.Result, kvset map[string]interface{}, args ...interface{}) (affected int64, err error) {
	kvset["updated"] = uint(time.Now().Unix())
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(kvset).Updatex()
	}
	m := *a
	m.FromRow(kvset)
	var editColumns []string
	for column := range kvset {
		editColumns = append(editColumns, column)
	}
	if err = DBI.FireUpdate("updating", &m, editColumns, mw, args...); err != nil {
		return
	}
	if affected, err = a.Param(mw, args...).SetSend(kvset).Updatex(); err != nil {
		return
	}
	err = DBI.FireUpdate("updated", &m, editColumns, mw, args...)
	return
}

func (a *OfficialCustomerDevice) UpdateValues(mw func(db.Result) db.Result, keysValues *db.KeysValues, args ...interface{}) (err error) {
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(keysValues).Update()
	}
	m := *a
	m.FromRow(keysValues.Map())
	if err = DBI.FireUpdate("updating", &m, keysValues.Keys(), mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).SetSend(keysValues).Update(); err != nil {
		return
	}
	return DBI.FireUpdate("updated", &m, keysValues.Keys(), mw, args...)
}

func (a *OfficialCustomerDevice) Upsert(mw func(db.Result) db.Result, args ...interface{}) (pk interface{}, err error) {
	pk, err = a.Param(mw, args...).SetSend(a).Upsert(func() error {
		a.Updated = uint(time.Now().Unix())
		if !a.base.Eventable() {
			return nil
		}
		return DBI.Fire("updating", a, mw, args...)
	}, func() error {
		a.Created = uint(time.Now().Unix())
		a.Id = 0
		if !a.base.Eventable() {
			return nil
		}
		return DBI.Fire("creating", a, nil)
	})
	if err == nil && pk != nil {
		if v, y := pk.(uint64); y {
			a.Id = v
		} else if v, y := pk.(int64); y {
			a.Id = uint64(v)
		}
	}
	if err == nil && a.base.Eventable() {
		if pk == nil {
			err = DBI.Fire("updated", a, mw, args...)
		} else {
			err = DBI.Fire("created", a, nil)
		}
	}
	return
}

func (a *OfficialCustomerDevice) Delete(mw func(db.Result) db.Result, args ...interface{}) (err error) {

	if !a.base.Eventable() {
		return a.Param(mw, args...).Delete()
	}
	if err = DBI.Fire("deleting", a, mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).Delete(); err != nil {
		return
	}
	return DBI.Fire("deleted", a, mw, args...)
}

func (a *OfficialCustomerDevice) Deletex(mw func(db.Result) db.Result, args ...interface{}) (affected int64, err error) {

	if !a.base.Eventable() {
		return a.Param(mw, args...).Deletex()
	}
	if err = DBI.Fire("deleting", a, mw, args...); err != nil {
		return
	}
	if affected, err = a.Param(mw, args...).Deletex(); err != nil {
		return
	}
	err = DBI.Fire("deleted", a, mw, args...)
	return
}

func (a *OfficialCustomerDevice) Count(mw func(db.Result) db.Result, args ...interface{}) (int64, error) {
	return a.Param(mw, args...).Count()
}

func (a *OfficialCustomerDevice) Exists(mw func(db.Result) db.Result, args ...interface{}) (bool, error) {
	return a.Param(mw, args...).Exists()
}

func (a *OfficialCustomerDevice) Reset() *OfficialCustomerDevice {
	a.Id = 0
	a.CustomerId = 0
	a.SessionId = ``
	a.Scense = ``
	a.Platform = ``
	a.DeviceNo = ``
	a.Created = 0
	a.Updated = 0
	a.Expired = 0
	return a
}

func (a *OfficialCustomerDevice) AsMap(onlyFields ...string) param.Store {
	r := param.Store{}
	if len(onlyFields) == 0 {
		r["Id"] = a.Id
		r["CustomerId"] = a.CustomerId
		r["SessionId"] = a.SessionId
		r["Scense"] = a.Scense
		r["Platform"] = a.Platform
		r["DeviceNo"] = a.DeviceNo
		r["Created"] = a.Created
		r["Updated"] = a.Updated
		r["Expired"] = a.Expired
		return r
	}
	for _, field := range onlyFields {
		switch field {
		case "Id":
			r["Id"] = a.Id
		case "CustomerId":
			r["CustomerId"] = a.CustomerId
		case "SessionId":
			r["SessionId"] = a.SessionId
		case "Scense":
			r["Scense"] = a.Scense
		case "Platform":
			r["Platform"] = a.Platform
		case "DeviceNo":
			r["DeviceNo"] = a.DeviceNo
		case "Created":
			r["Created"] = a.Created
		case "Updated":
			r["Updated"] = a.Updated
		case "Expired":
			r["Expired"] = a.Expired
		}
	}
	return r
}

func (a *OfficialCustomerDevice) FromRow(row map[string]interface{}) {
	for key, value := range row {
		switch key {
		case "id":
			a.Id = param.AsUint64(value)
		case "customer_id":
			a.CustomerId = param.AsUint64(value)
		case "session_id":
			a.SessionId = param.AsString(value)
		case "scense":
			a.Scense = param.AsString(value)
		case "platform":
			a.Platform = param.AsString(value)
		case "device_no":
			a.DeviceNo = param.AsString(value)
		case "created":
			a.Created = param.AsUint(value)
		case "updated":
			a.Updated = param.AsUint(value)
		case "expired":
			a.Expired = param.AsUint(value)
		}
	}
}

func (a *OfficialCustomerDevice) Set(key interface{}, value ...interface{}) {
	switch k := key.(type) {
	case map[string]interface{}:
		for kk, vv := range k {
			a.Set(kk, vv)
		}
	default:
		var (
			kk string
			vv interface{}
		)
		if k, y := key.(string); y {
			kk = k
		} else {
			kk = fmt.Sprint(key)
		}
		if len(value) > 0 {
			vv = value[0]
		}
		switch kk {
		case "Id":
			a.Id = param.AsUint64(vv)
		case "CustomerId":
			a.CustomerId = param.AsUint64(vv)
		case "SessionId":
			a.SessionId = param.AsString(vv)
		case "Scense":
			a.Scense = param.AsString(vv)
		case "Platform":
			a.Platform = param.AsString(vv)
		case "DeviceNo":
			a.DeviceNo = param.AsString(vv)
		case "Created":
			a.Created = param.AsUint(vv)
		case "Updated":
			a.Updated = param.AsUint(vv)
		case "Expired":
			a.Expired = param.AsUint(vv)
		}
	}
}

func (a *OfficialCustomerDevice) AsRow(onlyFields ...string) param.Store {
	r := param.Store{}
	if len(onlyFields) == 0 {
		r["id"] = a.Id
		r["customer_id"] = a.CustomerId
		r["session_id"] = a.SessionId
		r["scense"] = a.Scense
		r["platform"] = a.Platform
		r["device_no"] = a.DeviceNo
		r["created"] = a.Created
		r["updated"] = a.Updated
		r["expired"] = a.Expired
		return r
	}
	for _, field := range onlyFields {
		switch field {
		case "id":
			r["id"] = a.Id
		case "customer_id":
			r["customer_id"] = a.CustomerId
		case "session_id":
			r["session_id"] = a.SessionId
		case "scense":
			r["scense"] = a.Scense
		case "platform":
			r["platform"] = a.Platform
		case "device_no":
			r["device_no"] = a.DeviceNo
		case "created":
			r["created"] = a.Created
		case "updated":
			r["updated"] = a.Updated
		case "expired":
			r["expired"] = a.Expired
		}
	}
	return r
}

func (a *OfficialCustomerDevice) ListPage(cond *db.Compounds, sorts ...interface{}) error {
	_, err := pagination.NewLister(a, nil, func(r db.Result) db.Result {
		return r.OrderBy(sorts...)
	}, cond.And()).Paging(a.Context())
	return err
}

func (a *OfficialCustomerDevice) ListPageAs(recv interface{}, cond *db.Compounds, sorts ...interface{}) error {
	_, err := pagination.NewLister(a, recv, func(r db.Result) db.Result {
		return r.OrderBy(sorts...)
	}, cond.And()).Paging(a.Context())
	return err
}

func (a *OfficialCustomerDevice) BatchValidate(kvset map[string]interface{}) error {
	if kvset == nil {
		kvset = a.AsRow()
	}
	return DBI.Fields.BatchValidate(a.Short_(), kvset)
}

func (a *OfficialCustomerDevice) Validate(field string, value interface{}) error {
	return DBI.Fields.Validate(a.Short_(), field, value)
}
