// @generated Do not edit this file, which is automatically generated by the generator.

package dbschema

import (
	"fmt"

	"github.com/webx-top/com"
	"github.com/webx-top/db"
	"github.com/webx-top/db/lib/factory"
	"github.com/webx-top/db/lib/factory/pagination"
	"github.com/webx-top/echo"
	"github.com/webx-top/echo/param"
)

type Slice_OfficialCustomerRolePermission []*OfficialCustomerRolePermission

func (s Slice_OfficialCustomerRolePermission) Range(fn func(m factory.Model) error) error {
	for _, v := range s {
		if err := fn(v); err != nil {
			return err
		}
	}
	return nil
}

func (s Slice_OfficialCustomerRolePermission) RangeRaw(fn func(m *OfficialCustomerRolePermission) error) error {
	for _, v := range s {
		if err := fn(v); err != nil {
			return err
		}
	}
	return nil
}

func (s Slice_OfficialCustomerRolePermission) GroupBy(keyField string) map[string][]*OfficialCustomerRolePermission {
	r := map[string][]*OfficialCustomerRolePermission{}
	for _, row := range s {
		dmap := row.AsMap()
		vkey := fmt.Sprint(dmap[keyField])
		if _, y := r[vkey]; !y {
			r[vkey] = []*OfficialCustomerRolePermission{}
		}
		r[vkey] = append(r[vkey], row)
	}
	return r
}

func (s Slice_OfficialCustomerRolePermission) KeyBy(keyField string) map[string]*OfficialCustomerRolePermission {
	r := map[string]*OfficialCustomerRolePermission{}
	for _, row := range s {
		dmap := row.AsMap()
		vkey := fmt.Sprint(dmap[keyField])
		r[vkey] = row
	}
	return r
}

func (s Slice_OfficialCustomerRolePermission) AsKV(keyField string, valueField string) param.Store {
	r := param.Store{}
	for _, row := range s {
		dmap := row.AsMap()
		vkey := fmt.Sprint(dmap[keyField])
		r[vkey] = dmap[valueField]
	}
	return r
}

func (s Slice_OfficialCustomerRolePermission) Transform(transfers map[string]param.Transfer) []param.Store {
	r := make([]param.Store, len(s))
	for idx, row := range s {
		r[idx] = row.AsMap().Transform(transfers)
	}
	return r
}

func (s Slice_OfficialCustomerRolePermission) FromList(data interface{}) Slice_OfficialCustomerRolePermission {
	values, ok := data.([]*OfficialCustomerRolePermission)
	if !ok {
		for _, value := range data.([]interface{}) {
			row := &OfficialCustomerRolePermission{}
			row.FromRow(value.(map[string]interface{}))
			s = append(s, row)
		}
		return s
	}
	s = append(s, values...)

	return s
}

func NewOfficialCustomerRolePermission(ctx echo.Context) *OfficialCustomerRolePermission {
	m := &OfficialCustomerRolePermission{}
	m.SetContext(ctx)
	return m
}

// OfficialCustomerRolePermission
type OfficialCustomerRolePermission struct {
	base    factory.Base
	objects []*OfficialCustomerRolePermission

	RoleId     uint   `db:"role_id,pk" bson:"role_id" comment:"角色ID" json:"role_id" xml:"role_id"`
	Type       string `db:"type,pk" bson:"type" comment:"权限类型" json:"type" xml:"type"`
	Permission string `db:"permission" bson:"permission" comment:"权限值" json:"permission" xml:"permission"`
}

// - base function

func (a *OfficialCustomerRolePermission) Trans() factory.Transactioner {
	return a.base.Trans()
}

func (a *OfficialCustomerRolePermission) Use(trans factory.Transactioner) factory.Model {
	a.base.Use(trans)
	return a
}

func (a *OfficialCustomerRolePermission) SetContext(ctx echo.Context) factory.Model {
	a.base.SetContext(ctx)
	return a
}

func (a *OfficialCustomerRolePermission) EventON(on ...bool) factory.Model {
	a.base.EventON(on...)
	return a
}

func (a *OfficialCustomerRolePermission) EventOFF(off ...bool) factory.Model {
	a.base.EventOFF(off...)
	return a
}

func (a *OfficialCustomerRolePermission) Context() echo.Context {
	return a.base.Context()
}

func (a *OfficialCustomerRolePermission) SetConnID(connID int) factory.Model {
	a.base.SetConnID(connID)
	return a
}

func (a *OfficialCustomerRolePermission) ConnID() int {
	return a.base.ConnID()
}

func (a *OfficialCustomerRolePermission) SetNamer(namer func(factory.Model) string) factory.Model {
	a.base.SetNamer(namer)
	return a
}

func (a *OfficialCustomerRolePermission) Namer() func(factory.Model) string {
	return a.base.Namer()
}

func (a *OfficialCustomerRolePermission) SetParam(param *factory.Param) factory.Model {
	a.base.SetParam(param)
	return a
}

func (a *OfficialCustomerRolePermission) Param(mw func(db.Result) db.Result, args ...interface{}) *factory.Param {
	if a.base.Param() == nil {
		return a.NewParam().SetMiddleware(mw).SetArgs(args...)
	}
	return a.base.Param().SetMiddleware(mw).SetArgs(args...)
}

func (a *OfficialCustomerRolePermission) New(structName string, connID ...int) factory.Model {
	return a.base.New(structName, connID...)
}

func (a *OfficialCustomerRolePermission) Base_() factory.Baser {
	return &a.base
}

// - current function

func (a *OfficialCustomerRolePermission) Objects() []*OfficialCustomerRolePermission {
	if a.objects == nil {
		return nil
	}
	return a.objects[:]
}

func (a *OfficialCustomerRolePermission) XObjects() Slice_OfficialCustomerRolePermission {
	return Slice_OfficialCustomerRolePermission(a.Objects())
}

func (a *OfficialCustomerRolePermission) NewObjects() factory.Ranger {
	return &Slice_OfficialCustomerRolePermission{}
}

func (a *OfficialCustomerRolePermission) InitObjects() *[]*OfficialCustomerRolePermission {
	a.objects = []*OfficialCustomerRolePermission{}
	return &a.objects
}

func (a *OfficialCustomerRolePermission) NewParam() *factory.Param {
	return factory.NewParam(factory.DefaultFactory).SetIndex(a.base.ConnID()).SetTrans(a.base.Trans()).SetCollection(a.Name_()).SetModel(a)
}

func (a *OfficialCustomerRolePermission) Short_() string {
	return "official_customer_role_permission"
}

func (a *OfficialCustomerRolePermission) Struct_() string {
	return "OfficialCustomerRolePermission"
}

func (a *OfficialCustomerRolePermission) Name_() string {
	b := a
	if b == nil {
		b = &OfficialCustomerRolePermission{}
	}
	if b.base.Namer() != nil {
		return WithPrefix(b.base.Namer()(b))
	}
	return WithPrefix(factory.TableNamerGet(b.Short_())(b))
}

func (a *OfficialCustomerRolePermission) CPAFrom(source factory.Model) factory.Model {
	a.SetContext(source.Context())
	a.SetConnID(source.ConnID())
	a.SetNamer(source.Namer())
	return a
}

func (a *OfficialCustomerRolePermission) Get(mw func(db.Result) db.Result, args ...interface{}) (err error) {
	base := a.base
	if !a.base.Eventable() {
		err = a.Param(mw, args...).SetRecv(a).One()
		a.base = base
		return
	}
	queryParam := a.Param(mw, args...).SetRecv(a)
	if err = DBI.FireReading(a, queryParam); err != nil {
		return
	}
	err = queryParam.One()
	a.base = base
	if err == nil {
		err = DBI.FireReaded(a, queryParam)
	}
	return
}

func (a *OfficialCustomerRolePermission) List(recv interface{}, mw func(db.Result) db.Result, page, size int, args ...interface{}) (func() int64, error) {
	if recv == nil {
		recv = a.InitObjects()
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetPage(page).SetSize(size).SetRecv(recv).List()
	}
	queryParam := a.Param(mw, args...).SetPage(page).SetSize(size).SetRecv(recv)
	if err := DBI.FireReading(a, queryParam); err != nil {
		return nil, err
	}
	cnt, err := queryParam.List()
	if err == nil {
		switch v := recv.(type) {
		case *[]*OfficialCustomerRolePermission:
			err = DBI.FireReaded(a, queryParam, Slice_OfficialCustomerRolePermission(*v))
		case []*OfficialCustomerRolePermission:
			err = DBI.FireReaded(a, queryParam, Slice_OfficialCustomerRolePermission(v))
		case factory.Ranger:
			err = DBI.FireReaded(a, queryParam, v)
		}
	}
	return cnt, err
}

func (a *OfficialCustomerRolePermission) GroupBy(keyField string, inputRows ...[]*OfficialCustomerRolePermission) map[string][]*OfficialCustomerRolePermission {
	var rows Slice_OfficialCustomerRolePermission
	if len(inputRows) > 0 {
		rows = Slice_OfficialCustomerRolePermission(inputRows[0])
	} else {
		rows = Slice_OfficialCustomerRolePermission(a.Objects())
	}
	return rows.GroupBy(keyField)
}

func (a *OfficialCustomerRolePermission) KeyBy(keyField string, inputRows ...[]*OfficialCustomerRolePermission) map[string]*OfficialCustomerRolePermission {
	var rows Slice_OfficialCustomerRolePermission
	if len(inputRows) > 0 {
		rows = Slice_OfficialCustomerRolePermission(inputRows[0])
	} else {
		rows = Slice_OfficialCustomerRolePermission(a.Objects())
	}
	return rows.KeyBy(keyField)
}

func (a *OfficialCustomerRolePermission) AsKV(keyField string, valueField string, inputRows ...[]*OfficialCustomerRolePermission) param.Store {
	var rows Slice_OfficialCustomerRolePermission
	if len(inputRows) > 0 {
		rows = Slice_OfficialCustomerRolePermission(inputRows[0])
	} else {
		rows = Slice_OfficialCustomerRolePermission(a.Objects())
	}
	return rows.AsKV(keyField, valueField)
}

func (a *OfficialCustomerRolePermission) ListByOffset(recv interface{}, mw func(db.Result) db.Result, offset, size int, args ...interface{}) (func() int64, error) {
	if recv == nil {
		recv = a.InitObjects()
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetOffset(offset).SetSize(size).SetRecv(recv).List()
	}
	queryParam := a.Param(mw, args...).SetOffset(offset).SetSize(size).SetRecv(recv)
	if err := DBI.FireReading(a, queryParam); err != nil {
		return nil, err
	}
	cnt, err := queryParam.List()
	if err == nil {
		switch v := recv.(type) {
		case *[]*OfficialCustomerRolePermission:
			err = DBI.FireReaded(a, queryParam, Slice_OfficialCustomerRolePermission(*v))
		case []*OfficialCustomerRolePermission:
			err = DBI.FireReaded(a, queryParam, Slice_OfficialCustomerRolePermission(v))
		case factory.Ranger:
			err = DBI.FireReaded(a, queryParam, v)
		}
	}
	return cnt, err
}

func (a *OfficialCustomerRolePermission) Insert() (pk interface{}, err error) {

	if a.base.Eventable() {
		err = DBI.Fire("creating", a, nil)
		if err != nil {
			return
		}
	}
	pk, err = a.Param(nil).SetSend(a).Insert()

	if err == nil && a.base.Eventable() {
		err = DBI.Fire("created", a, nil)
	}
	return
}

func (a *OfficialCustomerRolePermission) Update(mw func(db.Result) db.Result, args ...interface{}) (err error) {

	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(a).Update()
	}
	if err = DBI.Fire("updating", a, mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).SetSend(a).Update(); err != nil {
		return
	}
	return DBI.Fire("updated", a, mw, args...)
}

func (a *OfficialCustomerRolePermission) Updatex(mw func(db.Result) db.Result, args ...interface{}) (affected int64, err error) {

	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(a).Updatex()
	}
	if err = DBI.Fire("updating", a, mw, args...); err != nil {
		return
	}
	if affected, err = a.Param(mw, args...).SetSend(a).Updatex(); err != nil {
		return
	}
	err = DBI.Fire("updated", a, mw, args...)
	return
}

func (a *OfficialCustomerRolePermission) UpdateByFields(mw func(db.Result) db.Result, fields []string, args ...interface{}) (err error) {

	if !a.base.Eventable() {
		return a.Param(mw, args...).UpdateByStruct(a, fields...)
	}
	editColumns := make([]string, len(fields))
	for index, field := range fields {
		editColumns[index] = com.SnakeCase(field)
	}
	if err = DBI.FireUpdate("updating", a, editColumns, mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).UpdateByStruct(a, fields...); err != nil {
		return
	}
	err = DBI.FireUpdate("updated", a, editColumns, mw, args...)
	return
}

func (a *OfficialCustomerRolePermission) UpdatexByFields(mw func(db.Result) db.Result, fields []string, args ...interface{}) (affected int64, err error) {

	if !a.base.Eventable() {
		return a.Param(mw, args...).UpdatexByStruct(a, fields...)
	}
	editColumns := make([]string, len(fields))
	for index, field := range fields {
		editColumns[index] = com.SnakeCase(field)
	}
	if err = DBI.FireUpdate("updating", a, editColumns, mw, args...); err != nil {
		return
	}
	if affected, err = a.Param(mw, args...).UpdatexByStruct(a, fields...); err != nil {
		return
	}
	err = DBI.FireUpdate("updated", a, editColumns, mw, args...)
	return
}

func (a *OfficialCustomerRolePermission) UpdateField(mw func(db.Result) db.Result, field string, value interface{}, args ...interface{}) (err error) {
	return a.UpdateFields(mw, map[string]interface{}{
		field: value,
	}, args...)
}

func (a *OfficialCustomerRolePermission) UpdatexField(mw func(db.Result) db.Result, field string, value interface{}, args ...interface{}) (affected int64, err error) {
	return a.UpdatexFields(mw, map[string]interface{}{
		field: value,
	}, args...)
}

func (a *OfficialCustomerRolePermission) UpdateFields(mw func(db.Result) db.Result, kvset map[string]interface{}, args ...interface{}) (err error) {

	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(kvset).Update()
	}
	m := *a
	m.FromRow(kvset)
	var editColumns []string
	for column := range kvset {
		editColumns = append(editColumns, column)
	}
	if err = DBI.FireUpdate("updating", &m, editColumns, mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).SetSend(kvset).Update(); err != nil {
		return
	}
	return DBI.FireUpdate("updated", &m, editColumns, mw, args...)
}

func (a *OfficialCustomerRolePermission) UpdatexFields(mw func(db.Result) db.Result, kvset map[string]interface{}, args ...interface{}) (affected int64, err error) {

	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(kvset).Updatex()
	}
	m := *a
	m.FromRow(kvset)
	var editColumns []string
	for column := range kvset {
		editColumns = append(editColumns, column)
	}
	if err = DBI.FireUpdate("updating", &m, editColumns, mw, args...); err != nil {
		return
	}
	if affected, err = a.Param(mw, args...).SetSend(kvset).Updatex(); err != nil {
		return
	}
	err = DBI.FireUpdate("updated", &m, editColumns, mw, args...)
	return
}

func (a *OfficialCustomerRolePermission) UpdateValues(mw func(db.Result) db.Result, keysValues *db.KeysValues, args ...interface{}) (err error) {
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(keysValues).Update()
	}
	m := *a
	m.FromRow(keysValues.Map())
	if err = DBI.FireUpdate("updating", &m, keysValues.Keys(), mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).SetSend(keysValues).Update(); err != nil {
		return
	}
	return DBI.FireUpdate("updated", &m, keysValues.Keys(), mw, args...)
}

func (a *OfficialCustomerRolePermission) Upsert(mw func(db.Result) db.Result, args ...interface{}) (pk interface{}, err error) {
	pk, err = a.Param(mw, args...).SetSend(a).Upsert(func() error {
		if !a.base.Eventable() {
			return nil
		}
		return DBI.Fire("updating", a, mw, args...)
	}, func() error {
		if !a.base.Eventable() {
			return nil
		}
		return DBI.Fire("creating", a, nil)
	})

	if err == nil && a.base.Eventable() {
		if pk == nil {
			err = DBI.Fire("updated", a, mw, args...)
		} else {
			err = DBI.Fire("created", a, nil)
		}
	}
	return
}

func (a *OfficialCustomerRolePermission) Delete(mw func(db.Result) db.Result, args ...interface{}) (err error) {

	if !a.base.Eventable() {
		return a.Param(mw, args...).Delete()
	}
	if err = DBI.Fire("deleting", a, mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).Delete(); err != nil {
		return
	}
	return DBI.Fire("deleted", a, mw, args...)
}

func (a *OfficialCustomerRolePermission) Deletex(mw func(db.Result) db.Result, args ...interface{}) (affected int64, err error) {

	if !a.base.Eventable() {
		return a.Param(mw, args...).Deletex()
	}
	if err = DBI.Fire("deleting", a, mw, args...); err != nil {
		return
	}
	if affected, err = a.Param(mw, args...).Deletex(); err != nil {
		return
	}
	err = DBI.Fire("deleted", a, mw, args...)
	return
}

func (a *OfficialCustomerRolePermission) Count(mw func(db.Result) db.Result, args ...interface{}) (int64, error) {
	return a.Param(mw, args...).Count()
}

func (a *OfficialCustomerRolePermission) Exists(mw func(db.Result) db.Result, args ...interface{}) (bool, error) {
	return a.Param(mw, args...).Exists()
}

func (a *OfficialCustomerRolePermission) Reset() *OfficialCustomerRolePermission {
	a.RoleId = 0
	a.Type = ``
	a.Permission = ``
	return a
}

func (a *OfficialCustomerRolePermission) AsMap(onlyFields ...string) param.Store {
	r := param.Store{}
	if len(onlyFields) == 0 {
		r["RoleId"] = a.RoleId
		r["Type"] = a.Type
		r["Permission"] = a.Permission
		return r
	}
	for _, field := range onlyFields {
		switch field {
		case "RoleId":
			r["RoleId"] = a.RoleId
		case "Type":
			r["Type"] = a.Type
		case "Permission":
			r["Permission"] = a.Permission
		}
	}
	return r
}

func (a *OfficialCustomerRolePermission) FromRow(row map[string]interface{}) {
	for key, value := range row {
		switch key {
		case "role_id":
			a.RoleId = param.AsUint(value)
		case "type":
			a.Type = param.AsString(value)
		case "permission":
			a.Permission = param.AsString(value)
		}
	}
}

func (a *OfficialCustomerRolePermission) Set(key interface{}, value ...interface{}) {
	switch k := key.(type) {
	case map[string]interface{}:
		for kk, vv := range k {
			a.Set(kk, vv)
		}
	default:
		var (
			kk string
			vv interface{}
		)
		if k, y := key.(string); y {
			kk = k
		} else {
			kk = fmt.Sprint(key)
		}
		if len(value) > 0 {
			vv = value[0]
		}
		switch kk {
		case "RoleId":
			a.RoleId = param.AsUint(vv)
		case "Type":
			a.Type = param.AsString(vv)
		case "Permission":
			a.Permission = param.AsString(vv)
		}
	}
}

func (a *OfficialCustomerRolePermission) AsRow(onlyFields ...string) param.Store {
	r := param.Store{}
	if len(onlyFields) == 0 {
		r["role_id"] = a.RoleId
		r["type"] = a.Type
		r["permission"] = a.Permission
		return r
	}
	for _, field := range onlyFields {
		switch field {
		case "role_id":
			r["role_id"] = a.RoleId
		case "type":
			r["type"] = a.Type
		case "permission":
			r["permission"] = a.Permission
		}
	}
	return r
}

func (a *OfficialCustomerRolePermission) ListPage(cond *db.Compounds, sorts ...interface{}) error {
	_, err := pagination.NewLister(a, nil, func(r db.Result) db.Result {
		return r.OrderBy(sorts...)
	}, cond.And()).Paging(a.Context())
	return err
}

func (a *OfficialCustomerRolePermission) ListPageAs(recv interface{}, cond *db.Compounds, sorts ...interface{}) error {
	_, err := pagination.NewLister(a, recv, func(r db.Result) db.Result {
		return r.OrderBy(sorts...)
	}, cond.And()).Paging(a.Context())
	return err
}

func (a *OfficialCustomerRolePermission) BatchValidate(kvset map[string]interface{}) error {
	if kvset == nil {
		kvset = a.AsRow()
	}
	return DBI.Fields.BatchValidate(a.Short_(), kvset)
}

func (a *OfficialCustomerRolePermission) Validate(field string, value interface{}) error {
	return DBI.Fields.Validate(a.Short_(), field, value)
}
