// @generated Do not edit this file, which is automatically generated by the generator.

package dbschema

import (
	"fmt"

	"time"

	"github.com/webx-top/com"
	"github.com/webx-top/db"
	"github.com/webx-top/db/lib/factory"
	"github.com/webx-top/db/lib/factory/pagination"
	"github.com/webx-top/echo"
	"github.com/webx-top/echo/param"
)

type Slice_OfficialCustomerFollowing = factory.Slicex[*OfficialCustomerFollowing]

func NewOfficialCustomerFollowing(ctx echo.Context) *OfficialCustomerFollowing {
	m := &OfficialCustomerFollowing{}
	m.SetContext(ctx)
	return m
}

// OfficialCustomerFollowing 关注
type OfficialCustomerFollowing struct {
	base    factory.Base
	objects []*OfficialCustomerFollowing

	CustomerA uint64 `db:"customer_a,pk" bson:"customer_a" comment:"关注人ID" json:"customer_a" xml:"customer_a"`
	CustomerB uint64 `db:"customer_b,pk" bson:"customer_b" comment:"被关注人ID" json:"customer_b" xml:"customer_b"`
	Created   uint   `db:"created" bson:"created" comment:"创建时间" json:"created" xml:"created" form_decoder:"time2unix" form_encoder:"unix2time"`
	Mutual    string `db:"mutual" bson:"mutual" comment:"是否相互关注" json:"mutual" xml:"mutual"`
}

// - base function

func (a *OfficialCustomerFollowing) Trans() factory.Transactioner {
	return a.base.Trans()
}

func (a *OfficialCustomerFollowing) Use(trans factory.Transactioner) factory.Model {
	a.base.Use(trans)
	return a
}

func (a *OfficialCustomerFollowing) SetContext(ctx echo.Context) factory.Model {
	a.base.SetContext(ctx)
	return a
}

func (a *OfficialCustomerFollowing) EventON(on ...bool) factory.Model {
	a.base.EventON(on...)
	return a
}

func (a *OfficialCustomerFollowing) EventOFF(off ...bool) factory.Model {
	a.base.EventOFF(off...)
	return a
}

func (a *OfficialCustomerFollowing) Context() echo.Context {
	return a.base.Context()
}

func (a *OfficialCustomerFollowing) SetConnID(connID int) factory.Model {
	a.base.SetConnID(connID)
	return a
}

func (a *OfficialCustomerFollowing) ConnID() int {
	return a.base.ConnID()
}

func (a *OfficialCustomerFollowing) SetNamer(namer func(factory.Model) string) factory.Model {
	a.base.SetNamer(namer)
	return a
}

func (a *OfficialCustomerFollowing) Namer() func(factory.Model) string {
	return a.base.Namer()
}

func (a *OfficialCustomerFollowing) SetParam(param *factory.Param) factory.Model {
	a.base.SetParam(param)
	return a
}

func (a *OfficialCustomerFollowing) Param(mw func(db.Result) db.Result, args ...interface{}) *factory.Param {
	if a.base.Param() == nil {
		return a.NewParam().SetMiddleware(mw).SetArgs(args...)
	}
	return a.base.Param().SetMiddleware(mw).SetArgs(args...)
}

func (a *OfficialCustomerFollowing) New(structName string, connID ...int) factory.Model {
	return a.base.New(structName, connID...)
}

func (a *OfficialCustomerFollowing) Base_() factory.Baser {
	return &a.base
}

// - current function

func (a *OfficialCustomerFollowing) Objects() []*OfficialCustomerFollowing {
	if a.objects == nil {
		return nil
	}
	return a.objects[:]
}

func (a *OfficialCustomerFollowing) XObjects() Slice_OfficialCustomerFollowing {
	return Slice_OfficialCustomerFollowing(a.Objects())
}

func (a *OfficialCustomerFollowing) NewObjects() factory.Ranger {
	return &Slice_OfficialCustomerFollowing{}
}

func (a *OfficialCustomerFollowing) InitObjects() *[]*OfficialCustomerFollowing {
	a.objects = []*OfficialCustomerFollowing{}
	return &a.objects
}

func (a *OfficialCustomerFollowing) NewParam() *factory.Param {
	return factory.NewParam(factory.DefaultFactory).SetIndex(a.base.ConnID()).SetTrans(a.base.Trans()).SetCollection(a.Name_()).SetModel(a)
}

func (a *OfficialCustomerFollowing) Short_() string {
	return "official_customer_following"
}

func (a *OfficialCustomerFollowing) Struct_() string {
	return "OfficialCustomerFollowing"
}

func (a *OfficialCustomerFollowing) Name_() string {
	b := a
	if b == nil {
		b = &OfficialCustomerFollowing{}
	}
	if b.base.Namer() != nil {
		return WithPrefix(b.base.Namer()(b))
	}
	return WithPrefix(factory.TableNamerGet(b.Short_())(b))
}

// CPAFrom Deprecated: Use CtxFrom instead.
func (a *OfficialCustomerFollowing) CPAFrom(source factory.Model) factory.Model {
	return a.CtxFrom(source)
}

func (a *OfficialCustomerFollowing) CtxFrom(source factory.Model) factory.Model {
	a.base.CtxFrom(source)
	return a
}

func (a *OfficialCustomerFollowing) Get(mw func(db.Result) db.Result, args ...interface{}) (err error) {
	base := a.base
	if !a.base.Eventable() {
		err = a.Param(mw, args...).SetRecv(a).One()
		a.base = base
		return
	}
	queryParam := a.Param(mw, args...).SetRecv(a)
	if err = a.base.FireReading(a, queryParam); err != nil {
		return
	}
	err = queryParam.One()
	a.base = base
	if err == nil {
		err = a.base.FireReaded(a, queryParam)
	}
	return
}

func (a *OfficialCustomerFollowing) List(recv interface{}, mw func(db.Result) db.Result, page, size int, args ...interface{}) (func() int64, error) {
	if recv == nil {
		recv = a.InitObjects()
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetPage(page).SetSize(size).SetRecv(recv).List()
	}
	queryParam := a.Param(mw, args...).SetPage(page).SetSize(size).SetRecv(recv)
	if err := a.base.FireReading(a, queryParam); err != nil {
		return nil, err
	}
	cnt, err := queryParam.List()
	if err == nil {
		switch v := recv.(type) {
		case *[]*OfficialCustomerFollowing:
			err = a.base.FireReaded(a, queryParam, Slice_OfficialCustomerFollowing(*v))
		case []*OfficialCustomerFollowing:
			err = a.base.FireReaded(a, queryParam, Slice_OfficialCustomerFollowing(v))
		case factory.Ranger:
			err = a.base.FireReaded(a, queryParam, v)
		}
	}
	return cnt, err
}

func (a *OfficialCustomerFollowing) GroupBy(keyField string, inputRows ...[]*OfficialCustomerFollowing) map[string][]*OfficialCustomerFollowing {
	var rows Slice_OfficialCustomerFollowing
	if len(inputRows) > 0 {
		rows = Slice_OfficialCustomerFollowing(inputRows[0])
	} else {
		rows = Slice_OfficialCustomerFollowing(a.Objects())
	}
	return rows.GroupBy(keyField)
}

func (a *OfficialCustomerFollowing) KeyBy(keyField string, inputRows ...[]*OfficialCustomerFollowing) map[string]*OfficialCustomerFollowing {
	var rows Slice_OfficialCustomerFollowing
	if len(inputRows) > 0 {
		rows = Slice_OfficialCustomerFollowing(inputRows[0])
	} else {
		rows = Slice_OfficialCustomerFollowing(a.Objects())
	}
	return rows.KeyBy(keyField)
}

func (a *OfficialCustomerFollowing) AsKV(keyField string, valueField string, inputRows ...[]*OfficialCustomerFollowing) param.Store {
	var rows Slice_OfficialCustomerFollowing
	if len(inputRows) > 0 {
		rows = Slice_OfficialCustomerFollowing(inputRows[0])
	} else {
		rows = Slice_OfficialCustomerFollowing(a.Objects())
	}
	return rows.AsKV(keyField, valueField)
}

func (a *OfficialCustomerFollowing) ListByOffset(recv interface{}, mw func(db.Result) db.Result, offset, size int, args ...interface{}) (func() int64, error) {
	if recv == nil {
		recv = a.InitObjects()
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetOffset(offset).SetSize(size).SetRecv(recv).List()
	}
	queryParam := a.Param(mw, args...).SetOffset(offset).SetSize(size).SetRecv(recv)
	if err := a.base.FireReading(a, queryParam); err != nil {
		return nil, err
	}
	cnt, err := queryParam.List()
	if err == nil {
		switch v := recv.(type) {
		case *[]*OfficialCustomerFollowing:
			err = a.base.FireReaded(a, queryParam, Slice_OfficialCustomerFollowing(*v))
		case []*OfficialCustomerFollowing:
			err = a.base.FireReaded(a, queryParam, Slice_OfficialCustomerFollowing(v))
		case factory.Ranger:
			err = a.base.FireReaded(a, queryParam, v)
		}
	}
	return cnt, err
}

func (a *OfficialCustomerFollowing) Insert() (pk interface{}, err error) {
	a.Created = uint(time.Now().Unix())
	if len(a.Mutual) == 0 {
		a.Mutual = "N"
	}
	if a.base.Eventable() {
		err = a.base.Fire(factory.EventCreating, a, nil)
		if err != nil {
			return
		}
	}
	pk, err = a.Param(nil).SetSend(a).Insert()

	if err == nil && a.base.Eventable() {
		err = a.base.Fire(factory.EventCreated, a, nil)
	}
	return
}

func (a *OfficialCustomerFollowing) Update(mw func(db.Result) db.Result, args ...interface{}) (err error) {

	if len(a.Mutual) == 0 {
		a.Mutual = "N"
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(a).Update()
	}
	if err = a.base.Fire(factory.EventUpdating, a, mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).SetSend(a).Update(); err != nil {
		return
	}
	return a.base.Fire(factory.EventUpdated, a, mw, args...)
}

func (a *OfficialCustomerFollowing) Updatex(mw func(db.Result) db.Result, args ...interface{}) (affected int64, err error) {

	if len(a.Mutual) == 0 {
		a.Mutual = "N"
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(a).Updatex()
	}
	if err = a.base.Fire(factory.EventUpdating, a, mw, args...); err != nil {
		return
	}
	if affected, err = a.Param(mw, args...).SetSend(a).Updatex(); err != nil {
		return
	}
	err = a.base.Fire(factory.EventUpdated, a, mw, args...)
	return
}

func (a *OfficialCustomerFollowing) UpdateByFields(mw func(db.Result) db.Result, fields []string, args ...interface{}) (err error) {

	if len(a.Mutual) == 0 {
		a.Mutual = "N"
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).UpdateByStruct(a, fields...)
	}
	editColumns := make([]string, len(fields))
	for index, field := range fields {
		editColumns[index] = com.SnakeCase(field)
	}
	if err = a.base.FireUpdate(factory.EventUpdating, a, editColumns, mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).UpdateByStruct(a, fields...); err != nil {
		return
	}
	err = a.base.FireUpdate(factory.EventUpdated, a, editColumns, mw, args...)
	return
}

func (a *OfficialCustomerFollowing) UpdatexByFields(mw func(db.Result) db.Result, fields []string, args ...interface{}) (affected int64, err error) {

	if len(a.Mutual) == 0 {
		a.Mutual = "N"
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).UpdatexByStruct(a, fields...)
	}
	editColumns := make([]string, len(fields))
	for index, field := range fields {
		editColumns[index] = com.SnakeCase(field)
	}
	if err = a.base.FireUpdate(factory.EventUpdating, a, editColumns, mw, args...); err != nil {
		return
	}
	if affected, err = a.Param(mw, args...).UpdatexByStruct(a, fields...); err != nil {
		return
	}
	err = a.base.FireUpdate(factory.EventUpdated, a, editColumns, mw, args...)
	return
}

func (a *OfficialCustomerFollowing) UpdateField(mw func(db.Result) db.Result, field string, value interface{}, args ...interface{}) (err error) {
	return a.UpdateFields(mw, map[string]interface{}{
		field: value,
	}, args...)
}

func (a *OfficialCustomerFollowing) UpdatexField(mw func(db.Result) db.Result, field string, value interface{}, args ...interface{}) (affected int64, err error) {
	return a.UpdatexFields(mw, map[string]interface{}{
		field: value,
	}, args...)
}

func (a *OfficialCustomerFollowing) UpdateFields(mw func(db.Result) db.Result, kvset map[string]interface{}, args ...interface{}) (err error) {

	if val, ok := kvset["mutual"]; ok && val != nil {
		if v, ok := val.(string); ok && len(v) == 0 {
			kvset["mutual"] = "N"
		}
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(kvset).Update()
	}
	m := *a
	m.FromRow(kvset)
	editColumns := make([]string, 0, len(kvset))
	for column := range kvset {
		editColumns = append(editColumns, column)
	}
	if err = a.base.FireUpdate(factory.EventUpdating, &m, editColumns, mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).SetSend(kvset).Update(); err != nil {
		return
	}
	return a.base.FireUpdate(factory.EventUpdated, &m, editColumns, mw, args...)
}

func (a *OfficialCustomerFollowing) UpdatexFields(mw func(db.Result) db.Result, kvset map[string]interface{}, args ...interface{}) (affected int64, err error) {

	if val, ok := kvset["mutual"]; ok && val != nil {
		if v, ok := val.(string); ok && len(v) == 0 {
			kvset["mutual"] = "N"
		}
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(kvset).Updatex()
	}
	m := *a
	m.FromRow(kvset)
	editColumns := make([]string, 0, len(kvset))
	for column := range kvset {
		editColumns = append(editColumns, column)
	}
	if err = a.base.FireUpdate(factory.EventUpdating, &m, editColumns, mw, args...); err != nil {
		return
	}
	if affected, err = a.Param(mw, args...).SetSend(kvset).Updatex(); err != nil {
		return
	}
	err = a.base.FireUpdate(factory.EventUpdated, &m, editColumns, mw, args...)
	return
}

func (a *OfficialCustomerFollowing) UpdateValues(mw func(db.Result) db.Result, keysValues *db.KeysValues, args ...interface{}) (err error) {
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(keysValues).Update()
	}
	m := *a
	m.FromRow(keysValues.Map())
	if err = a.base.FireUpdate(factory.EventUpdating, &m, keysValues.Keys(), mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).SetSend(keysValues).Update(); err != nil {
		return
	}
	return a.base.FireUpdate(factory.EventUpdated, &m, keysValues.Keys(), mw, args...)
}

func (a *OfficialCustomerFollowing) Upsert(mw func(db.Result) db.Result, args ...interface{}) (pk interface{}, err error) {
	pk, err = a.Param(mw, args...).SetSend(a).Upsert(func() error {
		if len(a.Mutual) == 0 {
			a.Mutual = "N"
		}
		if !a.base.Eventable() {
			return nil
		}
		return a.base.Fire(factory.EventUpdating, a, mw, args...)
	}, func() error {
		a.Created = uint(time.Now().Unix())
		if len(a.Mutual) == 0 {
			a.Mutual = "N"
		}
		if !a.base.Eventable() {
			return nil
		}
		return a.base.Fire(factory.EventCreating, a, nil)
	})

	if err == nil && a.base.Eventable() {
		if pk == nil {
			err = a.base.Fire(factory.EventUpdated, a, mw, args...)
		} else {
			err = a.base.Fire(factory.EventCreated, a, nil)
		}
	}
	return
}

func (a *OfficialCustomerFollowing) Delete(mw func(db.Result) db.Result, args ...interface{}) (err error) {

	if !a.base.Eventable() {
		return a.Param(mw, args...).Delete()
	}
	if err = a.base.Fire(factory.EventDeleting, a, mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).Delete(); err != nil {
		return
	}
	return a.base.Fire(factory.EventDeleted, a, mw, args...)
}

func (a *OfficialCustomerFollowing) Deletex(mw func(db.Result) db.Result, args ...interface{}) (affected int64, err error) {

	if !a.base.Eventable() {
		return a.Param(mw, args...).Deletex()
	}
	if err = a.base.Fire(factory.EventDeleting, a, mw, args...); err != nil {
		return
	}
	if affected, err = a.Param(mw, args...).Deletex(); err != nil {
		return
	}
	err = a.base.Fire(factory.EventDeleted, a, mw, args...)
	return
}

func (a *OfficialCustomerFollowing) Count(mw func(db.Result) db.Result, args ...interface{}) (int64, error) {
	return a.Param(mw, args...).Count()
}

func (a *OfficialCustomerFollowing) Exists(mw func(db.Result) db.Result, args ...interface{}) (bool, error) {
	return a.Param(mw, args...).Exists()
}

func (a *OfficialCustomerFollowing) Reset() *OfficialCustomerFollowing {
	a.CustomerA = 0
	a.CustomerB = 0
	a.Created = 0
	a.Mutual = ``
	return a
}

func (a *OfficialCustomerFollowing) AsMap(onlyFields ...string) param.Store {
	r := param.Store{}
	if len(onlyFields) == 0 {
		r["CustomerA"] = a.CustomerA
		r["CustomerB"] = a.CustomerB
		r["Created"] = a.Created
		r["Mutual"] = a.Mutual
		return r
	}
	for _, field := range onlyFields {
		switch field {
		case "CustomerA":
			r["CustomerA"] = a.CustomerA
		case "CustomerB":
			r["CustomerB"] = a.CustomerB
		case "Created":
			r["Created"] = a.Created
		case "Mutual":
			r["Mutual"] = a.Mutual
		}
	}
	return r
}

func (a *OfficialCustomerFollowing) Clone() *OfficialCustomerFollowing {
	cloned := OfficialCustomerFollowing{CustomerA: a.CustomerA, CustomerB: a.CustomerB, Created: a.Created, Mutual: a.Mutual}
	cloned.CtxFrom(a)
	return &cloned
}

func (a *OfficialCustomerFollowing) FromRow(row map[string]interface{}) {
	for key, value := range row {
		if _, ok := value.(db.RawValue); ok {
			continue
		}
		switch key {
		case "customer_a":
			a.CustomerA = param.AsUint64(value)
		case "customer_b":
			a.CustomerB = param.AsUint64(value)
		case "created":
			a.Created = param.AsUint(value)
		case "mutual":
			a.Mutual = param.AsString(value)
		}
	}
}

func (a *OfficialCustomerFollowing) GetField(field string) interface{} {
	switch field {
	case "CustomerA":
		return a.CustomerA
	case "CustomerB":
		return a.CustomerB
	case "Created":
		return a.Created
	case "Mutual":
		return a.Mutual
	default:
		return nil
	}
}

func (a *OfficialCustomerFollowing) GetAllFieldNames() []string {
	return []string{
		"CustomerA",
		"CustomerB",
		"Created",
		"Mutual",
	}
}

func (a *OfficialCustomerFollowing) HasField(field string) bool {
	switch field {
	case "CustomerA":
		return true
	case "CustomerB":
		return true
	case "Created":
		return true
	case "Mutual":
		return true
	default:
		return false
	}
}

func (a *OfficialCustomerFollowing) Set(key interface{}, value ...interface{}) {
	switch k := key.(type) {
	case map[string]interface{}:
		for kk, vv := range k {
			a.Set(kk, vv)
		}
	default:
		var (
			kk string
			vv interface{}
		)
		if k, y := key.(string); y {
			kk = k
		} else {
			kk = fmt.Sprint(key)
		}
		if len(value) > 0 {
			vv = value[0]
		}
		switch kk {
		case "CustomerA":
			a.CustomerA = param.AsUint64(vv)
		case "CustomerB":
			a.CustomerB = param.AsUint64(vv)
		case "Created":
			a.Created = param.AsUint(vv)
		case "Mutual":
			a.Mutual = param.AsString(vv)
		}
	}
}

func (a *OfficialCustomerFollowing) AsRow(onlyFields ...string) param.Store {
	r := param.Store{}
	if len(onlyFields) == 0 {
		r["customer_a"] = a.CustomerA
		r["customer_b"] = a.CustomerB
		r["created"] = a.Created
		r["mutual"] = a.Mutual
		return r
	}
	for _, field := range onlyFields {
		switch field {
		case "customer_a":
			r["customer_a"] = a.CustomerA
		case "customer_b":
			r["customer_b"] = a.CustomerB
		case "created":
			r["created"] = a.Created
		case "mutual":
			r["mutual"] = a.Mutual
		}
	}
	return r
}

func (a *OfficialCustomerFollowing) ListPage(cond *db.Compounds, sorts ...interface{}) error {
	return pagination.ListPage(a, cond, sorts...)
}

func (a *OfficialCustomerFollowing) ListPageAs(recv interface{}, cond *db.Compounds, sorts ...interface{}) error {
	return pagination.ListPageAs(a, recv, cond, sorts...)
}

func (a *OfficialCustomerFollowing) ListPageByOffset(cond *db.Compounds, sorts ...interface{}) error {
	return pagination.ListPageByOffset(a, cond, sorts...)
}

func (a *OfficialCustomerFollowing) ListPageByOffsetAs(recv interface{}, cond *db.Compounds, sorts ...interface{}) error {
	return pagination.ListPageByOffsetAs(a, recv, cond, sorts...)
}

func (a *OfficialCustomerFollowing) BatchValidate(kvset map[string]interface{}) error {
	return a.base.BatchValidate(a, kvset)
}

func (a *OfficialCustomerFollowing) Validate(column string, value interface{}) error {
	return a.base.Validate(a, column, value)
}

func (a *OfficialCustomerFollowing) TrimOverflowText(column string, value string) string {
	return a.base.TrimOverflowText(a, column, value)
}
