// @generated Do not edit this file, which is automatically generated by the generator.

package dbschema

import (
	"fmt"

	"time"

	"github.com/webx-top/com"
	"github.com/webx-top/db"
	"github.com/webx-top/db/lib/factory"
	"github.com/webx-top/db/lib/factory/pagination"
	"github.com/webx-top/echo"
	"github.com/webx-top/echo/param"
)

type Slice_OfficialCommonApiAccount []*OfficialCommonApiAccount

func (s Slice_OfficialCommonApiAccount) Range(fn func(m factory.Model) error) error {
	for _, v := range s {
		if err := fn(v); err != nil {
			return err
		}
	}
	return nil
}

func (s Slice_OfficialCommonApiAccount) RangeRaw(fn func(m *OfficialCommonApiAccount) error) error {
	for _, v := range s {
		if err := fn(v); err != nil {
			return err
		}
	}
	return nil
}

func (s Slice_OfficialCommonApiAccount) GroupBy(keyField string) map[string][]*OfficialCommonApiAccount {
	r := map[string][]*OfficialCommonApiAccount{}
	for _, row := range s {
		dmap := row.AsMap()
		vkey := fmt.Sprint(dmap[keyField])
		if _, y := r[vkey]; !y {
			r[vkey] = []*OfficialCommonApiAccount{}
		}
		r[vkey] = append(r[vkey], row)
	}
	return r
}

func (s Slice_OfficialCommonApiAccount) KeyBy(keyField string) map[string]*OfficialCommonApiAccount {
	r := map[string]*OfficialCommonApiAccount{}
	for _, row := range s {
		dmap := row.AsMap()
		vkey := fmt.Sprint(dmap[keyField])
		r[vkey] = row
	}
	return r
}

func (s Slice_OfficialCommonApiAccount) AsKV(keyField string, valueField string) param.Store {
	r := param.Store{}
	for _, row := range s {
		dmap := row.AsMap()
		vkey := fmt.Sprint(dmap[keyField])
		r[vkey] = dmap[valueField]
	}
	return r
}

func (s Slice_OfficialCommonApiAccount) Transform(transfers map[string]param.Transfer) []param.Store {
	r := make([]param.Store, len(s))
	for idx, row := range s {
		r[idx] = row.AsMap().Transform(transfers)
	}
	return r
}

func (s Slice_OfficialCommonApiAccount) FromList(data interface{}) Slice_OfficialCommonApiAccount {
	values, ok := data.([]*OfficialCommonApiAccount)
	if !ok {
		for _, value := range data.([]interface{}) {
			row := &OfficialCommonApiAccount{}
			row.FromRow(value.(map[string]interface{}))
			s = append(s, row)
		}
		return s
	}
	s = append(s, values...)

	return s
}

func NewOfficialCommonApiAccount(ctx echo.Context) *OfficialCommonApiAccount {
	m := &OfficialCommonApiAccount{}
	m.SetContext(ctx)
	return m
}

// OfficialCommonApiAccount
type OfficialCommonApiAccount struct {
	base    factory.Base
	objects []*OfficialCommonApiAccount

	Id         uint64 `db:"id,omitempty,pk" bson:"id,omitempty" comment:"ID" json:"id" xml:"id"`
	OwnerType  string `db:"owner_type" bson:"owner_type" comment:"所有者类型(user-后台用户;customer-前台客户)" json:"owner_type" xml:"owner_type"`
	OwnerId    uint64 `db:"owner_id" bson:"owner_id" comment:"所有者ID" json:"owner_id" xml:"owner_id"`
	GroupId    uint   `db:"group_id" bson:"group_id" comment:"分组" json:"group_id" xml:"group_id"`
	Name       string `db:"name" bson:"name" comment:"接口名称" json:"name" xml:"name"`
	Url        string `db:"url" bson:"url" comment:"接口网址(生产环境)" json:"url" xml:"url"`
	UrlDev     string `db:"url_dev" bson:"url_dev" comment:"接口网址(测试环境)" json:"url_dev" xml:"url_dev"`
	AppId      string `db:"app_id" bson:"app_id" comment:"APP ID" json:"app_id" xml:"app_id"`
	AppSecret  string `db:"app_secret" bson:"app_secret" comment:"APP 密钥" json:"app_secret" xml:"app_secret"`
	PublicKey  string `db:"public_key" bson:"public_key" comment:"公钥" json:"public_key" xml:"public_key"`
	Encryption string `db:"encryption" bson:"encryption" comment:"加密方式" json:"encryption" xml:"encryption"`
	Extra      string `db:"extra" bson:"extra" comment:"扩展数据(JSON格式)" json:"extra" xml:"extra"`
	Disabled   string `db:"disabled" bson:"disabled" comment:"是否禁用" json:"disabled" xml:"disabled"`
	Created    uint   `db:"created" bson:"created" comment:"创建时间" json:"created" xml:"created"`
	Updated    uint   `db:"updated" bson:"updated" comment:"更新时间" json:"updated" xml:"updated"`
}

// - base function

func (a *OfficialCommonApiAccount) Trans() factory.Transactioner {
	return a.base.Trans()
}

func (a *OfficialCommonApiAccount) Use(trans factory.Transactioner) factory.Model {
	a.base.Use(trans)
	return a
}

func (a *OfficialCommonApiAccount) SetContext(ctx echo.Context) factory.Model {
	a.base.SetContext(ctx)
	return a
}

func (a *OfficialCommonApiAccount) EventON(on ...bool) factory.Model {
	a.base.EventON(on...)
	return a
}

func (a *OfficialCommonApiAccount) EventOFF(off ...bool) factory.Model {
	a.base.EventOFF(off...)
	return a
}

func (a *OfficialCommonApiAccount) Context() echo.Context {
	return a.base.Context()
}

func (a *OfficialCommonApiAccount) SetConnID(connID int) factory.Model {
	a.base.SetConnID(connID)
	return a
}

func (a *OfficialCommonApiAccount) ConnID() int {
	return a.base.ConnID()
}

func (a *OfficialCommonApiAccount) SetNamer(namer func(factory.Model) string) factory.Model {
	a.base.SetNamer(namer)
	return a
}

func (a *OfficialCommonApiAccount) Namer() func(factory.Model) string {
	return a.base.Namer()
}

func (a *OfficialCommonApiAccount) SetParam(param *factory.Param) factory.Model {
	a.base.SetParam(param)
	return a
}

func (a *OfficialCommonApiAccount) Param(mw func(db.Result) db.Result, args ...interface{}) *factory.Param {
	if a.base.Param() == nil {
		return a.NewParam().SetMiddleware(mw).SetArgs(args...)
	}
	return a.base.Param().SetMiddleware(mw).SetArgs(args...)
}

func (a *OfficialCommonApiAccount) New(structName string, connID ...int) factory.Model {
	return a.base.New(structName, connID...)
}

func (a *OfficialCommonApiAccount) Base_() factory.Baser {
	return &a.base
}

// - current function

func (a *OfficialCommonApiAccount) Objects() []*OfficialCommonApiAccount {
	if a.objects == nil {
		return nil
	}
	return a.objects[:]
}

func (a *OfficialCommonApiAccount) XObjects() Slice_OfficialCommonApiAccount {
	return Slice_OfficialCommonApiAccount(a.Objects())
}

func (a *OfficialCommonApiAccount) NewObjects() factory.Ranger {
	return &Slice_OfficialCommonApiAccount{}
}

func (a *OfficialCommonApiAccount) InitObjects() *[]*OfficialCommonApiAccount {
	a.objects = []*OfficialCommonApiAccount{}
	return &a.objects
}

func (a *OfficialCommonApiAccount) NewParam() *factory.Param {
	return factory.NewParam(factory.DefaultFactory).SetIndex(a.base.ConnID()).SetTrans(a.base.Trans()).SetCollection(a.Name_()).SetModel(a)
}

func (a *OfficialCommonApiAccount) Short_() string {
	return "official_common_api_account"
}

func (a *OfficialCommonApiAccount) Struct_() string {
	return "OfficialCommonApiAccount"
}

func (a *OfficialCommonApiAccount) Name_() string {
	b := a
	if b == nil {
		b = &OfficialCommonApiAccount{}
	}
	if b.base.Namer() != nil {
		return WithPrefix(b.base.Namer()(b))
	}
	return WithPrefix(factory.TableNamerGet(b.Short_())(b))
}

func (a *OfficialCommonApiAccount) CPAFrom(source factory.Model) factory.Model {
	a.SetContext(source.Context())
	a.SetConnID(source.ConnID())
	a.SetNamer(source.Namer())
	return a
}

func (a *OfficialCommonApiAccount) Get(mw func(db.Result) db.Result, args ...interface{}) (err error) {
	base := a.base
	if !a.base.Eventable() {
		err = a.Param(mw, args...).SetRecv(a).One()
		a.base = base
		return
	}
	queryParam := a.Param(mw, args...).SetRecv(a)
	if err = DBI.FireReading(a, queryParam); err != nil {
		return
	}
	err = queryParam.One()
	a.base = base
	if err == nil {
		err = DBI.FireReaded(a, queryParam)
	}
	return
}

func (a *OfficialCommonApiAccount) List(recv interface{}, mw func(db.Result) db.Result, page, size int, args ...interface{}) (func() int64, error) {
	if recv == nil {
		recv = a.InitObjects()
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetPage(page).SetSize(size).SetRecv(recv).List()
	}
	queryParam := a.Param(mw, args...).SetPage(page).SetSize(size).SetRecv(recv)
	if err := DBI.FireReading(a, queryParam); err != nil {
		return nil, err
	}
	cnt, err := queryParam.List()
	if err == nil {
		switch v := recv.(type) {
		case *[]*OfficialCommonApiAccount:
			err = DBI.FireReaded(a, queryParam, Slice_OfficialCommonApiAccount(*v))
		case []*OfficialCommonApiAccount:
			err = DBI.FireReaded(a, queryParam, Slice_OfficialCommonApiAccount(v))
		case factory.Ranger:
			err = DBI.FireReaded(a, queryParam, v)
		}
	}
	return cnt, err
}

func (a *OfficialCommonApiAccount) GroupBy(keyField string, inputRows ...[]*OfficialCommonApiAccount) map[string][]*OfficialCommonApiAccount {
	var rows Slice_OfficialCommonApiAccount
	if len(inputRows) > 0 {
		rows = Slice_OfficialCommonApiAccount(inputRows[0])
	} else {
		rows = Slice_OfficialCommonApiAccount(a.Objects())
	}
	return rows.GroupBy(keyField)
}

func (a *OfficialCommonApiAccount) KeyBy(keyField string, inputRows ...[]*OfficialCommonApiAccount) map[string]*OfficialCommonApiAccount {
	var rows Slice_OfficialCommonApiAccount
	if len(inputRows) > 0 {
		rows = Slice_OfficialCommonApiAccount(inputRows[0])
	} else {
		rows = Slice_OfficialCommonApiAccount(a.Objects())
	}
	return rows.KeyBy(keyField)
}

func (a *OfficialCommonApiAccount) AsKV(keyField string, valueField string, inputRows ...[]*OfficialCommonApiAccount) param.Store {
	var rows Slice_OfficialCommonApiAccount
	if len(inputRows) > 0 {
		rows = Slice_OfficialCommonApiAccount(inputRows[0])
	} else {
		rows = Slice_OfficialCommonApiAccount(a.Objects())
	}
	return rows.AsKV(keyField, valueField)
}

func (a *OfficialCommonApiAccount) ListByOffset(recv interface{}, mw func(db.Result) db.Result, offset, size int, args ...interface{}) (func() int64, error) {
	if recv == nil {
		recv = a.InitObjects()
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetOffset(offset).SetSize(size).SetRecv(recv).List()
	}
	queryParam := a.Param(mw, args...).SetOffset(offset).SetSize(size).SetRecv(recv)
	if err := DBI.FireReading(a, queryParam); err != nil {
		return nil, err
	}
	cnt, err := queryParam.List()
	if err == nil {
		switch v := recv.(type) {
		case *[]*OfficialCommonApiAccount:
			err = DBI.FireReaded(a, queryParam, Slice_OfficialCommonApiAccount(*v))
		case []*OfficialCommonApiAccount:
			err = DBI.FireReaded(a, queryParam, Slice_OfficialCommonApiAccount(v))
		case factory.Ranger:
			err = DBI.FireReaded(a, queryParam, v)
		}
	}
	return cnt, err
}

func (a *OfficialCommonApiAccount) Insert() (pk interface{}, err error) {
	a.Created = uint(time.Now().Unix())
	a.Id = 0
	if len(a.OwnerType) == 0 {
		a.OwnerType = "user"
	}
	if len(a.Disabled) == 0 {
		a.Disabled = "N"
	}
	if a.base.Eventable() {
		err = DBI.Fire("creating", a, nil)
		if err != nil {
			return
		}
	}
	pk, err = a.Param(nil).SetSend(a).Insert()
	if err == nil && pk != nil {
		if v, y := pk.(uint64); y {
			a.Id = v
		} else if v, y := pk.(int64); y {
			a.Id = uint64(v)
		}
	}
	if err == nil && a.base.Eventable() {
		err = DBI.Fire("created", a, nil)
	}
	return
}

func (a *OfficialCommonApiAccount) Update(mw func(db.Result) db.Result, args ...interface{}) (err error) {
	a.Updated = uint(time.Now().Unix())
	if len(a.OwnerType) == 0 {
		a.OwnerType = "user"
	}
	if len(a.Disabled) == 0 {
		a.Disabled = "N"
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(a).Update()
	}
	if err = DBI.Fire("updating", a, mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).SetSend(a).Update(); err != nil {
		return
	}
	return DBI.Fire("updated", a, mw, args...)
}

func (a *OfficialCommonApiAccount) Updatex(mw func(db.Result) db.Result, args ...interface{}) (affected int64, err error) {
	a.Updated = uint(time.Now().Unix())
	if len(a.OwnerType) == 0 {
		a.OwnerType = "user"
	}
	if len(a.Disabled) == 0 {
		a.Disabled = "N"
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(a).Updatex()
	}
	if err = DBI.Fire("updating", a, mw, args...); err != nil {
		return
	}
	if affected, err = a.Param(mw, args...).SetSend(a).Updatex(); err != nil {
		return
	}
	err = DBI.Fire("updated", a, mw, args...)
	return
}

func (a *OfficialCommonApiAccount) UpdateByFields(mw func(db.Result) db.Result, fields []string, args ...interface{}) (err error) {
	a.Updated = uint(time.Now().Unix())
	if len(a.OwnerType) == 0 {
		a.OwnerType = "user"
	}
	if len(a.Disabled) == 0 {
		a.Disabled = "N"
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).UpdateByStruct(a, fields...)
	}
	editColumns := make([]string, len(fields))
	for index, field := range fields {
		editColumns[index] = com.SnakeCase(field)
	}
	if err = DBI.FireUpdate("updating", a, editColumns, mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).UpdateByStruct(a, fields...); err != nil {
		return
	}
	err = DBI.FireUpdate("updated", a, editColumns, mw, args...)
	return
}

func (a *OfficialCommonApiAccount) UpdatexByFields(mw func(db.Result) db.Result, fields []string, args ...interface{}) (affected int64, err error) {
	a.Updated = uint(time.Now().Unix())
	if len(a.OwnerType) == 0 {
		a.OwnerType = "user"
	}
	if len(a.Disabled) == 0 {
		a.Disabled = "N"
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).UpdatexByStruct(a, fields...)
	}
	editColumns := make([]string, len(fields))
	for index, field := range fields {
		editColumns[index] = com.SnakeCase(field)
	}
	if err = DBI.FireUpdate("updating", a, editColumns, mw, args...); err != nil {
		return
	}
	if affected, err = a.Param(mw, args...).UpdatexByStruct(a, fields...); err != nil {
		return
	}
	err = DBI.FireUpdate("updated", a, editColumns, mw, args...)
	return
}

func (a *OfficialCommonApiAccount) UpdateField(mw func(db.Result) db.Result, field string, value interface{}, args ...interface{}) (err error) {
	return a.UpdateFields(mw, map[string]interface{}{
		field: value,
	}, args...)
}

func (a *OfficialCommonApiAccount) UpdatexField(mw func(db.Result) db.Result, field string, value interface{}, args ...interface{}) (affected int64, err error) {
	return a.UpdatexFields(mw, map[string]interface{}{
		field: value,
	}, args...)
}

func (a *OfficialCommonApiAccount) UpdateFields(mw func(db.Result) db.Result, kvset map[string]interface{}, args ...interface{}) (err error) {

	if val, ok := kvset["owner_type"]; ok && val != nil {
		if v, ok := val.(string); ok && len(v) == 0 {
			kvset["owner_type"] = "user"
		}
	}
	if val, ok := kvset["disabled"]; ok && val != nil {
		if v, ok := val.(string); ok && len(v) == 0 {
			kvset["disabled"] = "N"
		}
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(kvset).Update()
	}
	m := *a
	m.FromRow(kvset)
	var editColumns []string
	for column := range kvset {
		editColumns = append(editColumns, column)
	}
	if err = DBI.FireUpdate("updating", &m, editColumns, mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).SetSend(kvset).Update(); err != nil {
		return
	}
	return DBI.FireUpdate("updated", &m, editColumns, mw, args...)
}

func (a *OfficialCommonApiAccount) UpdatexFields(mw func(db.Result) db.Result, kvset map[string]interface{}, args ...interface{}) (affected int64, err error) {

	if val, ok := kvset["owner_type"]; ok && val != nil {
		if v, ok := val.(string); ok && len(v) == 0 {
			kvset["owner_type"] = "user"
		}
	}
	if val, ok := kvset["disabled"]; ok && val != nil {
		if v, ok := val.(string); ok && len(v) == 0 {
			kvset["disabled"] = "N"
		}
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(kvset).Updatex()
	}
	m := *a
	m.FromRow(kvset)
	var editColumns []string
	for column := range kvset {
		editColumns = append(editColumns, column)
	}
	if err = DBI.FireUpdate("updating", &m, editColumns, mw, args...); err != nil {
		return
	}
	if affected, err = a.Param(mw, args...).SetSend(kvset).Updatex(); err != nil {
		return
	}
	err = DBI.FireUpdate("updated", &m, editColumns, mw, args...)
	return
}

func (a *OfficialCommonApiAccount) UpdateValues(mw func(db.Result) db.Result, keysValues *db.KeysValues, args ...interface{}) (err error) {
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(keysValues).Update()
	}
	m := *a
	m.FromRow(keysValues.Map())
	if err = DBI.FireUpdate("updating", &m, keysValues.Keys(), mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).SetSend(keysValues).Update(); err != nil {
		return
	}
	return DBI.FireUpdate("updated", &m, keysValues.Keys(), mw, args...)
}

func (a *OfficialCommonApiAccount) Upsert(mw func(db.Result) db.Result, args ...interface{}) (pk interface{}, err error) {
	pk, err = a.Param(mw, args...).SetSend(a).Upsert(func() error {
		a.Updated = uint(time.Now().Unix())
		if len(a.OwnerType) == 0 {
			a.OwnerType = "user"
		}
		if len(a.Disabled) == 0 {
			a.Disabled = "N"
		}
		if !a.base.Eventable() {
			return nil
		}
		return DBI.Fire("updating", a, mw, args...)
	}, func() error {
		a.Created = uint(time.Now().Unix())
		a.Id = 0
		if len(a.OwnerType) == 0 {
			a.OwnerType = "user"
		}
		if len(a.Disabled) == 0 {
			a.Disabled = "N"
		}
		if !a.base.Eventable() {
			return nil
		}
		return DBI.Fire("creating", a, nil)
	})
	if err == nil && pk != nil {
		if v, y := pk.(uint64); y {
			a.Id = v
		} else if v, y := pk.(int64); y {
			a.Id = uint64(v)
		}
	}
	if err == nil && a.base.Eventable() {
		if pk == nil {
			err = DBI.Fire("updated", a, mw, args...)
		} else {
			err = DBI.Fire("created", a, nil)
		}
	}
	return
}

func (a *OfficialCommonApiAccount) Delete(mw func(db.Result) db.Result, args ...interface{}) (err error) {

	if !a.base.Eventable() {
		return a.Param(mw, args...).Delete()
	}
	if err = DBI.Fire("deleting", a, mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).Delete(); err != nil {
		return
	}
	return DBI.Fire("deleted", a, mw, args...)
}

func (a *OfficialCommonApiAccount) Deletex(mw func(db.Result) db.Result, args ...interface{}) (affected int64, err error) {

	if !a.base.Eventable() {
		return a.Param(mw, args...).Deletex()
	}
	if err = DBI.Fire("deleting", a, mw, args...); err != nil {
		return
	}
	if affected, err = a.Param(mw, args...).Deletex(); err != nil {
		return
	}
	err = DBI.Fire("deleted", a, mw, args...)
	return
}

func (a *OfficialCommonApiAccount) Count(mw func(db.Result) db.Result, args ...interface{}) (int64, error) {
	return a.Param(mw, args...).Count()
}

func (a *OfficialCommonApiAccount) Exists(mw func(db.Result) db.Result, args ...interface{}) (bool, error) {
	return a.Param(mw, args...).Exists()
}

func (a *OfficialCommonApiAccount) Reset() *OfficialCommonApiAccount {
	a.Id = 0
	a.OwnerType = ``
	a.OwnerId = 0
	a.GroupId = 0
	a.Name = ``
	a.Url = ``
	a.UrlDev = ``
	a.AppId = ``
	a.AppSecret = ``
	a.PublicKey = ``
	a.Encryption = ``
	a.Extra = ``
	a.Disabled = ``
	a.Created = 0
	a.Updated = 0
	return a
}

func (a *OfficialCommonApiAccount) AsMap(onlyFields ...string) param.Store {
	r := param.Store{}
	if len(onlyFields) == 0 {
		r["Id"] = a.Id
		r["OwnerType"] = a.OwnerType
		r["OwnerId"] = a.OwnerId
		r["GroupId"] = a.GroupId
		r["Name"] = a.Name
		r["Url"] = a.Url
		r["UrlDev"] = a.UrlDev
		r["AppId"] = a.AppId
		r["AppSecret"] = a.AppSecret
		r["PublicKey"] = a.PublicKey
		r["Encryption"] = a.Encryption
		r["Extra"] = a.Extra
		r["Disabled"] = a.Disabled
		r["Created"] = a.Created
		r["Updated"] = a.Updated
		return r
	}
	for _, field := range onlyFields {
		switch field {
		case "Id":
			r["Id"] = a.Id
		case "OwnerType":
			r["OwnerType"] = a.OwnerType
		case "OwnerId":
			r["OwnerId"] = a.OwnerId
		case "GroupId":
			r["GroupId"] = a.GroupId
		case "Name":
			r["Name"] = a.Name
		case "Url":
			r["Url"] = a.Url
		case "UrlDev":
			r["UrlDev"] = a.UrlDev
		case "AppId":
			r["AppId"] = a.AppId
		case "AppSecret":
			r["AppSecret"] = a.AppSecret
		case "PublicKey":
			r["PublicKey"] = a.PublicKey
		case "Encryption":
			r["Encryption"] = a.Encryption
		case "Extra":
			r["Extra"] = a.Extra
		case "Disabled":
			r["Disabled"] = a.Disabled
		case "Created":
			r["Created"] = a.Created
		case "Updated":
			r["Updated"] = a.Updated
		}
	}
	return r
}

func (a *OfficialCommonApiAccount) FromRow(row map[string]interface{}) {
	for key, value := range row {
		switch key {
		case "id":
			a.Id = param.AsUint64(value)
		case "owner_type":
			a.OwnerType = param.AsString(value)
		case "owner_id":
			a.OwnerId = param.AsUint64(value)
		case "group_id":
			a.GroupId = param.AsUint(value)
		case "name":
			a.Name = param.AsString(value)
		case "url":
			a.Url = param.AsString(value)
		case "url_dev":
			a.UrlDev = param.AsString(value)
		case "app_id":
			a.AppId = param.AsString(value)
		case "app_secret":
			a.AppSecret = param.AsString(value)
		case "public_key":
			a.PublicKey = param.AsString(value)
		case "encryption":
			a.Encryption = param.AsString(value)
		case "extra":
			a.Extra = param.AsString(value)
		case "disabled":
			a.Disabled = param.AsString(value)
		case "created":
			a.Created = param.AsUint(value)
		case "updated":
			a.Updated = param.AsUint(value)
		}
	}
}

func (a *OfficialCommonApiAccount) Set(key interface{}, value ...interface{}) {
	switch k := key.(type) {
	case map[string]interface{}:
		for kk, vv := range k {
			a.Set(kk, vv)
		}
	default:
		var (
			kk string
			vv interface{}
		)
		if k, y := key.(string); y {
			kk = k
		} else {
			kk = fmt.Sprint(key)
		}
		if len(value) > 0 {
			vv = value[0]
		}
		switch kk {
		case "Id":
			a.Id = param.AsUint64(vv)
		case "OwnerType":
			a.OwnerType = param.AsString(vv)
		case "OwnerId":
			a.OwnerId = param.AsUint64(vv)
		case "GroupId":
			a.GroupId = param.AsUint(vv)
		case "Name":
			a.Name = param.AsString(vv)
		case "Url":
			a.Url = param.AsString(vv)
		case "UrlDev":
			a.UrlDev = param.AsString(vv)
		case "AppId":
			a.AppId = param.AsString(vv)
		case "AppSecret":
			a.AppSecret = param.AsString(vv)
		case "PublicKey":
			a.PublicKey = param.AsString(vv)
		case "Encryption":
			a.Encryption = param.AsString(vv)
		case "Extra":
			a.Extra = param.AsString(vv)
		case "Disabled":
			a.Disabled = param.AsString(vv)
		case "Created":
			a.Created = param.AsUint(vv)
		case "Updated":
			a.Updated = param.AsUint(vv)
		}
	}
}

func (a *OfficialCommonApiAccount) AsRow(onlyFields ...string) param.Store {
	r := param.Store{}
	if len(onlyFields) == 0 {
		r["id"] = a.Id
		r["owner_type"] = a.OwnerType
		r["owner_id"] = a.OwnerId
		r["group_id"] = a.GroupId
		r["name"] = a.Name
		r["url"] = a.Url
		r["url_dev"] = a.UrlDev
		r["app_id"] = a.AppId
		r["app_secret"] = a.AppSecret
		r["public_key"] = a.PublicKey
		r["encryption"] = a.Encryption
		r["extra"] = a.Extra
		r["disabled"] = a.Disabled
		r["created"] = a.Created
		r["updated"] = a.Updated
		return r
	}
	for _, field := range onlyFields {
		switch field {
		case "id":
			r["id"] = a.Id
		case "owner_type":
			r["owner_type"] = a.OwnerType
		case "owner_id":
			r["owner_id"] = a.OwnerId
		case "group_id":
			r["group_id"] = a.GroupId
		case "name":
			r["name"] = a.Name
		case "url":
			r["url"] = a.Url
		case "url_dev":
			r["url_dev"] = a.UrlDev
		case "app_id":
			r["app_id"] = a.AppId
		case "app_secret":
			r["app_secret"] = a.AppSecret
		case "public_key":
			r["public_key"] = a.PublicKey
		case "encryption":
			r["encryption"] = a.Encryption
		case "extra":
			r["extra"] = a.Extra
		case "disabled":
			r["disabled"] = a.Disabled
		case "created":
			r["created"] = a.Created
		case "updated":
			r["updated"] = a.Updated
		}
	}
	return r
}

func (a *OfficialCommonApiAccount) ListPage(cond *db.Compounds, sorts ...interface{}) error {
	_, err := pagination.NewLister(a, nil, func(r db.Result) db.Result {
		return r.OrderBy(sorts...)
	}, cond.And()).Paging(a.Context())
	return err
}

func (a *OfficialCommonApiAccount) ListPageAs(recv interface{}, cond *db.Compounds, sorts ...interface{}) error {
	_, err := pagination.NewLister(a, recv, func(r db.Result) db.Result {
		return r.OrderBy(sorts...)
	}, cond.And()).Paging(a.Context())
	return err
}

func (a *OfficialCommonApiAccount) BatchValidate(kvset map[string]interface{}) error {
	if kvset == nil {
		kvset = a.AsRow()
	}
	return DBI.Fields.BatchValidate(a.Short_(), kvset)
}

func (a *OfficialCommonApiAccount) Validate(field string, value interface{}) error {
	return DBI.Fields.Validate(a.Short_(), field, value)
}
