// @generated Do not edit this file, which is automatically generated by the generator.

package dbschema

import (
	"fmt"

	"time"

	"github.com/webx-top/com"
	"github.com/webx-top/db"
	"github.com/webx-top/db/lib/factory"
	"github.com/webx-top/db/lib/factory/pagination"
	"github.com/webx-top/echo"
	"github.com/webx-top/echo/param"
)

type Slice_OfficialCustomerAgentLevel []*OfficialCustomerAgentLevel

func (s Slice_OfficialCustomerAgentLevel) Range(fn func(m factory.Model) error) error {
	for _, v := range s {
		if err := fn(v); err != nil {
			return err
		}
	}
	return nil
}

func (s Slice_OfficialCustomerAgentLevel) RangeRaw(fn func(m *OfficialCustomerAgentLevel) error) error {
	for _, v := range s {
		if err := fn(v); err != nil {
			return err
		}
	}
	return nil
}

func (s Slice_OfficialCustomerAgentLevel) GroupBy(keyField string) map[string][]*OfficialCustomerAgentLevel {
	r := map[string][]*OfficialCustomerAgentLevel{}
	for _, row := range s {
		dmap := row.AsMap()
		vkey := fmt.Sprint(dmap[keyField])
		if _, y := r[vkey]; !y {
			r[vkey] = []*OfficialCustomerAgentLevel{}
		}
		r[vkey] = append(r[vkey], row)
	}
	return r
}

func (s Slice_OfficialCustomerAgentLevel) KeyBy(keyField string) map[string]*OfficialCustomerAgentLevel {
	r := map[string]*OfficialCustomerAgentLevel{}
	for _, row := range s {
		dmap := row.AsMap()
		vkey := fmt.Sprint(dmap[keyField])
		r[vkey] = row
	}
	return r
}

func (s Slice_OfficialCustomerAgentLevel) AsKV(keyField string, valueField string) param.Store {
	r := param.Store{}
	for _, row := range s {
		dmap := row.AsMap()
		vkey := fmt.Sprint(dmap[keyField])
		r[vkey] = dmap[valueField]
	}
	return r
}

func (s Slice_OfficialCustomerAgentLevel) Transform(transfers map[string]param.Transfer) []param.Store {
	r := make([]param.Store, len(s))
	for idx, row := range s {
		r[idx] = row.AsMap().Transform(transfers)
	}
	return r
}

func (s Slice_OfficialCustomerAgentLevel) FromList(data interface{}) Slice_OfficialCustomerAgentLevel {
	values, ok := data.([]*OfficialCustomerAgentLevel)
	if !ok {
		for _, value := range data.([]interface{}) {
			row := &OfficialCustomerAgentLevel{}
			row.FromRow(value.(map[string]interface{}))
			s = append(s, row)
		}
		return s
	}
	s = append(s, values...)

	return s
}

func NewOfficialCustomerAgentLevel(ctx echo.Context) *OfficialCustomerAgentLevel {
	m := &OfficialCustomerAgentLevel{}
	m.SetContext(ctx)
	return m
}

// OfficialCustomerAgentLevel 代理等级
type OfficialCustomerAgentLevel struct {
	base    factory.Base
	objects []*OfficialCustomerAgentLevel

	Id                     uint    `db:"id,omitempty,pk" bson:"id,omitempty" comment:"ID" json:"id" xml:"id"`
	Name                   string  `db:"name" bson:"name" comment:"等级名称" json:"name" xml:"name"`
	Description            string  `db:"description" bson:"description" comment:"等级说明" json:"description" xml:"description"`
	AgencyFee              float64 `db:"agency_fee" bson:"agency_fee" comment:"代理费" json:"agency_fee" xml:"agency_fee"`
	AgencyFeeRebateRatio   float64 `db:"agency_fee_rebate_ratio" bson:"agency_fee_rebate_ratio" comment:"下级代理费回扣比例" json:"agency_fee_rebate_ratio" xml:"agency_fee_rebate_ratio"`
	SalesCommissionRatio1  float64 `db:"sales_commission_ratio_1" bson:"sales_commission_ratio_1" comment:"销售提成比例(1级下线)" json:"sales_commission_ratio_1" xml:"sales_commission_ratio_1"`
	SalesCommissionRatio2  float64 `db:"sales_commission_ratio_2" bson:"sales_commission_ratio_2" comment:"销售提成比例(2级下线)" json:"sales_commission_ratio_2" xml:"sales_commission_ratio_2"`
	SalesCommissionRatio3  float64 `db:"sales_commission_ratio_3" bson:"sales_commission_ratio_3" comment:"销售提成比例(3级下线)" json:"sales_commission_ratio_3" xml:"sales_commission_ratio_3"`
	SalesCommissionRatio4  float64 `db:"sales_commission_ratio_4" bson:"sales_commission_ratio_4" comment:"销售提成比例(4级下线)" json:"sales_commission_ratio_4" xml:"sales_commission_ratio_4"`
	SalesCommissionRatio5  float64 `db:"sales_commission_ratio_5" bson:"sales_commission_ratio_5" comment:"销售提成比例(5级下线)" json:"sales_commission_ratio_5" xml:"sales_commission_ratio_5"`
	SalesCommissionRatio6  float64 `db:"sales_commission_ratio_6" bson:"sales_commission_ratio_6" comment:"销售提成比例(6级下线)" json:"sales_commission_ratio_6" xml:"sales_commission_ratio_6"`
	SalesCommissionRatio7  float64 `db:"sales_commission_ratio_7" bson:"sales_commission_ratio_7" comment:"销售提成比例(7级下线)" json:"sales_commission_ratio_7" xml:"sales_commission_ratio_7"`
	SalesCommissionRatio8  float64 `db:"sales_commission_ratio_8" bson:"sales_commission_ratio_8" comment:"销售提成比例(8级下线)" json:"sales_commission_ratio_8" xml:"sales_commission_ratio_8"`
	SalesCommissionRatio9  float64 `db:"sales_commission_ratio_9" bson:"sales_commission_ratio_9" comment:"销售提成比例(9级下线)" json:"sales_commission_ratio_9" xml:"sales_commission_ratio_9"`
	SalesCommissionRatio10 float64 `db:"sales_commission_ratio_10" bson:"sales_commission_ratio_10" comment:"销售提成比例(10级下线)" json:"sales_commission_ratio_10" xml:"sales_commission_ratio_10"`
	Created                uint    `db:"created" bson:"created" comment:"创建时间" json:"created" xml:"created"`
	Updated                uint    `db:"updated" bson:"updated" comment:"修改时间" json:"updated" xml:"updated"`
	Disabled               string  `db:"disabled" bson:"disabled" comment:"是否(Y/N)禁用" json:"disabled" xml:"disabled"`
	RoleIds                string  `db:"role_ids" bson:"role_ids" comment:"角色ID(多个用“,”分隔开)" json:"role_ids" xml:"role_ids"`
}

// - base function

func (a *OfficialCustomerAgentLevel) Trans() factory.Transactioner {
	return a.base.Trans()
}

func (a *OfficialCustomerAgentLevel) Use(trans factory.Transactioner) factory.Model {
	a.base.Use(trans)
	return a
}

func (a *OfficialCustomerAgentLevel) SetContext(ctx echo.Context) factory.Model {
	a.base.SetContext(ctx)
	return a
}

func (a *OfficialCustomerAgentLevel) EventON(on ...bool) factory.Model {
	a.base.EventON(on...)
	return a
}

func (a *OfficialCustomerAgentLevel) EventOFF(off ...bool) factory.Model {
	a.base.EventOFF(off...)
	return a
}

func (a *OfficialCustomerAgentLevel) Context() echo.Context {
	return a.base.Context()
}

func (a *OfficialCustomerAgentLevel) SetConnID(connID int) factory.Model {
	a.base.SetConnID(connID)
	return a
}

func (a *OfficialCustomerAgentLevel) ConnID() int {
	return a.base.ConnID()
}

func (a *OfficialCustomerAgentLevel) SetNamer(namer func(factory.Model) string) factory.Model {
	a.base.SetNamer(namer)
	return a
}

func (a *OfficialCustomerAgentLevel) Namer() func(factory.Model) string {
	return a.base.Namer()
}

func (a *OfficialCustomerAgentLevel) SetParam(param *factory.Param) factory.Model {
	a.base.SetParam(param)
	return a
}

func (a *OfficialCustomerAgentLevel) Param(mw func(db.Result) db.Result, args ...interface{}) *factory.Param {
	if a.base.Param() == nil {
		return a.NewParam().SetMiddleware(mw).SetArgs(args...)
	}
	return a.base.Param().SetMiddleware(mw).SetArgs(args...)
}

func (a *OfficialCustomerAgentLevel) New(structName string, connID ...int) factory.Model {
	return a.base.New(structName, connID...)
}

func (a *OfficialCustomerAgentLevel) Base_() factory.Baser {
	return &a.base
}

// - current function

func (a *OfficialCustomerAgentLevel) Objects() []*OfficialCustomerAgentLevel {
	if a.objects == nil {
		return nil
	}
	return a.objects[:]
}

func (a *OfficialCustomerAgentLevel) XObjects() Slice_OfficialCustomerAgentLevel {
	return Slice_OfficialCustomerAgentLevel(a.Objects())
}

func (a *OfficialCustomerAgentLevel) NewObjects() factory.Ranger {
	return &Slice_OfficialCustomerAgentLevel{}
}

func (a *OfficialCustomerAgentLevel) InitObjects() *[]*OfficialCustomerAgentLevel {
	a.objects = []*OfficialCustomerAgentLevel{}
	return &a.objects
}

func (a *OfficialCustomerAgentLevel) NewParam() *factory.Param {
	return factory.NewParam(factory.DefaultFactory).SetIndex(a.base.ConnID()).SetTrans(a.base.Trans()).SetCollection(a.Name_()).SetModel(a)
}

func (a *OfficialCustomerAgentLevel) Short_() string {
	return "official_customer_agent_level"
}

func (a *OfficialCustomerAgentLevel) Struct_() string {
	return "OfficialCustomerAgentLevel"
}

func (a *OfficialCustomerAgentLevel) Name_() string {
	b := a
	if b == nil {
		b = &OfficialCustomerAgentLevel{}
	}
	if b.base.Namer() != nil {
		return WithPrefix(b.base.Namer()(b))
	}
	return WithPrefix(factory.TableNamerGet(b.Short_())(b))
}

func (a *OfficialCustomerAgentLevel) CPAFrom(source factory.Model) factory.Model {
	a.SetContext(source.Context())
	a.SetConnID(source.ConnID())
	a.SetNamer(source.Namer())
	return a
}

func (a *OfficialCustomerAgentLevel) Get(mw func(db.Result) db.Result, args ...interface{}) (err error) {
	base := a.base
	if !a.base.Eventable() {
		err = a.Param(mw, args...).SetRecv(a).One()
		a.base = base
		return
	}
	queryParam := a.Param(mw, args...).SetRecv(a)
	if err = DBI.FireReading(a, queryParam); err != nil {
		return
	}
	err = queryParam.One()
	a.base = base
	if err == nil {
		err = DBI.FireReaded(a, queryParam)
	}
	return
}

func (a *OfficialCustomerAgentLevel) List(recv interface{}, mw func(db.Result) db.Result, page, size int, args ...interface{}) (func() int64, error) {
	if recv == nil {
		recv = a.InitObjects()
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetPage(page).SetSize(size).SetRecv(recv).List()
	}
	queryParam := a.Param(mw, args...).SetPage(page).SetSize(size).SetRecv(recv)
	if err := DBI.FireReading(a, queryParam); err != nil {
		return nil, err
	}
	cnt, err := queryParam.List()
	if err == nil {
		switch v := recv.(type) {
		case *[]*OfficialCustomerAgentLevel:
			err = DBI.FireReaded(a, queryParam, Slice_OfficialCustomerAgentLevel(*v))
		case []*OfficialCustomerAgentLevel:
			err = DBI.FireReaded(a, queryParam, Slice_OfficialCustomerAgentLevel(v))
		case factory.Ranger:
			err = DBI.FireReaded(a, queryParam, v)
		}
	}
	return cnt, err
}

func (a *OfficialCustomerAgentLevel) GroupBy(keyField string, inputRows ...[]*OfficialCustomerAgentLevel) map[string][]*OfficialCustomerAgentLevel {
	var rows Slice_OfficialCustomerAgentLevel
	if len(inputRows) > 0 {
		rows = Slice_OfficialCustomerAgentLevel(inputRows[0])
	} else {
		rows = Slice_OfficialCustomerAgentLevel(a.Objects())
	}
	return rows.GroupBy(keyField)
}

func (a *OfficialCustomerAgentLevel) KeyBy(keyField string, inputRows ...[]*OfficialCustomerAgentLevel) map[string]*OfficialCustomerAgentLevel {
	var rows Slice_OfficialCustomerAgentLevel
	if len(inputRows) > 0 {
		rows = Slice_OfficialCustomerAgentLevel(inputRows[0])
	} else {
		rows = Slice_OfficialCustomerAgentLevel(a.Objects())
	}
	return rows.KeyBy(keyField)
}

func (a *OfficialCustomerAgentLevel) AsKV(keyField string, valueField string, inputRows ...[]*OfficialCustomerAgentLevel) param.Store {
	var rows Slice_OfficialCustomerAgentLevel
	if len(inputRows) > 0 {
		rows = Slice_OfficialCustomerAgentLevel(inputRows[0])
	} else {
		rows = Slice_OfficialCustomerAgentLevel(a.Objects())
	}
	return rows.AsKV(keyField, valueField)
}

func (a *OfficialCustomerAgentLevel) ListByOffset(recv interface{}, mw func(db.Result) db.Result, offset, size int, args ...interface{}) (func() int64, error) {
	if recv == nil {
		recv = a.InitObjects()
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetOffset(offset).SetSize(size).SetRecv(recv).List()
	}
	queryParam := a.Param(mw, args...).SetOffset(offset).SetSize(size).SetRecv(recv)
	if err := DBI.FireReading(a, queryParam); err != nil {
		return nil, err
	}
	cnt, err := queryParam.List()
	if err == nil {
		switch v := recv.(type) {
		case *[]*OfficialCustomerAgentLevel:
			err = DBI.FireReaded(a, queryParam, Slice_OfficialCustomerAgentLevel(*v))
		case []*OfficialCustomerAgentLevel:
			err = DBI.FireReaded(a, queryParam, Slice_OfficialCustomerAgentLevel(v))
		case factory.Ranger:
			err = DBI.FireReaded(a, queryParam, v)
		}
	}
	return cnt, err
}

func (a *OfficialCustomerAgentLevel) Insert() (pk interface{}, err error) {
	a.Created = uint(time.Now().Unix())
	a.Id = 0
	if len(a.Disabled) == 0 {
		a.Disabled = "N"
	}
	if a.base.Eventable() {
		err = DBI.Fire("creating", a, nil)
		if err != nil {
			return
		}
	}
	pk, err = a.Param(nil).SetSend(a).Insert()
	if err == nil && pk != nil {
		if v, y := pk.(uint); y {
			a.Id = v
		} else if v, y := pk.(int64); y {
			a.Id = uint(v)
		}
	}
	if err == nil && a.base.Eventable() {
		err = DBI.Fire("created", a, nil)
	}
	return
}

func (a *OfficialCustomerAgentLevel) Update(mw func(db.Result) db.Result, args ...interface{}) (err error) {
	a.Updated = uint(time.Now().Unix())
	if len(a.Disabled) == 0 {
		a.Disabled = "N"
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(a).Update()
	}
	if err = DBI.Fire("updating", a, mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).SetSend(a).Update(); err != nil {
		return
	}
	return DBI.Fire("updated", a, mw, args...)
}

func (a *OfficialCustomerAgentLevel) Updatex(mw func(db.Result) db.Result, args ...interface{}) (affected int64, err error) {
	a.Updated = uint(time.Now().Unix())
	if len(a.Disabled) == 0 {
		a.Disabled = "N"
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(a).Updatex()
	}
	if err = DBI.Fire("updating", a, mw, args...); err != nil {
		return
	}
	if affected, err = a.Param(mw, args...).SetSend(a).Updatex(); err != nil {
		return
	}
	err = DBI.Fire("updated", a, mw, args...)
	return
}

func (a *OfficialCustomerAgentLevel) UpdateByFields(mw func(db.Result) db.Result, fields []string, args ...interface{}) (err error) {
	a.Updated = uint(time.Now().Unix())
	if len(a.Disabled) == 0 {
		a.Disabled = "N"
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).UpdateByStruct(a, fields...)
	}
	editColumns := make([]string, len(fields))
	for index, field := range fields {
		editColumns[index] = com.SnakeCase(field)
	}
	if err = DBI.FireUpdate("updating", a, editColumns, mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).UpdateByStruct(a, fields...); err != nil {
		return
	}
	err = DBI.FireUpdate("updated", a, editColumns, mw, args...)
	return
}

func (a *OfficialCustomerAgentLevel) UpdatexByFields(mw func(db.Result) db.Result, fields []string, args ...interface{}) (affected int64, err error) {
	a.Updated = uint(time.Now().Unix())
	if len(a.Disabled) == 0 {
		a.Disabled = "N"
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).UpdatexByStruct(a, fields...)
	}
	editColumns := make([]string, len(fields))
	for index, field := range fields {
		editColumns[index] = com.SnakeCase(field)
	}
	if err = DBI.FireUpdate("updating", a, editColumns, mw, args...); err != nil {
		return
	}
	if affected, err = a.Param(mw, args...).UpdatexByStruct(a, fields...); err != nil {
		return
	}
	err = DBI.FireUpdate("updated", a, editColumns, mw, args...)
	return
}

func (a *OfficialCustomerAgentLevel) UpdateField(mw func(db.Result) db.Result, field string, value interface{}, args ...interface{}) (err error) {
	return a.UpdateFields(mw, map[string]interface{}{
		field: value,
	}, args...)
}

func (a *OfficialCustomerAgentLevel) UpdatexField(mw func(db.Result) db.Result, field string, value interface{}, args ...interface{}) (affected int64, err error) {
	return a.UpdatexFields(mw, map[string]interface{}{
		field: value,
	}, args...)
}

func (a *OfficialCustomerAgentLevel) UpdateFields(mw func(db.Result) db.Result, kvset map[string]interface{}, args ...interface{}) (err error) {

	if val, ok := kvset["disabled"]; ok && val != nil {
		if v, ok := val.(string); ok && len(v) == 0 {
			kvset["disabled"] = "N"
		}
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(kvset).Update()
	}
	m := *a
	m.FromRow(kvset)
	var editColumns []string
	for column := range kvset {
		editColumns = append(editColumns, column)
	}
	if err = DBI.FireUpdate("updating", &m, editColumns, mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).SetSend(kvset).Update(); err != nil {
		return
	}
	return DBI.FireUpdate("updated", &m, editColumns, mw, args...)
}

func (a *OfficialCustomerAgentLevel) UpdatexFields(mw func(db.Result) db.Result, kvset map[string]interface{}, args ...interface{}) (affected int64, err error) {

	if val, ok := kvset["disabled"]; ok && val != nil {
		if v, ok := val.(string); ok && len(v) == 0 {
			kvset["disabled"] = "N"
		}
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(kvset).Updatex()
	}
	m := *a
	m.FromRow(kvset)
	var editColumns []string
	for column := range kvset {
		editColumns = append(editColumns, column)
	}
	if err = DBI.FireUpdate("updating", &m, editColumns, mw, args...); err != nil {
		return
	}
	if affected, err = a.Param(mw, args...).SetSend(kvset).Updatex(); err != nil {
		return
	}
	err = DBI.FireUpdate("updated", &m, editColumns, mw, args...)
	return
}

func (a *OfficialCustomerAgentLevel) UpdateValues(mw func(db.Result) db.Result, keysValues *db.KeysValues, args ...interface{}) (err error) {
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(keysValues).Update()
	}
	m := *a
	m.FromRow(keysValues.Map())
	if err = DBI.FireUpdate("updating", &m, keysValues.Keys(), mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).SetSend(keysValues).Update(); err != nil {
		return
	}
	return DBI.FireUpdate("updated", &m, keysValues.Keys(), mw, args...)
}

func (a *OfficialCustomerAgentLevel) Upsert(mw func(db.Result) db.Result, args ...interface{}) (pk interface{}, err error) {
	pk, err = a.Param(mw, args...).SetSend(a).Upsert(func() error {
		a.Updated = uint(time.Now().Unix())
		if len(a.Disabled) == 0 {
			a.Disabled = "N"
		}
		if !a.base.Eventable() {
			return nil
		}
		return DBI.Fire("updating", a, mw, args...)
	}, func() error {
		a.Created = uint(time.Now().Unix())
		a.Id = 0
		if len(a.Disabled) == 0 {
			a.Disabled = "N"
		}
		if !a.base.Eventable() {
			return nil
		}
		return DBI.Fire("creating", a, nil)
	})
	if err == nil && pk != nil {
		if v, y := pk.(uint); y {
			a.Id = v
		} else if v, y := pk.(int64); y {
			a.Id = uint(v)
		}
	}
	if err == nil && a.base.Eventable() {
		if pk == nil {
			err = DBI.Fire("updated", a, mw, args...)
		} else {
			err = DBI.Fire("created", a, nil)
		}
	}
	return
}

func (a *OfficialCustomerAgentLevel) Delete(mw func(db.Result) db.Result, args ...interface{}) (err error) {

	if !a.base.Eventable() {
		return a.Param(mw, args...).Delete()
	}
	if err = DBI.Fire("deleting", a, mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).Delete(); err != nil {
		return
	}
	return DBI.Fire("deleted", a, mw, args...)
}

func (a *OfficialCustomerAgentLevel) Deletex(mw func(db.Result) db.Result, args ...interface{}) (affected int64, err error) {

	if !a.base.Eventable() {
		return a.Param(mw, args...).Deletex()
	}
	if err = DBI.Fire("deleting", a, mw, args...); err != nil {
		return
	}
	if affected, err = a.Param(mw, args...).Deletex(); err != nil {
		return
	}
	err = DBI.Fire("deleted", a, mw, args...)
	return
}

func (a *OfficialCustomerAgentLevel) Count(mw func(db.Result) db.Result, args ...interface{}) (int64, error) {
	return a.Param(mw, args...).Count()
}

func (a *OfficialCustomerAgentLevel) Exists(mw func(db.Result) db.Result, args ...interface{}) (bool, error) {
	return a.Param(mw, args...).Exists()
}

func (a *OfficialCustomerAgentLevel) Reset() *OfficialCustomerAgentLevel {
	a.Id = 0
	a.Name = ``
	a.Description = ``
	a.AgencyFee = 0.0
	a.AgencyFeeRebateRatio = 0.0
	a.SalesCommissionRatio1 = 0.0
	a.SalesCommissionRatio2 = 0.0
	a.SalesCommissionRatio3 = 0.0
	a.SalesCommissionRatio4 = 0.0
	a.SalesCommissionRatio5 = 0.0
	a.SalesCommissionRatio6 = 0.0
	a.SalesCommissionRatio7 = 0.0
	a.SalesCommissionRatio8 = 0.0
	a.SalesCommissionRatio9 = 0.0
	a.SalesCommissionRatio10 = 0.0
	a.Created = 0
	a.Updated = 0
	a.Disabled = ``
	a.RoleIds = ``
	return a
}

func (a *OfficialCustomerAgentLevel) AsMap(onlyFields ...string) param.Store {
	r := param.Store{}
	if len(onlyFields) == 0 {
		r["Id"] = a.Id
		r["Name"] = a.Name
		r["Description"] = a.Description
		r["AgencyFee"] = a.AgencyFee
		r["AgencyFeeRebateRatio"] = a.AgencyFeeRebateRatio
		r["SalesCommissionRatio1"] = a.SalesCommissionRatio1
		r["SalesCommissionRatio2"] = a.SalesCommissionRatio2
		r["SalesCommissionRatio3"] = a.SalesCommissionRatio3
		r["SalesCommissionRatio4"] = a.SalesCommissionRatio4
		r["SalesCommissionRatio5"] = a.SalesCommissionRatio5
		r["SalesCommissionRatio6"] = a.SalesCommissionRatio6
		r["SalesCommissionRatio7"] = a.SalesCommissionRatio7
		r["SalesCommissionRatio8"] = a.SalesCommissionRatio8
		r["SalesCommissionRatio9"] = a.SalesCommissionRatio9
		r["SalesCommissionRatio10"] = a.SalesCommissionRatio10
		r["Created"] = a.Created
		r["Updated"] = a.Updated
		r["Disabled"] = a.Disabled
		r["RoleIds"] = a.RoleIds
		return r
	}
	for _, field := range onlyFields {
		switch field {
		case "Id":
			r["Id"] = a.Id
		case "Name":
			r["Name"] = a.Name
		case "Description":
			r["Description"] = a.Description
		case "AgencyFee":
			r["AgencyFee"] = a.AgencyFee
		case "AgencyFeeRebateRatio":
			r["AgencyFeeRebateRatio"] = a.AgencyFeeRebateRatio
		case "SalesCommissionRatio1":
			r["SalesCommissionRatio1"] = a.SalesCommissionRatio1
		case "SalesCommissionRatio2":
			r["SalesCommissionRatio2"] = a.SalesCommissionRatio2
		case "SalesCommissionRatio3":
			r["SalesCommissionRatio3"] = a.SalesCommissionRatio3
		case "SalesCommissionRatio4":
			r["SalesCommissionRatio4"] = a.SalesCommissionRatio4
		case "SalesCommissionRatio5":
			r["SalesCommissionRatio5"] = a.SalesCommissionRatio5
		case "SalesCommissionRatio6":
			r["SalesCommissionRatio6"] = a.SalesCommissionRatio6
		case "SalesCommissionRatio7":
			r["SalesCommissionRatio7"] = a.SalesCommissionRatio7
		case "SalesCommissionRatio8":
			r["SalesCommissionRatio8"] = a.SalesCommissionRatio8
		case "SalesCommissionRatio9":
			r["SalesCommissionRatio9"] = a.SalesCommissionRatio9
		case "SalesCommissionRatio10":
			r["SalesCommissionRatio10"] = a.SalesCommissionRatio10
		case "Created":
			r["Created"] = a.Created
		case "Updated":
			r["Updated"] = a.Updated
		case "Disabled":
			r["Disabled"] = a.Disabled
		case "RoleIds":
			r["RoleIds"] = a.RoleIds
		}
	}
	return r
}

func (a *OfficialCustomerAgentLevel) FromRow(row map[string]interface{}) {
	for key, value := range row {
		switch key {
		case "id":
			a.Id = param.AsUint(value)
		case "name":
			a.Name = param.AsString(value)
		case "description":
			a.Description = param.AsString(value)
		case "agency_fee":
			a.AgencyFee = param.AsFloat64(value)
		case "agency_fee_rebate_ratio":
			a.AgencyFeeRebateRatio = param.AsFloat64(value)
		case "sales_commission_ratio_1":
			a.SalesCommissionRatio1 = param.AsFloat64(value)
		case "sales_commission_ratio_2":
			a.SalesCommissionRatio2 = param.AsFloat64(value)
		case "sales_commission_ratio_3":
			a.SalesCommissionRatio3 = param.AsFloat64(value)
		case "sales_commission_ratio_4":
			a.SalesCommissionRatio4 = param.AsFloat64(value)
		case "sales_commission_ratio_5":
			a.SalesCommissionRatio5 = param.AsFloat64(value)
		case "sales_commission_ratio_6":
			a.SalesCommissionRatio6 = param.AsFloat64(value)
		case "sales_commission_ratio_7":
			a.SalesCommissionRatio7 = param.AsFloat64(value)
		case "sales_commission_ratio_8":
			a.SalesCommissionRatio8 = param.AsFloat64(value)
		case "sales_commission_ratio_9":
			a.SalesCommissionRatio9 = param.AsFloat64(value)
		case "sales_commission_ratio_10":
			a.SalesCommissionRatio10 = param.AsFloat64(value)
		case "created":
			a.Created = param.AsUint(value)
		case "updated":
			a.Updated = param.AsUint(value)
		case "disabled":
			a.Disabled = param.AsString(value)
		case "role_ids":
			a.RoleIds = param.AsString(value)
		}
	}
}

func (a *OfficialCustomerAgentLevel) Set(key interface{}, value ...interface{}) {
	switch k := key.(type) {
	case map[string]interface{}:
		for kk, vv := range k {
			a.Set(kk, vv)
		}
	default:
		var (
			kk string
			vv interface{}
		)
		if k, y := key.(string); y {
			kk = k
		} else {
			kk = fmt.Sprint(key)
		}
		if len(value) > 0 {
			vv = value[0]
		}
		switch kk {
		case "Id":
			a.Id = param.AsUint(vv)
		case "Name":
			a.Name = param.AsString(vv)
		case "Description":
			a.Description = param.AsString(vv)
		case "AgencyFee":
			a.AgencyFee = param.AsFloat64(vv)
		case "AgencyFeeRebateRatio":
			a.AgencyFeeRebateRatio = param.AsFloat64(vv)
		case "SalesCommissionRatio1":
			a.SalesCommissionRatio1 = param.AsFloat64(vv)
		case "SalesCommissionRatio2":
			a.SalesCommissionRatio2 = param.AsFloat64(vv)
		case "SalesCommissionRatio3":
			a.SalesCommissionRatio3 = param.AsFloat64(vv)
		case "SalesCommissionRatio4":
			a.SalesCommissionRatio4 = param.AsFloat64(vv)
		case "SalesCommissionRatio5":
			a.SalesCommissionRatio5 = param.AsFloat64(vv)
		case "SalesCommissionRatio6":
			a.SalesCommissionRatio6 = param.AsFloat64(vv)
		case "SalesCommissionRatio7":
			a.SalesCommissionRatio7 = param.AsFloat64(vv)
		case "SalesCommissionRatio8":
			a.SalesCommissionRatio8 = param.AsFloat64(vv)
		case "SalesCommissionRatio9":
			a.SalesCommissionRatio9 = param.AsFloat64(vv)
		case "SalesCommissionRatio10":
			a.SalesCommissionRatio10 = param.AsFloat64(vv)
		case "Created":
			a.Created = param.AsUint(vv)
		case "Updated":
			a.Updated = param.AsUint(vv)
		case "Disabled":
			a.Disabled = param.AsString(vv)
		case "RoleIds":
			a.RoleIds = param.AsString(vv)
		}
	}
}

func (a *OfficialCustomerAgentLevel) AsRow(onlyFields ...string) param.Store {
	r := param.Store{}
	if len(onlyFields) == 0 {
		r["id"] = a.Id
		r["name"] = a.Name
		r["description"] = a.Description
		r["agency_fee"] = a.AgencyFee
		r["agency_fee_rebate_ratio"] = a.AgencyFeeRebateRatio
		r["sales_commission_ratio_1"] = a.SalesCommissionRatio1
		r["sales_commission_ratio_2"] = a.SalesCommissionRatio2
		r["sales_commission_ratio_3"] = a.SalesCommissionRatio3
		r["sales_commission_ratio_4"] = a.SalesCommissionRatio4
		r["sales_commission_ratio_5"] = a.SalesCommissionRatio5
		r["sales_commission_ratio_6"] = a.SalesCommissionRatio6
		r["sales_commission_ratio_7"] = a.SalesCommissionRatio7
		r["sales_commission_ratio_8"] = a.SalesCommissionRatio8
		r["sales_commission_ratio_9"] = a.SalesCommissionRatio9
		r["sales_commission_ratio_10"] = a.SalesCommissionRatio10
		r["created"] = a.Created
		r["updated"] = a.Updated
		r["disabled"] = a.Disabled
		r["role_ids"] = a.RoleIds
		return r
	}
	for _, field := range onlyFields {
		switch field {
		case "id":
			r["id"] = a.Id
		case "name":
			r["name"] = a.Name
		case "description":
			r["description"] = a.Description
		case "agency_fee":
			r["agency_fee"] = a.AgencyFee
		case "agency_fee_rebate_ratio":
			r["agency_fee_rebate_ratio"] = a.AgencyFeeRebateRatio
		case "sales_commission_ratio_1":
			r["sales_commission_ratio_1"] = a.SalesCommissionRatio1
		case "sales_commission_ratio_2":
			r["sales_commission_ratio_2"] = a.SalesCommissionRatio2
		case "sales_commission_ratio_3":
			r["sales_commission_ratio_3"] = a.SalesCommissionRatio3
		case "sales_commission_ratio_4":
			r["sales_commission_ratio_4"] = a.SalesCommissionRatio4
		case "sales_commission_ratio_5":
			r["sales_commission_ratio_5"] = a.SalesCommissionRatio5
		case "sales_commission_ratio_6":
			r["sales_commission_ratio_6"] = a.SalesCommissionRatio6
		case "sales_commission_ratio_7":
			r["sales_commission_ratio_7"] = a.SalesCommissionRatio7
		case "sales_commission_ratio_8":
			r["sales_commission_ratio_8"] = a.SalesCommissionRatio8
		case "sales_commission_ratio_9":
			r["sales_commission_ratio_9"] = a.SalesCommissionRatio9
		case "sales_commission_ratio_10":
			r["sales_commission_ratio_10"] = a.SalesCommissionRatio10
		case "created":
			r["created"] = a.Created
		case "updated":
			r["updated"] = a.Updated
		case "disabled":
			r["disabled"] = a.Disabled
		case "role_ids":
			r["role_ids"] = a.RoleIds
		}
	}
	return r
}

func (a *OfficialCustomerAgentLevel) ListPage(cond *db.Compounds, sorts ...interface{}) error {
	_, err := pagination.NewLister(a, nil, func(r db.Result) db.Result {
		return r.OrderBy(sorts...)
	}, cond.And()).Paging(a.Context())
	return err
}

func (a *OfficialCustomerAgentLevel) ListPageAs(recv interface{}, cond *db.Compounds, sorts ...interface{}) error {
	_, err := pagination.NewLister(a, recv, func(r db.Result) db.Result {
		return r.OrderBy(sorts...)
	}, cond.And()).Paging(a.Context())
	return err
}

func (a *OfficialCustomerAgentLevel) BatchValidate(kvset map[string]interface{}) error {
	if kvset == nil {
		kvset = a.AsRow()
	}
	return DBI.Fields.BatchValidate(a.Short_(), kvset)
}

func (a *OfficialCustomerAgentLevel) Validate(field string, value interface{}) error {
	return DBI.Fields.Validate(a.Short_(), field, value)
}
