// @generated Do not edit this file, which is automatically generated by the generator.

package dbschema

import (
	"fmt"

	"time"

	"github.com/webx-top/com"
	"github.com/webx-top/db"
	"github.com/webx-top/db/lib/factory"
	"github.com/webx-top/db/lib/factory/pagination"
	"github.com/webx-top/echo"
	"github.com/webx-top/echo/param"
)

type Slice_OfficialCustomerInvitationUsed = factory.Slicex[*OfficialCustomerInvitationUsed]

func NewOfficialCustomerInvitationUsed(ctx echo.Context) *OfficialCustomerInvitationUsed {
	m := &OfficialCustomerInvitationUsed{}
	m.SetContext(ctx)
	return m
}

// OfficialCustomerInvitationUsed 邀请客户
type OfficialCustomerInvitationUsed struct {
	base    factory.Base
	objects []*OfficialCustomerInvitationUsed

	Id           uint64 `db:"id,omitempty,pk" bson:"id,omitempty" comment:"ID" json:"id" xml:"id"`
	CustomerId   uint64 `db:"customer_id" bson:"customer_id" comment:"客户ID" json:"customer_id" xml:"customer_id"`
	InvitationId uint   `db:"invitation_id" bson:"invitation_id" comment:"邀请码ID" json:"invitation_id" xml:"invitation_id"`
	Created      uint   `db:"created" bson:"created" comment:"创建时间" json:"created" xml:"created" form_decoder:"time2unix" form_encoder:"unix2time"`
	LevelId      uint   `db:"level_id" bson:"level_id" comment:"客户等级ID" json:"level_id" xml:"level_id"`
	AgentLevelId uint   `db:"agent_level_id" bson:"agent_level_id" comment:"代理等级ID" json:"agent_level_id" xml:"agent_level_id"`
	RoleIds      string `db:"role_ids" bson:"role_ids" comment:"注册为角色(多个用“,”分隔开)" json:"role_ids" xml:"role_ids"`
}

// - base function

func (a *OfficialCustomerInvitationUsed) Trans() factory.Transactioner {
	return a.base.Trans()
}

func (a *OfficialCustomerInvitationUsed) Use(trans factory.Transactioner) factory.Model {
	a.base.Use(trans)
	return a
}

func (a *OfficialCustomerInvitationUsed) SetContext(ctx echo.Context) factory.Model {
	a.base.SetContext(ctx)
	return a
}

func (a *OfficialCustomerInvitationUsed) EventON(on ...bool) factory.Model {
	a.base.EventON(on...)
	return a
}

func (a *OfficialCustomerInvitationUsed) EventOFF(off ...bool) factory.Model {
	a.base.EventOFF(off...)
	return a
}

func (a *OfficialCustomerInvitationUsed) Context() echo.Context {
	return a.base.Context()
}

func (a *OfficialCustomerInvitationUsed) SetConnID(connID int) factory.Model {
	a.base.SetConnID(connID)
	return a
}

func (a *OfficialCustomerInvitationUsed) ConnID() int {
	return a.base.ConnID()
}

func (a *OfficialCustomerInvitationUsed) SetNamer(namer func(factory.Model) string) factory.Model {
	a.base.SetNamer(namer)
	return a
}

func (a *OfficialCustomerInvitationUsed) Namer() func(factory.Model) string {
	return a.base.Namer()
}

func (a *OfficialCustomerInvitationUsed) SetParam(param *factory.Param) factory.Model {
	a.base.SetParam(param)
	return a
}

func (a *OfficialCustomerInvitationUsed) Param(mw func(db.Result) db.Result, args ...interface{}) *factory.Param {
	if a.base.Param() == nil {
		return a.NewParam().SetMiddleware(mw).SetArgs(args...)
	}
	return a.base.Param().SetMiddleware(mw).SetArgs(args...)
}

func (a *OfficialCustomerInvitationUsed) New(structName string, connID ...int) factory.Model {
	return a.base.New(structName, connID...)
}

func (a *OfficialCustomerInvitationUsed) Base_() factory.Baser {
	return &a.base
}

// - current function

func (a *OfficialCustomerInvitationUsed) Objects() []*OfficialCustomerInvitationUsed {
	if a.objects == nil {
		return nil
	}
	return a.objects[:]
}

func (a *OfficialCustomerInvitationUsed) XObjects() Slice_OfficialCustomerInvitationUsed {
	return Slice_OfficialCustomerInvitationUsed(a.Objects())
}

func (a *OfficialCustomerInvitationUsed) NewObjects() factory.Ranger {
	return &Slice_OfficialCustomerInvitationUsed{}
}

func (a *OfficialCustomerInvitationUsed) InitObjects() *[]*OfficialCustomerInvitationUsed {
	a.objects = []*OfficialCustomerInvitationUsed{}
	return &a.objects
}

func (a *OfficialCustomerInvitationUsed) NewParam() *factory.Param {
	return factory.NewParam(factory.DefaultFactory).SetIndex(a.base.ConnID()).SetTrans(a.base.Trans()).SetCollection(a.Name_()).SetModel(a)
}

func (a *OfficialCustomerInvitationUsed) Short_() string {
	return "official_customer_invitation_used"
}

func (a *OfficialCustomerInvitationUsed) Struct_() string {
	return "OfficialCustomerInvitationUsed"
}

func (a *OfficialCustomerInvitationUsed) Name_() string {
	b := a
	if b == nil {
		b = &OfficialCustomerInvitationUsed{}
	}
	if b.base.Namer() != nil {
		return WithPrefix(b.base.Namer()(b))
	}
	return WithPrefix(factory.TableNamerGet(b.Short_())(b))
}

// CPAFrom Deprecated: Use CtxFrom instead.
func (a *OfficialCustomerInvitationUsed) CPAFrom(source factory.Model) factory.Model {
	return a.CtxFrom(source)
}

func (a *OfficialCustomerInvitationUsed) CtxFrom(source factory.Model) factory.Model {
	a.base.CtxFrom(source)
	return a
}

func (a *OfficialCustomerInvitationUsed) Get(mw func(db.Result) db.Result, args ...interface{}) (err error) {
	base := a.base
	if !a.base.Eventable() {
		err = a.Param(mw, args...).SetRecv(a).One()
		a.base = base
		return
	}
	queryParam := a.Param(mw, args...).SetRecv(a)
	if err = a.base.FireReading(a, queryParam); err != nil {
		return
	}
	err = queryParam.One()
	a.base = base
	if err == nil {
		err = a.base.FireReaded(a, queryParam)
	}
	return
}

func (a *OfficialCustomerInvitationUsed) List(recv interface{}, mw func(db.Result) db.Result, page, size int, args ...interface{}) (func() int64, error) {
	if recv == nil {
		recv = a.InitObjects()
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetPage(page).SetSize(size).SetRecv(recv).List()
	}
	queryParam := a.Param(mw, args...).SetPage(page).SetSize(size).SetRecv(recv)
	if err := a.base.FireReading(a, queryParam); err != nil {
		return nil, err
	}
	cnt, err := queryParam.List()
	if err == nil {
		switch v := recv.(type) {
		case *[]*OfficialCustomerInvitationUsed:
			err = a.base.FireReaded(a, queryParam, Slice_OfficialCustomerInvitationUsed(*v))
		case []*OfficialCustomerInvitationUsed:
			err = a.base.FireReaded(a, queryParam, Slice_OfficialCustomerInvitationUsed(v))
		case factory.Ranger:
			err = a.base.FireReaded(a, queryParam, v)
		}
	}
	return cnt, err
}

func (a *OfficialCustomerInvitationUsed) GroupBy(keyField string, inputRows ...[]*OfficialCustomerInvitationUsed) map[string][]*OfficialCustomerInvitationUsed {
	var rows Slice_OfficialCustomerInvitationUsed
	if len(inputRows) > 0 {
		rows = Slice_OfficialCustomerInvitationUsed(inputRows[0])
	} else {
		rows = Slice_OfficialCustomerInvitationUsed(a.Objects())
	}
	return rows.GroupBy(keyField)
}

func (a *OfficialCustomerInvitationUsed) KeyBy(keyField string, inputRows ...[]*OfficialCustomerInvitationUsed) map[string]*OfficialCustomerInvitationUsed {
	var rows Slice_OfficialCustomerInvitationUsed
	if len(inputRows) > 0 {
		rows = Slice_OfficialCustomerInvitationUsed(inputRows[0])
	} else {
		rows = Slice_OfficialCustomerInvitationUsed(a.Objects())
	}
	return rows.KeyBy(keyField)
}

func (a *OfficialCustomerInvitationUsed) AsKV(keyField string, valueField string, inputRows ...[]*OfficialCustomerInvitationUsed) param.Store {
	var rows Slice_OfficialCustomerInvitationUsed
	if len(inputRows) > 0 {
		rows = Slice_OfficialCustomerInvitationUsed(inputRows[0])
	} else {
		rows = Slice_OfficialCustomerInvitationUsed(a.Objects())
	}
	return rows.AsKV(keyField, valueField)
}

func (a *OfficialCustomerInvitationUsed) ListByOffset(recv interface{}, mw func(db.Result) db.Result, offset, size int, args ...interface{}) (func() int64, error) {
	if recv == nil {
		recv = a.InitObjects()
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetOffset(offset).SetSize(size).SetRecv(recv).List()
	}
	queryParam := a.Param(mw, args...).SetOffset(offset).SetSize(size).SetRecv(recv)
	if err := a.base.FireReading(a, queryParam); err != nil {
		return nil, err
	}
	cnt, err := queryParam.List()
	if err == nil {
		switch v := recv.(type) {
		case *[]*OfficialCustomerInvitationUsed:
			err = a.base.FireReaded(a, queryParam, Slice_OfficialCustomerInvitationUsed(*v))
		case []*OfficialCustomerInvitationUsed:
			err = a.base.FireReaded(a, queryParam, Slice_OfficialCustomerInvitationUsed(v))
		case factory.Ranger:
			err = a.base.FireReaded(a, queryParam, v)
		}
	}
	return cnt, err
}

func (a *OfficialCustomerInvitationUsed) Insert() (pk interface{}, err error) {
	a.Created = uint(time.Now().Unix())
	a.Id = 0
	if a.base.Eventable() {
		err = a.base.Fire(factory.EventCreating, a, nil)
		if err != nil {
			return
		}
	}
	pk, err = a.Param(nil).SetSend(a).Insert()
	if err == nil && pk != nil {
		if v, y := pk.(uint64); y {
			a.Id = v
		} else if v, y := pk.(int64); y {
			a.Id = uint64(v)
		}
	}
	if err == nil && a.base.Eventable() {
		err = a.base.Fire(factory.EventCreated, a, nil)
	}
	return
}

func (a *OfficialCustomerInvitationUsed) Update(mw func(db.Result) db.Result, args ...interface{}) (err error) {

	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(a).Update()
	}
	if err = a.base.Fire(factory.EventUpdating, a, mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).SetSend(a).Update(); err != nil {
		return
	}
	return a.base.Fire(factory.EventUpdated, a, mw, args...)
}

func (a *OfficialCustomerInvitationUsed) Updatex(mw func(db.Result) db.Result, args ...interface{}) (affected int64, err error) {

	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(a).Updatex()
	}
	if err = a.base.Fire(factory.EventUpdating, a, mw, args...); err != nil {
		return
	}
	if affected, err = a.Param(mw, args...).SetSend(a).Updatex(); err != nil {
		return
	}
	err = a.base.Fire(factory.EventUpdated, a, mw, args...)
	return
}

func (a *OfficialCustomerInvitationUsed) UpdateByFields(mw func(db.Result) db.Result, fields []string, args ...interface{}) (err error) {

	if !a.base.Eventable() {
		return a.Param(mw, args...).UpdateByStruct(a, fields...)
	}
	editColumns := make([]string, len(fields))
	for index, field := range fields {
		editColumns[index] = com.SnakeCase(field)
	}
	if err = a.base.FireUpdate(factory.EventUpdating, a, editColumns, mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).UpdateByStruct(a, fields...); err != nil {
		return
	}
	err = a.base.FireUpdate(factory.EventUpdated, a, editColumns, mw, args...)
	return
}

func (a *OfficialCustomerInvitationUsed) UpdatexByFields(mw func(db.Result) db.Result, fields []string, args ...interface{}) (affected int64, err error) {

	if !a.base.Eventable() {
		return a.Param(mw, args...).UpdatexByStruct(a, fields...)
	}
	editColumns := make([]string, len(fields))
	for index, field := range fields {
		editColumns[index] = com.SnakeCase(field)
	}
	if err = a.base.FireUpdate(factory.EventUpdating, a, editColumns, mw, args...); err != nil {
		return
	}
	if affected, err = a.Param(mw, args...).UpdatexByStruct(a, fields...); err != nil {
		return
	}
	err = a.base.FireUpdate(factory.EventUpdated, a, editColumns, mw, args...)
	return
}

func (a *OfficialCustomerInvitationUsed) UpdateField(mw func(db.Result) db.Result, field string, value interface{}, args ...interface{}) (err error) {
	return a.UpdateFields(mw, map[string]interface{}{
		field: value,
	}, args...)
}

func (a *OfficialCustomerInvitationUsed) UpdatexField(mw func(db.Result) db.Result, field string, value interface{}, args ...interface{}) (affected int64, err error) {
	return a.UpdatexFields(mw, map[string]interface{}{
		field: value,
	}, args...)
}

func (a *OfficialCustomerInvitationUsed) UpdateFields(mw func(db.Result) db.Result, kvset map[string]interface{}, args ...interface{}) (err error) {

	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(kvset).Update()
	}
	m := *a
	m.FromRow(kvset)
	editColumns := make([]string, 0, len(kvset))
	for column := range kvset {
		editColumns = append(editColumns, column)
	}
	if err = a.base.FireUpdate(factory.EventUpdating, &m, editColumns, mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).SetSend(kvset).Update(); err != nil {
		return
	}
	return a.base.FireUpdate(factory.EventUpdated, &m, editColumns, mw, args...)
}

func (a *OfficialCustomerInvitationUsed) UpdatexFields(mw func(db.Result) db.Result, kvset map[string]interface{}, args ...interface{}) (affected int64, err error) {

	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(kvset).Updatex()
	}
	m := *a
	m.FromRow(kvset)
	editColumns := make([]string, 0, len(kvset))
	for column := range kvset {
		editColumns = append(editColumns, column)
	}
	if err = a.base.FireUpdate(factory.EventUpdating, &m, editColumns, mw, args...); err != nil {
		return
	}
	if affected, err = a.Param(mw, args...).SetSend(kvset).Updatex(); err != nil {
		return
	}
	err = a.base.FireUpdate(factory.EventUpdated, &m, editColumns, mw, args...)
	return
}

func (a *OfficialCustomerInvitationUsed) UpdateValues(mw func(db.Result) db.Result, keysValues *db.KeysValues, args ...interface{}) (err error) {
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(keysValues).Update()
	}
	m := *a
	m.FromRow(keysValues.Map())
	if err = a.base.FireUpdate(factory.EventUpdating, &m, keysValues.Keys(), mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).SetSend(keysValues).Update(); err != nil {
		return
	}
	return a.base.FireUpdate(factory.EventUpdated, &m, keysValues.Keys(), mw, args...)
}

func (a *OfficialCustomerInvitationUsed) Upsert(mw func(db.Result) db.Result, args ...interface{}) (pk interface{}, err error) {
	pk, err = a.Param(mw, args...).SetSend(a).Upsert(func() error {
		if !a.base.Eventable() {
			return nil
		}
		return a.base.Fire(factory.EventUpdating, a, mw, args...)
	}, func() error {
		a.Created = uint(time.Now().Unix())
		a.Id = 0
		if !a.base.Eventable() {
			return nil
		}
		return a.base.Fire(factory.EventCreating, a, nil)
	})
	if err == nil && pk != nil {
		if v, y := pk.(uint64); y {
			a.Id = v
		} else if v, y := pk.(int64); y {
			a.Id = uint64(v)
		}
	}
	if err == nil && a.base.Eventable() {
		if pk == nil {
			err = a.base.Fire(factory.EventUpdated, a, mw, args...)
		} else {
			err = a.base.Fire(factory.EventCreated, a, nil)
		}
	}
	return
}

func (a *OfficialCustomerInvitationUsed) Delete(mw func(db.Result) db.Result, args ...interface{}) (err error) {

	if !a.base.Eventable() {
		return a.Param(mw, args...).Delete()
	}
	if err = a.base.Fire(factory.EventDeleting, a, mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).Delete(); err != nil {
		return
	}
	return a.base.Fire(factory.EventDeleted, a, mw, args...)
}

func (a *OfficialCustomerInvitationUsed) Deletex(mw func(db.Result) db.Result, args ...interface{}) (affected int64, err error) {

	if !a.base.Eventable() {
		return a.Param(mw, args...).Deletex()
	}
	if err = a.base.Fire(factory.EventDeleting, a, mw, args...); err != nil {
		return
	}
	if affected, err = a.Param(mw, args...).Deletex(); err != nil {
		return
	}
	err = a.base.Fire(factory.EventDeleted, a, mw, args...)
	return
}

func (a *OfficialCustomerInvitationUsed) Count(mw func(db.Result) db.Result, args ...interface{}) (int64, error) {
	return a.Param(mw, args...).Count()
}

func (a *OfficialCustomerInvitationUsed) Exists(mw func(db.Result) db.Result, args ...interface{}) (bool, error) {
	return a.Param(mw, args...).Exists()
}

func (a *OfficialCustomerInvitationUsed) Reset() *OfficialCustomerInvitationUsed {
	a.Id = 0
	a.CustomerId = 0
	a.InvitationId = 0
	a.Created = 0
	a.LevelId = 0
	a.AgentLevelId = 0
	a.RoleIds = ``
	return a
}

func (a *OfficialCustomerInvitationUsed) AsMap(onlyFields ...string) param.Store {
	r := param.Store{}
	if len(onlyFields) == 0 {
		r["Id"] = a.Id
		r["CustomerId"] = a.CustomerId
		r["InvitationId"] = a.InvitationId
		r["Created"] = a.Created
		r["LevelId"] = a.LevelId
		r["AgentLevelId"] = a.AgentLevelId
		r["RoleIds"] = a.RoleIds
		return r
	}
	for _, field := range onlyFields {
		switch field {
		case "Id":
			r["Id"] = a.Id
		case "CustomerId":
			r["CustomerId"] = a.CustomerId
		case "InvitationId":
			r["InvitationId"] = a.InvitationId
		case "Created":
			r["Created"] = a.Created
		case "LevelId":
			r["LevelId"] = a.LevelId
		case "AgentLevelId":
			r["AgentLevelId"] = a.AgentLevelId
		case "RoleIds":
			r["RoleIds"] = a.RoleIds
		}
	}
	return r
}

func (a *OfficialCustomerInvitationUsed) Clone() *OfficialCustomerInvitationUsed {
	cloned := OfficialCustomerInvitationUsed{Id: a.Id, CustomerId: a.CustomerId, InvitationId: a.InvitationId, Created: a.Created, LevelId: a.LevelId, AgentLevelId: a.AgentLevelId, RoleIds: a.RoleIds}
	cloned.CtxFrom(a)
	return &cloned
}

func (a *OfficialCustomerInvitationUsed) FromRow(row map[string]interface{}) {
	for key, value := range row {
		if _, ok := value.(db.RawValue); ok {
			continue
		}
		switch key {
		case "id":
			a.Id = param.AsUint64(value)
		case "customer_id":
			a.CustomerId = param.AsUint64(value)
		case "invitation_id":
			a.InvitationId = param.AsUint(value)
		case "created":
			a.Created = param.AsUint(value)
		case "level_id":
			a.LevelId = param.AsUint(value)
		case "agent_level_id":
			a.AgentLevelId = param.AsUint(value)
		case "role_ids":
			a.RoleIds = param.AsString(value)
		}
	}
}

func (a *OfficialCustomerInvitationUsed) GetField(field string) interface{} {
	switch field {
	case "Id":
		return a.Id
	case "CustomerId":
		return a.CustomerId
	case "InvitationId":
		return a.InvitationId
	case "Created":
		return a.Created
	case "LevelId":
		return a.LevelId
	case "AgentLevelId":
		return a.AgentLevelId
	case "RoleIds":
		return a.RoleIds
	default:
		return nil
	}
}

func (a *OfficialCustomerInvitationUsed) GetAllFieldNames() []string {
	return []string{
		"Id",
		"CustomerId",
		"InvitationId",
		"Created",
		"LevelId",
		"AgentLevelId",
		"RoleIds",
	}
}

func (a *OfficialCustomerInvitationUsed) HasField(field string) bool {
	switch field {
	case "Id":
		return true
	case "CustomerId":
		return true
	case "InvitationId":
		return true
	case "Created":
		return true
	case "LevelId":
		return true
	case "AgentLevelId":
		return true
	case "RoleIds":
		return true
	default:
		return false
	}
}

func (a *OfficialCustomerInvitationUsed) Set(key interface{}, value ...interface{}) {
	switch k := key.(type) {
	case map[string]interface{}:
		for kk, vv := range k {
			a.Set(kk, vv)
		}
	default:
		var (
			kk string
			vv interface{}
		)
		if k, y := key.(string); y {
			kk = k
		} else {
			kk = fmt.Sprint(key)
		}
		if len(value) > 0 {
			vv = value[0]
		}
		switch kk {
		case "Id":
			a.Id = param.AsUint64(vv)
		case "CustomerId":
			a.CustomerId = param.AsUint64(vv)
		case "InvitationId":
			a.InvitationId = param.AsUint(vv)
		case "Created":
			a.Created = param.AsUint(vv)
		case "LevelId":
			a.LevelId = param.AsUint(vv)
		case "AgentLevelId":
			a.AgentLevelId = param.AsUint(vv)
		case "RoleIds":
			a.RoleIds = param.AsString(vv)
		}
	}
}

func (a *OfficialCustomerInvitationUsed) AsRow(onlyFields ...string) param.Store {
	r := param.Store{}
	if len(onlyFields) == 0 {
		r["id"] = a.Id
		r["customer_id"] = a.CustomerId
		r["invitation_id"] = a.InvitationId
		r["created"] = a.Created
		r["level_id"] = a.LevelId
		r["agent_level_id"] = a.AgentLevelId
		r["role_ids"] = a.RoleIds
		return r
	}
	for _, field := range onlyFields {
		switch field {
		case "id":
			r["id"] = a.Id
		case "customer_id":
			r["customer_id"] = a.CustomerId
		case "invitation_id":
			r["invitation_id"] = a.InvitationId
		case "created":
			r["created"] = a.Created
		case "level_id":
			r["level_id"] = a.LevelId
		case "agent_level_id":
			r["agent_level_id"] = a.AgentLevelId
		case "role_ids":
			r["role_ids"] = a.RoleIds
		}
	}
	return r
}

func (a *OfficialCustomerInvitationUsed) ListPage(cond *db.Compounds, sorts ...interface{}) error {
	return pagination.ListPage(a, cond, sorts...)
}

func (a *OfficialCustomerInvitationUsed) ListPageAs(recv interface{}, cond *db.Compounds, sorts ...interface{}) error {
	return pagination.ListPageAs(a, recv, cond, sorts...)
}

func (a *OfficialCustomerInvitationUsed) ListPageByOffset(cond *db.Compounds, sorts ...interface{}) error {
	return pagination.ListPageByOffset(a, cond, sorts...)
}

func (a *OfficialCustomerInvitationUsed) ListPageByOffsetAs(recv interface{}, cond *db.Compounds, sorts ...interface{}) error {
	return pagination.ListPageByOffsetAs(a, recv, cond, sorts...)
}

func (a *OfficialCustomerInvitationUsed) BatchValidate(kvset map[string]interface{}) error {
	return a.base.BatchValidate(a, kvset)
}

func (a *OfficialCustomerInvitationUsed) Validate(column string, value interface{}) error {
	return a.base.Validate(a, column, value)
}

func (a *OfficialCustomerInvitationUsed) TrimOverflowText(column string, value string) string {
	return a.base.TrimOverflowText(a, column, value)
}
