// @generated Do not edit this file, which is automatically generated by the generator.

package dbschema

import (
	"fmt"

	"time"

	"github.com/webx-top/com"
	"github.com/webx-top/db"
	"github.com/webx-top/db/lib/factory"
	"github.com/webx-top/db/lib/factory/pagination"
	"github.com/webx-top/echo"
	"github.com/webx-top/echo/param"
)

type Slice_OfficialCommonMessageViewed []*OfficialCommonMessageViewed

func (s Slice_OfficialCommonMessageViewed) Range(fn func(m factory.Model) error) error {
	for _, v := range s {
		if err := fn(v); err != nil {
			return err
		}
	}
	return nil
}

func (s Slice_OfficialCommonMessageViewed) RangeRaw(fn func(m *OfficialCommonMessageViewed) error) error {
	for _, v := range s {
		if err := fn(v); err != nil {
			return err
		}
	}
	return nil
}

func (s Slice_OfficialCommonMessageViewed) GroupBy(keyField string) map[string][]*OfficialCommonMessageViewed {
	r := map[string][]*OfficialCommonMessageViewed{}
	for _, row := range s {
		dmap := row.AsMap()
		vkey := fmt.Sprint(dmap[keyField])
		if _, y := r[vkey]; !y {
			r[vkey] = []*OfficialCommonMessageViewed{}
		}
		r[vkey] = append(r[vkey], row)
	}
	return r
}

func (s Slice_OfficialCommonMessageViewed) KeyBy(keyField string) map[string]*OfficialCommonMessageViewed {
	r := map[string]*OfficialCommonMessageViewed{}
	for _, row := range s {
		dmap := row.AsMap()
		vkey := fmt.Sprint(dmap[keyField])
		r[vkey] = row
	}
	return r
}

func (s Slice_OfficialCommonMessageViewed) AsKV(keyField string, valueField string) param.Store {
	r := param.Store{}
	for _, row := range s {
		dmap := row.AsMap()
		vkey := fmt.Sprint(dmap[keyField])
		r[vkey] = dmap[valueField]
	}
	return r
}

func (s Slice_OfficialCommonMessageViewed) Transform(transfers map[string]param.Transfer) []param.Store {
	r := make([]param.Store, len(s))
	for idx, row := range s {
		r[idx] = row.AsMap().Transform(transfers)
	}
	return r
}

func (s Slice_OfficialCommonMessageViewed) FromList(data interface{}) Slice_OfficialCommonMessageViewed {
	values, ok := data.([]*OfficialCommonMessageViewed)
	if !ok {
		for _, value := range data.([]interface{}) {
			row := &OfficialCommonMessageViewed{}
			row.FromRow(value.(map[string]interface{}))
			s = append(s, row)
		}
		return s
	}
	s = append(s, values...)

	return s
}

func NewOfficialCommonMessageViewed(ctx echo.Context) *OfficialCommonMessageViewed {
	m := &OfficialCommonMessageViewed{}
	m.SetContext(ctx)
	return m
}

// OfficialCommonMessageViewed 消息浏览记录
type OfficialCommonMessageViewed struct {
	base    factory.Base
	objects []*OfficialCommonMessageViewed

	MessageId  uint64 `db:"message_id,pk" bson:"message_id" comment:"消息ID" json:"message_id" xml:"message_id"`
	ViewerId   uint64 `db:"viewer_id,pk" bson:"viewer_id" comment:"浏览者ID" json:"viewer_id" xml:"viewer_id"`
	ViewerType string `db:"viewer_type,pk" bson:"viewer_type" comment:"浏览者类型" json:"viewer_type" xml:"viewer_type"`
	Created    uint   `db:"created" bson:"created" comment:"查看时间" json:"created" xml:"created"`
}

// - base function

func (a *OfficialCommonMessageViewed) Trans() factory.Transactioner {
	return a.base.Trans()
}

func (a *OfficialCommonMessageViewed) Use(trans factory.Transactioner) factory.Model {
	a.base.Use(trans)
	return a
}

func (a *OfficialCommonMessageViewed) SetContext(ctx echo.Context) factory.Model {
	a.base.SetContext(ctx)
	return a
}

func (a *OfficialCommonMessageViewed) EventON(on ...bool) factory.Model {
	a.base.EventON(on...)
	return a
}

func (a *OfficialCommonMessageViewed) EventOFF(off ...bool) factory.Model {
	a.base.EventOFF(off...)
	return a
}

func (a *OfficialCommonMessageViewed) Context() echo.Context {
	return a.base.Context()
}

func (a *OfficialCommonMessageViewed) SetConnID(connID int) factory.Model {
	a.base.SetConnID(connID)
	return a
}

func (a *OfficialCommonMessageViewed) ConnID() int {
	return a.base.ConnID()
}

func (a *OfficialCommonMessageViewed) SetNamer(namer func(factory.Model) string) factory.Model {
	a.base.SetNamer(namer)
	return a
}

func (a *OfficialCommonMessageViewed) Namer() func(factory.Model) string {
	return a.base.Namer()
}

func (a *OfficialCommonMessageViewed) SetParam(param *factory.Param) factory.Model {
	a.base.SetParam(param)
	return a
}

func (a *OfficialCommonMessageViewed) Param(mw func(db.Result) db.Result, args ...interface{}) *factory.Param {
	if a.base.Param() == nil {
		return a.NewParam().SetMiddleware(mw).SetArgs(args...)
	}
	return a.base.Param().SetMiddleware(mw).SetArgs(args...)
}

func (a *OfficialCommonMessageViewed) New(structName string, connID ...int) factory.Model {
	return a.base.New(structName, connID...)
}

func (a *OfficialCommonMessageViewed) Base_() factory.Baser {
	return &a.base
}

// - current function

func (a *OfficialCommonMessageViewed) Objects() []*OfficialCommonMessageViewed {
	if a.objects == nil {
		return nil
	}
	return a.objects[:]
}

func (a *OfficialCommonMessageViewed) XObjects() Slice_OfficialCommonMessageViewed {
	return Slice_OfficialCommonMessageViewed(a.Objects())
}

func (a *OfficialCommonMessageViewed) NewObjects() factory.Ranger {
	return &Slice_OfficialCommonMessageViewed{}
}

func (a *OfficialCommonMessageViewed) InitObjects() *[]*OfficialCommonMessageViewed {
	a.objects = []*OfficialCommonMessageViewed{}
	return &a.objects
}

func (a *OfficialCommonMessageViewed) NewParam() *factory.Param {
	return factory.NewParam(factory.DefaultFactory).SetIndex(a.base.ConnID()).SetTrans(a.base.Trans()).SetCollection(a.Name_()).SetModel(a)
}

func (a *OfficialCommonMessageViewed) Short_() string {
	return "official_common_message_viewed"
}

func (a *OfficialCommonMessageViewed) Struct_() string {
	return "OfficialCommonMessageViewed"
}

func (a *OfficialCommonMessageViewed) Name_() string {
	b := a
	if b == nil {
		b = &OfficialCommonMessageViewed{}
	}
	if b.base.Namer() != nil {
		return WithPrefix(b.base.Namer()(b))
	}
	return WithPrefix(factory.TableNamerGet(b.Short_())(b))
}

func (a *OfficialCommonMessageViewed) CPAFrom(source factory.Model) factory.Model {
	a.SetContext(source.Context())
	a.SetConnID(source.ConnID())
	a.SetNamer(source.Namer())
	return a
}

func (a *OfficialCommonMessageViewed) Get(mw func(db.Result) db.Result, args ...interface{}) (err error) {
	base := a.base
	if !a.base.Eventable() {
		err = a.Param(mw, args...).SetRecv(a).One()
		a.base = base
		return
	}
	queryParam := a.Param(mw, args...).SetRecv(a)
	if err = DBI.FireReading(a, queryParam); err != nil {
		return
	}
	err = queryParam.One()
	a.base = base
	if err == nil {
		err = DBI.FireReaded(a, queryParam)
	}
	return
}

func (a *OfficialCommonMessageViewed) List(recv interface{}, mw func(db.Result) db.Result, page, size int, args ...interface{}) (func() int64, error) {
	if recv == nil {
		recv = a.InitObjects()
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetPage(page).SetSize(size).SetRecv(recv).List()
	}
	queryParam := a.Param(mw, args...).SetPage(page).SetSize(size).SetRecv(recv)
	if err := DBI.FireReading(a, queryParam); err != nil {
		return nil, err
	}
	cnt, err := queryParam.List()
	if err == nil {
		switch v := recv.(type) {
		case *[]*OfficialCommonMessageViewed:
			err = DBI.FireReaded(a, queryParam, Slice_OfficialCommonMessageViewed(*v))
		case []*OfficialCommonMessageViewed:
			err = DBI.FireReaded(a, queryParam, Slice_OfficialCommonMessageViewed(v))
		case factory.Ranger:
			err = DBI.FireReaded(a, queryParam, v)
		}
	}
	return cnt, err
}

func (a *OfficialCommonMessageViewed) GroupBy(keyField string, inputRows ...[]*OfficialCommonMessageViewed) map[string][]*OfficialCommonMessageViewed {
	var rows Slice_OfficialCommonMessageViewed
	if len(inputRows) > 0 {
		rows = Slice_OfficialCommonMessageViewed(inputRows[0])
	} else {
		rows = Slice_OfficialCommonMessageViewed(a.Objects())
	}
	return rows.GroupBy(keyField)
}

func (a *OfficialCommonMessageViewed) KeyBy(keyField string, inputRows ...[]*OfficialCommonMessageViewed) map[string]*OfficialCommonMessageViewed {
	var rows Slice_OfficialCommonMessageViewed
	if len(inputRows) > 0 {
		rows = Slice_OfficialCommonMessageViewed(inputRows[0])
	} else {
		rows = Slice_OfficialCommonMessageViewed(a.Objects())
	}
	return rows.KeyBy(keyField)
}

func (a *OfficialCommonMessageViewed) AsKV(keyField string, valueField string, inputRows ...[]*OfficialCommonMessageViewed) param.Store {
	var rows Slice_OfficialCommonMessageViewed
	if len(inputRows) > 0 {
		rows = Slice_OfficialCommonMessageViewed(inputRows[0])
	} else {
		rows = Slice_OfficialCommonMessageViewed(a.Objects())
	}
	return rows.AsKV(keyField, valueField)
}

func (a *OfficialCommonMessageViewed) ListByOffset(recv interface{}, mw func(db.Result) db.Result, offset, size int, args ...interface{}) (func() int64, error) {
	if recv == nil {
		recv = a.InitObjects()
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetOffset(offset).SetSize(size).SetRecv(recv).List()
	}
	queryParam := a.Param(mw, args...).SetOffset(offset).SetSize(size).SetRecv(recv)
	if err := DBI.FireReading(a, queryParam); err != nil {
		return nil, err
	}
	cnt, err := queryParam.List()
	if err == nil {
		switch v := recv.(type) {
		case *[]*OfficialCommonMessageViewed:
			err = DBI.FireReaded(a, queryParam, Slice_OfficialCommonMessageViewed(*v))
		case []*OfficialCommonMessageViewed:
			err = DBI.FireReaded(a, queryParam, Slice_OfficialCommonMessageViewed(v))
		case factory.Ranger:
			err = DBI.FireReaded(a, queryParam, v)
		}
	}
	return cnt, err
}

func (a *OfficialCommonMessageViewed) Insert() (pk interface{}, err error) {
	a.Created = uint(time.Now().Unix())
	if len(a.ViewerType) == 0 {
		a.ViewerType = "customer"
	}
	if a.base.Eventable() {
		err = DBI.Fire("creating", a, nil)
		if err != nil {
			return
		}
	}
	pk, err = a.Param(nil).SetSend(a).Insert()

	if err == nil && a.base.Eventable() {
		err = DBI.Fire("created", a, nil)
	}
	return
}

func (a *OfficialCommonMessageViewed) Update(mw func(db.Result) db.Result, args ...interface{}) (err error) {

	if len(a.ViewerType) == 0 {
		a.ViewerType = "customer"
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(a).Update()
	}
	if err = DBI.Fire("updating", a, mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).SetSend(a).Update(); err != nil {
		return
	}
	return DBI.Fire("updated", a, mw, args...)
}

func (a *OfficialCommonMessageViewed) Updatex(mw func(db.Result) db.Result, args ...interface{}) (affected int64, err error) {

	if len(a.ViewerType) == 0 {
		a.ViewerType = "customer"
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(a).Updatex()
	}
	if err = DBI.Fire("updating", a, mw, args...); err != nil {
		return
	}
	if affected, err = a.Param(mw, args...).SetSend(a).Updatex(); err != nil {
		return
	}
	err = DBI.Fire("updated", a, mw, args...)
	return
}

func (a *OfficialCommonMessageViewed) UpdateByFields(mw func(db.Result) db.Result, fields []string, args ...interface{}) (err error) {

	if len(a.ViewerType) == 0 {
		a.ViewerType = "customer"
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).UpdateByStruct(a, fields...)
	}
	editColumns := make([]string, len(fields))
	for index, field := range fields {
		editColumns[index] = com.SnakeCase(field)
	}
	if err = DBI.FireUpdate("updating", a, editColumns, mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).UpdateByStruct(a, fields...); err != nil {
		return
	}
	err = DBI.FireUpdate("updated", a, editColumns, mw, args...)
	return
}

func (a *OfficialCommonMessageViewed) UpdatexByFields(mw func(db.Result) db.Result, fields []string, args ...interface{}) (affected int64, err error) {

	if len(a.ViewerType) == 0 {
		a.ViewerType = "customer"
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).UpdatexByStruct(a, fields...)
	}
	editColumns := make([]string, len(fields))
	for index, field := range fields {
		editColumns[index] = com.SnakeCase(field)
	}
	if err = DBI.FireUpdate("updating", a, editColumns, mw, args...); err != nil {
		return
	}
	if affected, err = a.Param(mw, args...).UpdatexByStruct(a, fields...); err != nil {
		return
	}
	err = DBI.FireUpdate("updated", a, editColumns, mw, args...)
	return
}

func (a *OfficialCommonMessageViewed) UpdateField(mw func(db.Result) db.Result, field string, value interface{}, args ...interface{}) (err error) {
	return a.UpdateFields(mw, map[string]interface{}{
		field: value,
	}, args...)
}

func (a *OfficialCommonMessageViewed) UpdatexField(mw func(db.Result) db.Result, field string, value interface{}, args ...interface{}) (affected int64, err error) {
	return a.UpdatexFields(mw, map[string]interface{}{
		field: value,
	}, args...)
}

func (a *OfficialCommonMessageViewed) UpdateFields(mw func(db.Result) db.Result, kvset map[string]interface{}, args ...interface{}) (err error) {

	if val, ok := kvset["viewer_type"]; ok && val != nil {
		if v, ok := val.(string); ok && len(v) == 0 {
			kvset["viewer_type"] = "customer"
		}
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(kvset).Update()
	}
	m := *a
	m.FromRow(kvset)
	var editColumns []string
	for column := range kvset {
		editColumns = append(editColumns, column)
	}
	if err = DBI.FireUpdate("updating", &m, editColumns, mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).SetSend(kvset).Update(); err != nil {
		return
	}
	return DBI.FireUpdate("updated", &m, editColumns, mw, args...)
}

func (a *OfficialCommonMessageViewed) UpdatexFields(mw func(db.Result) db.Result, kvset map[string]interface{}, args ...interface{}) (affected int64, err error) {

	if val, ok := kvset["viewer_type"]; ok && val != nil {
		if v, ok := val.(string); ok && len(v) == 0 {
			kvset["viewer_type"] = "customer"
		}
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(kvset).Updatex()
	}
	m := *a
	m.FromRow(kvset)
	var editColumns []string
	for column := range kvset {
		editColumns = append(editColumns, column)
	}
	if err = DBI.FireUpdate("updating", &m, editColumns, mw, args...); err != nil {
		return
	}
	if affected, err = a.Param(mw, args...).SetSend(kvset).Updatex(); err != nil {
		return
	}
	err = DBI.FireUpdate("updated", &m, editColumns, mw, args...)
	return
}

func (a *OfficialCommonMessageViewed) UpdateValues(mw func(db.Result) db.Result, keysValues *db.KeysValues, args ...interface{}) (err error) {
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(keysValues).Update()
	}
	m := *a
	m.FromRow(keysValues.Map())
	if err = DBI.FireUpdate("updating", &m, keysValues.Keys(), mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).SetSend(keysValues).Update(); err != nil {
		return
	}
	return DBI.FireUpdate("updated", &m, keysValues.Keys(), mw, args...)
}

func (a *OfficialCommonMessageViewed) Upsert(mw func(db.Result) db.Result, args ...interface{}) (pk interface{}, err error) {
	pk, err = a.Param(mw, args...).SetSend(a).Upsert(func() error {
		if len(a.ViewerType) == 0 {
			a.ViewerType = "customer"
		}
		if !a.base.Eventable() {
			return nil
		}
		return DBI.Fire("updating", a, mw, args...)
	}, func() error {
		a.Created = uint(time.Now().Unix())
		if len(a.ViewerType) == 0 {
			a.ViewerType = "customer"
		}
		if !a.base.Eventable() {
			return nil
		}
		return DBI.Fire("creating", a, nil)
	})

	if err == nil && a.base.Eventable() {
		if pk == nil {
			err = DBI.Fire("updated", a, mw, args...)
		} else {
			err = DBI.Fire("created", a, nil)
		}
	}
	return
}

func (a *OfficialCommonMessageViewed) Delete(mw func(db.Result) db.Result, args ...interface{}) (err error) {

	if !a.base.Eventable() {
		return a.Param(mw, args...).Delete()
	}
	if err = DBI.Fire("deleting", a, mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).Delete(); err != nil {
		return
	}
	return DBI.Fire("deleted", a, mw, args...)
}

func (a *OfficialCommonMessageViewed) Deletex(mw func(db.Result) db.Result, args ...interface{}) (affected int64, err error) {

	if !a.base.Eventable() {
		return a.Param(mw, args...).Deletex()
	}
	if err = DBI.Fire("deleting", a, mw, args...); err != nil {
		return
	}
	if affected, err = a.Param(mw, args...).Deletex(); err != nil {
		return
	}
	err = DBI.Fire("deleted", a, mw, args...)
	return
}

func (a *OfficialCommonMessageViewed) Count(mw func(db.Result) db.Result, args ...interface{}) (int64, error) {
	return a.Param(mw, args...).Count()
}

func (a *OfficialCommonMessageViewed) Exists(mw func(db.Result) db.Result, args ...interface{}) (bool, error) {
	return a.Param(mw, args...).Exists()
}

func (a *OfficialCommonMessageViewed) Reset() *OfficialCommonMessageViewed {
	a.MessageId = 0
	a.ViewerId = 0
	a.ViewerType = ``
	a.Created = 0
	return a
}

func (a *OfficialCommonMessageViewed) AsMap(onlyFields ...string) param.Store {
	r := param.Store{}
	if len(onlyFields) == 0 {
		r["MessageId"] = a.MessageId
		r["ViewerId"] = a.ViewerId
		r["ViewerType"] = a.ViewerType
		r["Created"] = a.Created
		return r
	}
	for _, field := range onlyFields {
		switch field {
		case "MessageId":
			r["MessageId"] = a.MessageId
		case "ViewerId":
			r["ViewerId"] = a.ViewerId
		case "ViewerType":
			r["ViewerType"] = a.ViewerType
		case "Created":
			r["Created"] = a.Created
		}
	}
	return r
}

func (a *OfficialCommonMessageViewed) FromRow(row map[string]interface{}) {
	for key, value := range row {
		switch key {
		case "message_id":
			a.MessageId = param.AsUint64(value)
		case "viewer_id":
			a.ViewerId = param.AsUint64(value)
		case "viewer_type":
			a.ViewerType = param.AsString(value)
		case "created":
			a.Created = param.AsUint(value)
		}
	}
}

func (a *OfficialCommonMessageViewed) Set(key interface{}, value ...interface{}) {
	switch k := key.(type) {
	case map[string]interface{}:
		for kk, vv := range k {
			a.Set(kk, vv)
		}
	default:
		var (
			kk string
			vv interface{}
		)
		if k, y := key.(string); y {
			kk = k
		} else {
			kk = fmt.Sprint(key)
		}
		if len(value) > 0 {
			vv = value[0]
		}
		switch kk {
		case "MessageId":
			a.MessageId = param.AsUint64(vv)
		case "ViewerId":
			a.ViewerId = param.AsUint64(vv)
		case "ViewerType":
			a.ViewerType = param.AsString(vv)
		case "Created":
			a.Created = param.AsUint(vv)
		}
	}
}

func (a *OfficialCommonMessageViewed) AsRow(onlyFields ...string) param.Store {
	r := param.Store{}
	if len(onlyFields) == 0 {
		r["message_id"] = a.MessageId
		r["viewer_id"] = a.ViewerId
		r["viewer_type"] = a.ViewerType
		r["created"] = a.Created
		return r
	}
	for _, field := range onlyFields {
		switch field {
		case "message_id":
			r["message_id"] = a.MessageId
		case "viewer_id":
			r["viewer_id"] = a.ViewerId
		case "viewer_type":
			r["viewer_type"] = a.ViewerType
		case "created":
			r["created"] = a.Created
		}
	}
	return r
}

func (a *OfficialCommonMessageViewed) ListPage(cond *db.Compounds, sorts ...interface{}) error {
	_, err := pagination.NewLister(a, nil, func(r db.Result) db.Result {
		return r.OrderBy(sorts...)
	}, cond.And()).Paging(a.Context())
	return err
}

func (a *OfficialCommonMessageViewed) ListPageAs(recv interface{}, cond *db.Compounds, sorts ...interface{}) error {
	_, err := pagination.NewLister(a, recv, func(r db.Result) db.Result {
		return r.OrderBy(sorts...)
	}, cond.And()).Paging(a.Context())
	return err
}

func (a *OfficialCommonMessageViewed) BatchValidate(kvset map[string]interface{}) error {
	if kvset == nil {
		kvset = a.AsRow()
	}
	return DBI.Fields.BatchValidate(a.Short_(), kvset)
}

func (a *OfficialCommonMessageViewed) Validate(field string, value interface{}) error {
	return DBI.Fields.Validate(a.Short_(), field, value)
}
